### ISSUE TITLE
Multiple errors thrown when trying to Update Views in FT 3alpha

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#111]
When creating a form, I am trying to add a default value for new submissions to one of the fields which is a text area. The first time I create a default value everything works ok and the default value appears in a new submission. However, if you go back and try to either delete this default value or amend the text of the default value, the following error is thrown and the default value is not deleted or updated:

> Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-11' for key 'PRIMARY' in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/global/code/Database.class.php:142 Stack trace: #0 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/global/code/Database.class.php(142): PDOStatement->execute() #1 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/global/code/Views.class.php(810): FormTools\Database->execute() #2 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/global/code/Views.class.php(696): FormTools\Views::updateViewMainSettings('2', Array) #3 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/admin/forms/edit/page_edit_view.php(30): FormTools\Views::updateView('2', Array) #4 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/admin/forms/edit/index.php(122): require_once('/home/acutemed/...') #5 {main} thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/global/code/Database.class.php on line 142

**Comment by tomheaps** [comment]
Getting the same error when I try to 'Update View' after dragging the order of fields around for a given view.

**Comment by benkeen** [comment]
Thanks @tomheaps! I'll look at this now.

**Comment by benkeen** [comment]
Just a syntax problem with the DB query. I'll release a new alpha tonight containing this fix - thanks again!
