### ISSUE TITLE
Unable to create default form view

### ISSUE THREAD

**Issue by joshmckibbin** [formtools/core#112]
Trying to create a default view for my first form, throws this error:
`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'custom_data' doesn't have a default value in /var/www/html/formtools/global/code/Database.class.php:142 Stack trace: #0 /var/www/html/formtools/global/code/Database.class.php(142): PDOStatement->execute() #1 /var/www/html/formtools/global/code/Views.class.php(1082): FormTools\Database->execute() #2 /var/www/html/formtools/admin/forms/edit/page_views.php(28): FormTools\Views::addDefaultView('2') #3 /var/www/html/formtools/admin/forms/edit/index.php(122): require_once('/var/www/html/f...') #4 {main} thrown in /var/www/html/formtools/global/code/Database.class.php on line 142`

**Comment by benkeen** [comment]
Thanks! I'll include a fix for this in today's alpha build. I appreciate the bug report. :D
