### ISSUE TITLE
Date formatting, Text Override and Data Visualization bugs

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#113]
The date format function under Settings > Accounts does not seem to affect the formatting of dates entered into forms - I have changed the date format to 'd/m/y, H:i' for all clients however when a new form is created, the date on the form is still formatted in the default way i.e. **2017-11-29 7:18 PM** whereas I would expect it to be **29/11/17, 19:18**?

The text override module does not work correctly. Some simple strings e.g. word_update and word_client seem to get successfully overridden, however other phrases e.g. validation_wrong_password and text_login aren't overriding despite a successful 'The list of overridden strings has been updated' message?

Data Vizualization module does not work correctly - when trying to update Permissions, changes do not save, when trying to update Appearance, following error is thrown:

> Notice: Undefined variable: db in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/data_visualization/code/ActivityCharts.class.php on line 509
> 
> Fatal error: Uncaught Error: Call to a member function query() on null in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/data_visualization/code/ActivityCharts.class.php:509 Stack trace: #0 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/data_visualization/code/ActivityCharts.class.php(89): FormTools\Modules\DataVisualization\ActivityCharts::updateVisualizationAppearanceTab('3', Array) #1 /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/data_visualization/activity_charts/edit.php(25): FormTools\Modules\DataVisualization\ActivityCharts::updateActivityChart('3', 'appearance', Array, Array) #2 {main} thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/data_visualization/code/ActivityCharts.class.php on line 509

**Comment by benkeen** [comment]
Hey @tomheaps, 

Thanks for the bug reports! 

> The date format function under Settings > Accounts does not seem to affect the formatting of dates entered into forms - I have changed the date format to 'd/m/y, H:i' for all clients however when a new form is created, the date on the form is still formatted in the default way i.e. 2017-11-29 7:18 PM whereas I would expect it to be 29/11/17, 19:18?

This one is actually working properly. The formatting of dates within forms are done on the per-field level. To control that value, go to Edit Form -> Fields tab -> edit the individual date field. In the dialog window you'll find a setting (I think under the second tab...) where you can customize the date format. 

But this raises an interesting question: where IS that date format in the account section actually used?! It was definitely used at one point, but I don't see anywhere in the current codebase it's used. I'll keep this in mind for future updates.

> The text override module does not work correctly. Some simple strings e.g. word_update and word_client seem to get successfully overridden, however other phrases e.g. validation_wrong_password and text_login aren't overriding despite a successful 'The list of overridden strings has been updated' message?

Thanks for the heads up - sounds like a bug. I've flagged the issue your raised on the Text Override repo [https://github.com/formtools/module-text_override/issues/1] and I'll look at it for the next version. Is this issue holding you up at all, or you just happened to spot it? 

And yeah - nice clear bug with the Data Visualization repo. I'll patch that soon. 

Thanks again! Keep 'em comin'. ;-) 

Ben

**Comment by benkeen** [comment]
Edit: I've patched the issues with the Data Visualization in the latest release (2.0.4): https://github.com/formtools/module-data_visualization/releases/tag/2.0.4

**Comment by tomheaps** [comment]
Thanks Ben for your swift response! Apologies for lumping all these bugs together under core issues but I didn't know if you were actively monitoring issues on the module pages. Will post separately in future! 

I did wonder what the date format was actually doing!?

Text Override not a biggy - can just modify the language file directly for now and appreciate that you have more pressing issues to attend to!

Please keep up the great work.

**Comment by Dtrieb** [comment]
In Version 3.0.9. I set the lang to german and date to d.m.Y H:i:s but:

The Date selector shows English weeknames and the Time is 12h instead of german 24h format.

**Comment by benkeen** [comment]
Thanks @Dtrieb, I've created a separate issue for this & will look at it in the next release:
https://github.com/formtools/core/issues/387
