### ISSUE TITLE
Module installation not working

### ISSUE THREAD

**Issue by Rathilesh** [formtools/core#114]
Cant find any modules after copy the module  files inside the module folder
i tried both file upload module and form builder module

**Comment by benkeen** [comment]
Hi @Rathilesh, is this for Form Tools 3 or an earlier version of Form Tools?

**Comment by tomheaps** [comment]
When you download modules separately, the folders are named differently e.g. **module_data_visualization_2.0.4** and you have to rename it to **data_visualization** before it is recognized by the modules page in Form Tools.

**Comment by georGEO1989** [comment]
I'm also having this issue. I tried changing the data visualization to "data_visualization" and that did not work. I also tried changing the report builder into "report_builder" just for laughs but that also did not work.

**Comment by tomheaps** [comment]
Works for me in form tools 3 alpha. What version are you using?

**Comment by georGEO1989** [comment]
I am using 2.2.5. Fresh download and install. We are prototyping this, not sure if using an alpha version would be a good idea.

Is there a known fix for 2.2.5?

**Comment by benkeen** [comment]
Hey @georGEO1989 - I think you've moved onto FT3 now, but just in case anyone else encounters this thread, I think Google may have deprecated the older version of Google Charts referenced by Data Visualization version 1.x. So Form Tools 3 and the more recent versions of the Data Visualization modules are the way to go.
