### ISSUE TITLE
More bugs in Form Tools 3 Alpha...

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#116]
Have discovered more issues:

**1) Form Builder Module** - throws the same error as other modules did when trying to open from the modules page (update - I have managed to fix this by going through all templates changing` include `to `ft_include`)

> Fatal error: Uncaught --> Smarty: Unable to load template 'file:messages.tpl' in '/home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/form_builder/templates/index.tpl' <-- thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 185

I can use the form builder module via the 'Publish' tab when making a new form however if you click on 'edit the available template sets' from within this tab then the same error as above is thrown.

Also, when trying to delete a published form from within the 'Publish' tab, a 404 - page not found error is thrown after clicking on OK in the modal dialog to confirm deletion of the published form.

**2) Tiny MCE module** - still throwing the same error as above when trying to open this module from the modules page (update - same fix as above works, also still affecting other modules e.g. Arbitrary Settings)

**3) Can't allocate specific clients to a form** - on the `main settings tab` of a form when you choose `private (restrict access to specific users) `and add a user from `available clients` to `selected clients` then click `update`, your selection is not saved and the users you selected are not allocated to the form. Only way to add specific users to the form is to go into each user account and do it from forms tab.

**4) Users** - the 'Last Logged In' field is not updating - I have logged in multiple times as different users (not from within the admin account but from the main login page) and the 'Last Logged In' does not change from 'Never'

**5) Number of Submissions Box** - when I log in as a user and view a form with a client filter set so that users can only view their own submissions - the Number of Submissions box shows the total number of submissions by all users, even if that user has not created a form of that type which is very misleading to users - should this number not change depending on the number of forms that user can actually view??

**Comment by benkeen** [comment]
Hey @tomheaps - thanks again for the bug reports! I just released updates for the core, Form Builder and TinyMCE Field module. Issues 1-4 should now be resolved. I'll need some more time to investigate issue 5.

**Comment by tomheaps** [comment]
Thanks once again Ben. 

I was really pleased that you released the Form Backup module for FT3alpha yesterday however there are issues with it...

The module seems to work fine - I can go into it, select the desired options and create a backup of a particular form and receive the notification 'The form has been created. Click here to edit the form' however when I go to my main forms page, the copied form is not listed there.

I have checked in my SQL database and the backed up forms have been created with unique ids e.g. ft_form_11, ft_form_12, ft_form_13.

However when I look in the database at the ft_forms table, these newly created backup copies have not been added to it which probably explains why they are not visible from my main forms page online?

**Comment by benkeen** [comment]
Hey @tomheaps, hmm puzzler! I've been testing it out today but it's been working fine for me. Let me look over that particular piece of the logic - the adding of the new record in the forms table.

You don't get any errors at all? I don't suppose you see any errors appearing in your PHP error logs?

**Comment by tomheaps** [comment]
This is strange. I am able to successfully backup one of my forms properly but all attempts to backup any of my other forms fail as described above. 

1. No PHP errors are thrown at the time and the process seems to work but then the copied form is not visible in my forms list (but has been created in my database)

2. Checking the PHP error logs in the form builder module shows only these errors which probably aren't relevant:
> [17-Dec-2017 09:37:46 Europe/London] PHP Notice:  Undefined offset: 126 in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/form_backup/code/General.class.php on line 700
> [17-Dec-2017 12:22:11 Europe/London] PHP Notice:  Undefined offset: 2 in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/form_backup/code/General.class.php on line 700
> [17-Dec-2017 12:40:08 Europe/London] PHP Notice:  Undefined offset: 255 in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/form_backup/code/General.class.php on line 602

3. I am getting an error in the browser console when trying to backup a form but this error also appears when I successfully backup the one form that can be copied so again probably not relevant:
> jquery.js:16 Uncaught TypeError: Cannot read property '0' of undefined
>     at f.fx.step.(anonymous function) (https://warwickacutemedicine.co.uk/acportfolio/themes/acportfolio/scripts/jquery-ui-1.8.14.custom.min.js:483:226)
>     at fx.update (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:77116)
>     at fx.step (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:78868)
>     at g (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:77384)
>     at fx.custom (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:77573)
>     at String.<anonymous> (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:75912)
>     at Function.each (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:11386)
>     at HTMLDivElement.<anonymous> (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:75598)
>     at Function.each (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:11442)
>     at init.each (https://warwickacutemedicine.co.uk/acportfolio/global/scripts/jquery.js:16:8034)

4. I think the issue is something to do with the ID on the backup copy of the form created - when I run System Check module and look at Orphan Clean up after unsuccessfully trying to backup a form I can see that the copied form (ft_form_36 in the example below) is generating all sorts of errors:
> TABLE: ft_client_forms
> - num orphans: 1
> - error description: 
> 1. Invalid form ID: 36
> _______________________
> 
> TABLE: ft_email_template_edit_submission_views
> - num orphans: 3
> - error description: 
> 1. Invalid View ID: 76
> 2. Invalid View ID: 77
> 3. Invalid View ID: 78
> _______________________
> 
> TABLE: ft_email_template_when_sent_views
> - num orphans: 3
> - error description: 
> 1. invalid View ID 78
> 2. invalid View ID 77
> 3. invalid View ID 76
> _______________________
> 
> TABLE: ft_views
> - num orphans: 3
> - error description: 
> 1. Invalid reference to form_id 36 for view_id 94
> 2. Invalid reference to form_id 36 for view_id 93
> 3. Invalid reference to form_id 36 for view_id 92
> _______________________
> 
> TABLE: ft_view_columns
> - num orphans: 15
> - error description: 
> 1. Invalid reference to field_id 546 for view_id 94
> 2. Invalid reference to field_id 547 for view_id 94
> 3. Invalid reference to field_id 556 for view_id 94
> 4. Invalid reference to field_id 563 for view_id 94
> 5. Invalid reference to field_id 549 for view_id 93
> 6. Invalid reference to field_id 562 for view_id 94
> 7. Invalid reference to field_id 547 for view_id 93
> 8. Invalid reference to field_id 558 for view_id 93
> 9. Invalid reference to field_id 556 for view_id 93
> 10. Invalid reference to field_id 562 for view_id 93
> 11. Invalid reference to field_id 547 for view_id 92
> 12. Invalid reference to field_id 558 for view_id 92
> 13. Invalid reference to field_id 562 for view_id 92
> 14. Invalid reference to field_id 549 for view_id 92
> 15. Invalid reference to field_id 556 for view_id 92
> _______________________
> 
> TABLE: ft_view_fields
> - num orphans: 60
> - error description: 
> 1. Invalid reference to field_id 544 for view_id 94
> 2. Invalid reference to field_id 543 for view_id 94
> 3. Invalid reference to field_id 545 for view_id 94
> 4. Invalid reference to field_id 546 for view_id 94
> 5. Invalid reference to field_id 547 for view_id 94
> 6. Invalid reference to field_id 549 for view_id 94
> 7. Invalid reference to field_id 548 for view_id 94
> 8. Invalid reference to field_id 552 for view_id 94
> 9. Invalid reference to field_id 551 for view_id 94
> 10. Invalid reference to field_id 563 for view_id 94
> 11. Invalid reference to field_id 557 for view_id 94
> 12. Invalid reference to field_id 556 for view_id 94
> 13. Invalid reference to field_id 562 for view_id 94
> 14. Invalid reference to field_id 561 for view_id 94
> 15. Invalid reference to field_id 559 for view_id 94
> 16. Invalid reference to field_id 558 for view_id 94
> 17. Invalid reference to field_id 553 for view_id 94
> 18. Invalid reference to field_id 554 for view_id 94
> 19. Invalid reference to field_id 555 for view_id 94
> 20. Invalid reference to field_id 550 for view_id 94
> 21. Invalid reference to field_id 560 for view_id 94
> 22. Invalid reference to field_id 544 for view_id 93
> 23. Invalid reference to field_id 543 for view_id 93
> 24. Invalid reference to field_id 547 for view_id 93
> 25. Invalid reference to field_id 549 for view_id 93
> 26. Invalid reference to field_id 548 for view_id 93
> 27. Invalid reference to field_id 552 for view_id 93
> 28. Invalid reference to field_id 551 for view_id 93
> 29. Invalid reference to field_id 550 for view_id 93
> 30. Invalid reference to field_id 555 for view_id 93
> 31. Invalid reference to field_id 554 for view_id 93
> 32. Invalid reference to field_id 553 for view_id 93
> 33. Invalid reference to field_id 561 for view_id 93
> 34. Invalid reference to field_id 559 for view_id 93
> 35. Invalid reference to field_id 557 for view_id 93
> 36. Invalid reference to field_id 544 for view_id 92
> 37. Invalid reference to field_id 560 for view_id 93
> 38. Invalid reference to field_id 558 for view_id 93
> 39. Invalid reference to field_id 556 for view_id 93
> 40. Invalid reference to field_id 562 for view_id 93
> 41. Invalid reference to field_id 543 for view_id 92
> 42. Invalid reference to field_id 545 for view_id 92
> 43. Invalid reference to field_id 546 for view_id 92
> 44. Invalid reference to field_id 547 for view_id 92
> 45. Invalid reference to field_id 549 for view_id 92
> 46. Invalid reference to field_id 548 for view_id 92
> 47. Invalid reference to field_id 552 for view_id 92
> 48. Invalid reference to field_id 551 for view_id 92
> 49. Invalid reference to field_id 550 for view_id 92
> 50. Invalid reference to field_id 555 for view_id 92
> 51. Invalid reference to field_id 554 for view_id 92
> 52. Invalid reference to field_id 553 for view_id 92
> 53. Invalid reference to field_id 561 for view_id 92
> 54. Invalid reference to field_id 560 for view_id 92
> 55. Invalid reference to field_id 559 for view_id 92
> 56. Invalid reference to field_id 558 for view_id 92
> 57. Invalid reference to field_id 557 for view_id 92
> 58. Invalid reference to field_id 556 for view_id 92
> 59. Invalid reference to field_id 562 for view_id 92
> 60. Invalid reference to field_id 563 for view_id 92
> _______________________

5. Finally, when I use the System Check module and do Hook Verification, the process stalls on the Form Backup module, don't know if this is related?

Really hoping that this can be sorted as the ability to copy/backup forms is critical to my project.

Thanks.

**Comment by benkeen** [comment]
btw, I've created the following ticket regarding issue 5 in your original post in this thread: https://github.com/formtools/core/issues/118

**Comment by tomheaps** [comment]
Thanks @benkeen . On top of my Form Backup woes I'm having big issues now with Form Builder. 

When I go to add forms, the option to add a FormBuilder form has now completely disappeared and the 'Publish' tab on individual forms has also disappeared. All the forms I had made were of FormBuilder type and when I look at my list of Forms, the column for Form Type is showing blank for all of them.

The Form Builder module itself seems to be working OK (latest version 2.02) and I am not getting any errors in System Check for the form builder module.

This all seemed to happen after I upgraded Form Backup to 2.01 (with the addition of the backup button) but no idea why this should affect Form Builder?? I have tried uninstalling Form Backup and reverting back to 2.00 but the issues with Form Builder still remain. I have tried reverting back to Form Builder 2.00 and 2.01 again without success - I don't want to uninstall and reinstall Form Builder as I will lose all the templates and stuff I have worked on for hours.

Sorry to keep flagging these issues!

PS - you still need to update all the .tpl files in `Form Builder > templates > template sets` to change all instances of `include` to `ft_include` e.g. tab_templates.tpl, tab_resources.tpl (8 files in total).

**Comment by benkeen** [comment]
Hmmm.. Form Backup + Form Builder are quite separate so I doubt those issues are related. I'm starting to wonder if there's something deeper going on with your setup which is manifesting these different issues. I don't suppose you have an installation set up that I could get access to to debug? 

And no no, thanks for all the bug reports! Most of them are genuine issues so I'm very appreciative :) I'll fix up the include->ft_include issues in a new release today.

**Comment by tomheaps** [comment]
Thanks so much @benkeen really appreciate the support. I know Form Tools could be perfect for me but it feels like one step forward and two back at the moment and fear losing all my work if I have to reinstall - serves me right for using an alpha version of your script I suppose!

I will email you my site address and login details - there is no real data on the site at the moment so feel free to go poking around everywhere!

Would be good for your views on the minimalist theme I am developing as well.

**Comment by benkeen** [comment]
Sounds good! Btw, I'm moving all discussion of the Form Backup to here: 
https://github.com/formtools/module-form_backup/issues/2

Let's chat there. I'll keep adding + responding to your other comments.
