### ISSUE TITLE
More issues - Field Validation/Form Back Up and Assigning View to Client in Private Form

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#120]
Hi @benkeen. I have another few bugs for you I'm afraid.

**1. Field Validation and Form Back Up** - I have intermittently had issues with all my field validation settings being wiped and I have now pinpointed the problem to Form Backup. You can recreate this issue by doing the following:
a) make a backup copy of a form that has validation set on some of its fields
b) delete the copied form (orphan clean-up reveals that the validation entries that were associated with this deleted from have not been removed from ft_field_validation table
c) delete these orphaned records through Orphan Clean-up
d) check the ft_field_validation table in your database - the orphaned records have been deleted but also, all validation entries associated with the ORIGINAL form (that you copied) have also been deleted
e) validation entries associated with multiple non-related OTHER FORMS also get deleted!

A similar problem occurs when you delete any FIELD from a form that had a validation associated with it - the record of the validation in ft_field_validation does not get removed after you delete the form and then if you run Orphan Clean-up, it can delete random validation records for other non-related forms.

**2. If you have a form with access set to private (specific clients have access)** I can add selected clients to this form however when I then go to the views tab and I try to assign a client (from the list of available clients dictated by my original private access settings) to a view by adding them to selected clients, in this view, my selection does not save.

**Comment by benkeen** [comment]
Hey @tomheaps, good grief that module really has been causing trouble. I'm so sorry. 

I've fixed the second issue (just some code that wasn't properly ported to PDO). I'll release a new version of the Core tonight. 

I've listed the Form Backup bug here: https://github.com/formtools/module-form_backup/issues/3 and I'll let you know how it goes. 

Sorry for all the problems. That module was in worse shape than I thought.
