### ISSUE TITLE
submitting a form from mobile  it does not work

### ISSUE THREAD

**Issue by ridharezzag** [formtools/core#125]
Hello 
in form tools V 2.5 when submitting a form from mobile  it does not work after click continue it just refresh the page, im having all kind of field in the form like uploading files, but the form works fine from computer 
Add: i tested the new version 3.0 and it has the same issue wont accept any form posted from phone browser if the form contains uploading fields, other than that form works fine

**Comment by ridharezzag** [comment]
Add: i tested the new version 3.0 and it has the same issue wont accept any form posted from phone browser if the form contains uploading fields, other than that form works fine

**Comment by ridharezzag** [comment]
Hello never mind i fixed this by raising the server resource in Cpanel MultiPHP INI Editor 
 raised the 
max_input_time to 120
memory_limit 1000
post_max_size 800mb
upload_max_filesize 900mb

-----------------
these values are not exactly what you should do but it depends on the size of the files uploaded in your form so thats why i have them in high values 
hope this will help who ever face this issue

**Comment by benkeen** [comment]
Thanks for following up with the fix, @ridharezzag!
