### ISSUE TITLE
"Notice: undefined index ..." while adding external form

### ISSUE THREAD

**Issue by jsnwht** [formtools/core#128]
Occurs at ".../formtools/admin/forms/add/step2.php?submission_type=direct"

Appears at the top of the page:

> Notice: Undefined index: form_name in /public_html/formtools/global/code/Forms.class.php on line 372
> 
> Notice: Undefined index: form_url in /public_html/formtools/global/code/Forms.class.php on line 373
> 
> Notice: Undefined index: is_multi_page_form in /public_html/formtools/global/code/Forms.class.php on line 374
> 
> Notice: Undefined index: multi_page_form_urls in /public_html/formtools/global/code/Forms.class.php on line 375
> 
> Notice: Undefined index: redirect_url in /public_html/formtools/global/code/Forms.class.php on line 376
> 
> Notice: Undefined index: access_type in /public_html/formtools/global/code/Forms.class.php on line 377
> 
> Notice: Undefined index: client_info in /public_html/formtools/global/code/Forms.class.php on line 378

Never happened before. The only thing done differently prior to this was the act of deleting an incomplete form (also external)

**Comment by jsnwht** [comment]
"step3.php" then throws out this
> Notice: Undefined index: form_url in /home/zibaho5/public_html/formtools/admin/forms/add/step3.php on line 43

**Comment by jsnwht** [comment]
After attempting to add the form multiple times, it seems to have fixed itself after the third attempt. I can 
 now add forms as usual

**Comment by benkeen** [comment]
Hmm, curious! This may well be a bug, but I couldn't reproduce it. I'll leave it open for a while in case it pops up again. 

Thanks for logging it.

**Comment by johnbleck3** [comment]
I had similar issues on a form_builder form.
I changed the show all fields to 10 per page and updated, then when I tried to update the fields, I got these errors.
Changed it back to all fields and hit update and it worked without a problem.

Notice: Undefined index: system_fields in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Warning: in_array() expects parameter 2 to be array, null given in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Notice: Undefined index: system_fields in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Warning: in_array() expects parameter 2 to be array, null given in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Notice: Undefined index: system_fields in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Warning: in_array() expects parameter 2 to be array, null given in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

Notice: Undefined index: system_fields in /var/www/forms.buffalonews.com/global/code/Forms.class.php on line 1776

![1-24-2018 7-04-35 pm](https://user-images.githubusercontent.com/12632568/35363777-c1b68cb8-0139-11e8-97ad-4b1820679deb.png)

**Comment by benkeen** [comment]
Ah, I think this is a separate issue than the original one - just manifests the same problem. Thanks for logging it, I'll take a look at it soon.

**Comment by benkeen** [comment]
Actually - simple fix, I just updated `master` - it'll be in the next release. I'll leave this issue open regarding the original problem.
