### ISSUE TITLE
Can't delete form email field configurations

### ISSUE THREAD

**Issue by tomheaps** [formtools/core#131]
Hi @benkeen, have discovered another bug. Under the EMAILS tab for a particular form, I can successfully configure an email field from the form however if I then want to delete that particular email field configuration I get a 404 - page not found error ([url]/admin/forms/edit/edit.php?page=email_settings&delete_form_email_id=11)  when clicking on the cross to delete the configuration (see screenshot below) and it is not removed.

![image](https://user-images.githubusercontent.com/13905479/34734755-df9b448e-f564-11e7-82af-6fa1cc4b828b.png)

**Comment by benkeen** [comment]
Thanks Tom! I've just patched it and updated master - if it's okay, I won't do another new release for a couple of days, I'd like to get the last of the API work done and that may require a few more Core changes.

**Comment by tomheaps** [comment]
That's fine, no rush. Thanks for sorting!
