### ISSUE TITLE
File type File: Permitted file types blank but setting_value has 2 values.

### ISSUE THREAD

**Issue by johnbleck3** [formtools/core#135]
When only one file type, it shows when editing the field. When I put in more than one file type, the field is blank. see below example.

![1-24-2018 8-39-01 pm](https://user-images.githubusercontent.com/12632568/35366449-9f5c92bc-0147-11e8-8332-b7bac27b2830.png)

**Comment by benkeen** [comment]
Nice, thanks @johnbleck3!

**Comment by benkeen** [comment]
Neat bug. This was actually present in FT2 (!). Fixed in the next version.
