### ISSUE TITLE
Minor reminder: !! at end of page names in client menu pulldowns

### ISSUE THREAD

**Issue by johnbleck3** [formtools/core#138]
Whenever a page name is created in the pages module it's adding "!!" at the end of the name of the page for the menu pulldowns. I'm assuming it was put there to test and just hasn't been removed. Which is why it's more of a reminder - I wouldn't call it a "bug" - just wanted to make sure you knew it was still there.
![1-26-2018 4-47-47 pm](https://user-images.githubusercontent.com/12632568/35462430-e09d74c6-02b9-11e8-8b3d-0351b6a1de3c.png)

**Comment by benkeen** [comment]
Gah! Oops.

**Comment by benkeen** [comment]
Thanks again @johnbleck3! I'll patch the Pages module today - I've created an issue there. Will close this one.
