### ISSUE TITLE
Current release will not install

### ISSUE THREAD

**Issue by daimonbok1** [formtools/core#143]
Uploaded tonight, tried installing current version available on 2/6/18 it just sites there with a white screen.  and will not install.  Cache directory is 777 as direction stated.

Tried Opera and Chrome browsers without any luck.

Any help would be appreciated.

**Comment by nelsondcosta23** [comment]
can share a screenshot?

**Comment by daimonbok1** [comment]
![screenshot](https://user-images.githubusercontent.com/22897815/35920629-5da26582-0be6-11e8-8ae9-13cefccefdfc.png)
Nothing there?
