### ISSUE TITLE
Blank page on page1 of install 

### ISSUE THREAD

**Issue by daimonbok1** [formtools/core#144]
![screenshot](https://user-images.githubusercontent.com/22897815/35929380-5f9ae97e-0bfd-11e8-9c7a-823612b352eb.png)

**Comment by benkeen** [comment]
Hi @daimonbok1, no idea why your previous ticket closed either. I can't reproduce the problem myself. Couple of things:
- what version of PHP are you running?
- could you check your PHP error logs to see if there are any errors that may give us a clue how to debug this?

**Comment by daimonbok1** [comment]
Thanks for getting back so quick....
I use dreamhost first....
running php 7.1 fastcgi. can change to:

5.6cgi, 5.6fastcgi, 7.0cgi, 7.0fastcgi,7.1cgi, 7.2cgi, and last one they have is 7.2fastcgi... I don't see anyway to get to the error logs...

**Comment by benkeen** [comment]
Ah nice! Dreamhost have some pretty accessible logs and I have an account too. I'll check it out tonight.

Here's how to get to the logs by SFTP:
https://help.dreamhost.com/hc/en-us/articles/216512197-Viewing-your-error-log-via-SFTP

**Comment by benkeen** [comment]
Drat, I just uploaded it to my own 7.1 fastCGI env on Dreamhost and everything seems fine. Could you double-check all files were properly uploaded to the server?

**Comment by daimonbok1** [comment]
I'll re-download and try again.

**Comment by daimonbok1** [comment]
Installed the beta version and it went great.

Thanks for your help....

**Comment by benkeen** [comment]
Ah excellent, thanks! By the way, FT 3.1 is going to be all about improving the installation + upgrade process and part of that will great reducing the size of the script, so there will be far fewer files to upload to your server (less to go wrong!). I'll make a post about that in a few weeks on the main site. :)
