### ISSUE TITLE
Form Tools Download Page Doesn't Link to Current Version

### ISSUE THREAD

**Issue by jlkane** [formtools/core#149]
The Form Tools Download page (https://formtools.org/download/) nominally provides a handy link to an installation package for both the V3 Beta and the stable V2 release.  But the download button for Form Tools 2 erroneously links to the V3 beta package, too!

(It would seem that using the Custom Build button would provide an easy work-around ...but today that process just dumps your request into a queue that never seems to get acted upon.)

**Comment by benkeen** [comment]
Ack! I'll fix the links right now; I know the cause. 

I'll take a look at the Custom Build script too. Hmm.

**Comment by jlkane** [comment]
Thanks so much.  I'm grateful for your tolerance for picky stuff like this!

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by benkeen** [comment]
haha gosh not picky at all - mixing up the download link for FT2 was a whopper. It's fixed now, but I'm still investigating the Custom Build issue.

**Comment by jlkane** [comment]
Thanks again, Ben!

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by benkeen** [comment]
np! The custom build script is back online too, but I'll be making a couple of tweaks to it later this week. The translations are no longer required for FT3+ (they'll all included by default) so the script will now disable them is not pertinent.
