### ISSUE TITLE
Modules: 403 Error

### ISSUE THREAD

**Issue by jlkane** [formtools/core#150]
I completed a new installation of Form Tools 2 (Core=2.2.5), and all seemed fine ...until I tried to access Modules from the main menu.  That click yielded a 403 error.

The modules directory was present, all of its files were there, and the permissions seemed appropriate.  I deleted the modules directory and re-uploaded it.  Still no love.

Any suggestions?

Thanks in advance for your help,
Jim

**Comment by benkeen** [comment]
I heard the same problem reported a few months back but was never able to reproduce it. Which modules (any?) are in your installation?

**Comment by jlkane** [comment]
Benjamin Keen wrote:
> 
> Which modules (any?) are in your installation?

Just the modules that are included in your default installation package.

Thanks in advance for your help,

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by jlkane** [comment]
PS
If I should simply clean house and reinstall FT, just say the word.

**Comment by benkeen** [comment]
To be honest I'm not sure what to suggest, a 403 permissions denied error is rather peculiar if the files are there and they have the right permissions. There was never a problem with that page on FT2.x back in the day (3 / 4 years ago) so it's possible there's some sort of incompatibility with more modern PHP versions... 

No chance I could get temporary access to your env so I could debug this directly?

**Comment by jlkane** [comment]
Benjamin Keen wrote:
> 
> No chance I could get temporary access to your env so I could debug this directly?

That would be awesome!  I'll send credentials to you directly via email.

Thanks in advance for your help,

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by benkeen** [comment]
Thanks Jim! For anyone else that runs into this, in this case there was a setting on the server's `.htaccess` file that was redirecting all .php files within any folder called "modules" to display a 403 error.

**Comment by jlkane** [comment]
Thank you SO much for discovering the source of the problem, Ben.  That line is part of the .htaccess file distributed with the CMS system I'm using:  CMS Made Simple.  It looks as if it's intended to keep unauthorized visitors out of TinyMCE and the responsive filemanager modules, and it's simply guilty of overreach here.

VERY much obliged to you for your willingness to investigate and resolve this problem,
Jim
