### ISSUE TITLE
Upgrade of 2.2.6 modules

### ISSUE THREAD

**Issue by uprjfc** [formtools/core#153]
I hope I have raised this in the right place.

I have been happily using 2.2.6 for a while so have not needed to upgrade recently.

I have tried to upgrade the modules to the latest versions in preparation for v3.

However after uploading the files the module screen does not recognise the new files and does not show the upgrade link against the modules upgraded after refreshing the list.

I am not sure what versions I should be upgrading to is it the 2.*.* or 1.*.* versions?
Also is this necessary before upgrading to v3?

I have not used Github before so I apologise if this should be raised elsewhere.

**Comment by benkeen** [comment]
Hi @uprjfc, you found the right place! 

This is actually a good question - I'm going to need to make a few changes to the upgrade script. When you select an older version of the core it should be acting slightly differently: it should be selecting different versions of the modules - not the latest + greatest that are only compatible with Form Tools 3.

As a workaround for now, just upgrade the modules to the latest FT2-compatible versions, use the Custom Build script:
https://formtools.org/build/

On that page select the Form Tools version you want (2.2.6) and that will automatically pre-select the latest version of each module that's compatible. Then select the modules you have installed and generate the download file. Lastly, extract the zip file and use the contents of the /modules folder. 

Hope this helps, and I appreciate letting me know!

**Comment by benkeen** [comment]
This was fixed a while back. Closing.
