### ISSUE TITLE
get started with API

### ISSUE THREAD

**Issue by ttkrpink** [formtools/core#155]
FT3.0, API 2.0.

I am stuck with API 2.0 tutorial, can someone help me please?

API 2.0 tutorial asks me to : "then add the following PHP to the very top of your page ":

`<?php 
require_once "path/to/form_tools/global/api/API.class.php";
$api = new FormTools\API();
$fields = $api->initFormPage("", "test");
$params = array(
	"submit_button" => "submit_button_name_attribute",
	"next_page" => "thanks.php",
	"form_data" => $_POST,
	"file_data" => $_FILES,
	"finalize" => true,
);
$api->processFormSubmission($params);
?>
`

Well, FT3.0 generate the page like the following:

`<?php
/**
 * This file was created by the Form Tools Form Builder module.
 */
require_once "/Users/chaoyou/Sites/formtools/global/library.php";
use FormTools\Core;
Core::init(array("auto_logout" => false));
$root_dir = Core::getRootDir();
$published_form_id = 5;
$filename = "newForm.php";
require_once "$root_dir/modules/form_builder/form.php";?>
`

It does not make sense to add the API code in the generated page. Can someone give me a hint?

**Comment by benkeen** [comment]
Hey @ttkrpink, sure no problem! The API tutorial is for integrating your own forms, i.e. forms that you yourself have manually created - not forms generated with the form builder. The form builder is totally self contained and you don't need to worry about how it's integrated. You're quite right, it wouldn't make any sense to add them in the generate page there. :)

This page explains the three different types of form:
https://docs.formtools.org/userdoc/form_management/form_types/

The API is used for the "external forms" type, for more advanced integrations. Generally I'd suggest just using the form builder - or simpler external forms using the POST method. 

Let me know if you have any other questions!

**Comment by Patdaman1** [comment]
I thought i had to do this to pull the info into the next form. i built 3 forms so far, the first is Contact Contains items that people only have 1 of (Fname, Lname, DOB, ext..) the other 2 are addresses and phone numbers. I did this to normalize data but i need to automaticly bring in the contact ID to the other 2 forms I was thinking I would build one html page saved as php file and use the 
<?php include 
	"includes/header.php" ;
?>
for the 3 forms and my standard heading am i way off base here? is there somewhere i can watch videos or read up on this stuff so im not wasting the forums time?
Pat
