### ISSUE TITLE
Formbuilder: Fatal error: require_once()...ootormtools/global/library.php' (include_path='.;C:\php\pear') in

### ISSUE THREAD

**Issue by KoreTeknology** [formtools/core#156]
Hi :)
i got troubles by publishing a form with formbuilder, here is the message:
i am using the v3 beta ! on localhost for testing purpose

```
Warning: require_once(C:\Users\...\Desktop\URIEL\USBWebserver v8.6 ootormtools/global/library.php): failed to open stream: Invalid argument in C:\Users\...\Desktop\URIEL\USBWebserver v8.6\root\formtools\modules\form_builder\published\test123.php on line 6

Fatal error: require_once(): Failed opening required 'C:\Users\...\Desktop\URIEL\USBWebserver v8.6 ootormtools/global/library.php' (include_path='.;C:\php\pear') in C:\Users\...\Desktop\URIEL\USBWebserver v8.6\root\formtools\modules\form_builder\published\test123.php on line 6 
```

thanks for your help, ;)
uriel

**Comment by benkeen** [comment]
Hey @KoreTeknology! Does this path look right? 
`C:\Users\...\Desktop\URIEL\USBWebserver v8.6 ootormtools/global/library.php` ? That's where the file is trying to include the file. The "ootormtools" bit looks especially fishy. 

If you're able to log in and out of Form Tools and everything seems okay there, your `$g_root_dir` setting your `/global/config.php` is probably correct. Try re-publishing your form through the Form Builder at a new location and see if that solves the problem.

**Comment by KoreTeknology** [comment]
in config.php, everything seems ok:
`$g_root_url = "http://localhost:8080/formtools";
$g_root_dir = "C:\\Users\\..\\Desktop\\URIEL\\USBWebserver v8.6\\root\\formtools";`

i dont know why it generates "ootormtools" ??
i will try what you said about re-publishing at a new location ;)
thx
