### ISSUE TITLE
Form always visible after changing offline  and access restriction

### ISSUE THREAD

**Issue by Rathilesh** [formtools/core#157]
i created a form using formtools ( 3.0.0-beta-20180224 ) then changes form type to offline and also changed permission to specific client , but form is always showing, i dont know its a bug or my mistake

**Comment by benkeen** [comment]
Hi @Rathilesh,

I'm glad you brought this up, that's a confusing setting and needs to be updated. It's kind of vestigial from older versions of Form Tools when the application only accepted External Forms. 

Here's how it's supposed to work:
- It has no effect for administrator accounts. Admin's can still see and access the form, edit the submission data etc.
- If set to offline, *client* accounts will no longer see the form appear in their user interface.
- If the form is an External form, Form Tools will no longer accept data posted to it for that form ID.

When you say it's always showing, do you mean for the administrator? If so, that's normal.

**Comment by Rathilesh** [comment]
OK , Understood , Thanks for your replay

**Comment by benkeen** [comment]
No problem! Happy to help.
