### ISSUE TITLE
Installation fails immediately without php mbstring

### ISSUE THREAD

**Issue by tstrock** [formtools/core#158]
The installation index.php fails immediately if the server php installation does not include the mbstring extension since a mb_split function is called in Sessions exists check.  mbstring is a non-default extension according to php.net.  I encountered this problem on a 1and1 (windows) server initially and then also on a local Debian linux server with the default php 7 setup.   After installing this extension, the install works great.  An earlier check that the server has the correct php version and this extension is suggested.

**Comment by benkeen** [comment]
Thanks @tstrock! I'll log this as a bug and take a look.

**Comment by benkeen** [comment]
Ah, I see. The polyfill file doesn't include `mb_split` along with the other mb_* functions:
https://github.com/formtools/core/blob/master/global/code/polyfills.php

I'll add in a polyfill and test it out without that extension to confirm it's all working as expected. Thanks!
