### ISSUE TITLE
Undefined index - Form field type:checkboxes option list - submissions from another form

### ISSUE THREAD

**Issue by johnbleck3** [formtools/core#159]
I have a form field using an option list from another form field and this error shows up even though it does still display the submission field.
![image](https://user-images.githubusercontent.com/12632568/36817366-e63fb2ae-1cae-11e8-8bb3-0ba202d6f253.png)

**Comment by johnbleck3** [comment]
![image](https://user-images.githubusercontent.com/12632568/36817434-2be1101e-1caf-11e8-9188-6965b5dca5d5.png)

**Comment by benkeen** [comment]
Thanks @johnbleck3, yeah this is a bug. Thanks for letting me know!

**Comment by benkeen** [comment]
[N.B. investigate why the core errorReporting setting isn't suppressing this notice!]

**Comment by johnbleck3** [comment]
I cheated and added $g_debug = true; to the config file. :-)

**Comment by benkeen** [comment]
haha!

**Comment by benkeen** [comment]
I'll release a new beta tonight containing the fix for this.
