### ISSUE TITLE
Is there a updateForm API

### ISSUE THREAD

**Issue by ttkrpink** [formtools/core#160]
Through API, an user can submit a new form. Is there an API that an developer can use to update submission data or delete a submission entry?

Thanks,

ttk

**Comment by benkeen** [comment]
Hi @ttkrpink, you can use the `processFormSubmission()` method with the `may_update_finalized_submissions` setting set to true. That will allow it to update a particular submission and overwrite specific parts of the submission data. See here + the associated doc links within the page:
https://docs.formtools.org/api/v2/process_form_submission/

For deleting, you can just use the Core function itself:
`FormTools\Core::deleteSubmission($form_id, $view_id, $submission_id);`
https://github.com/formtools/core/blob/master/global/code/Submissions.class.php#L367

But both of these methods should really be added to the API. I'll include this in a future update, thanks!

**Comment by ttkrpink** [comment]
Tutorial indicates that "may_update_finalized_submissions" default is true. So my follow-up question is: how to use processFormSubmission to pass submission_id in to the function. Create an hidden field in the form, and the input name is "submission_id"?

For the external form, should I leave the deleteSubmission view_id as blank?

Thanks

ttk
