### ISSUE TITLE
Emails without subject line when using Swift Mailer

### ISSUE THREAD

**Issue by mcmg87** [formtools/core#161]
Hi, I'm using FT 3.0.0-beta-20180224 with Swift Mailer 2.0.4.
The only thing not working is that Emails (upon submission of a form) are sent without subject line when using Swift Mailer. When I disable Swift Mailer the subject line is present.
Any idea on how to fix this?
thanks

**Comment by benkeen** [comment]
Hmm, sounds like a bug. I'm actually away this weekend but I'll try to get to this tomorrow night. Should be a quick fix if it's a bug.

**Comment by benkeen** [comment]
Curious! I haven't been able to reproduce this. I tried with a Form Builder form, External form and through the test email template functionality. Couple of questions:
- does your subject line contain placeholders? Any special characters or anything? 
- Where does it fail to send? i.e. what event is it configured to be sent on (edit submission, new submission, delete submission)?

**Comment by ghalpha** [comment]
I am seeing the same thing running 3.0.0-beta-20180312. I have manually entered a subject and tried both placeholders neither pass. However when doing a test weather HTML or TEXT both tests pass the subject without an issue. Even stranger when sending a form as a test it shows correctly there as well.

**Comment by benkeen** [comment]
Hi @ghalpha, thanks for your help! I don't quite follow, though: where is it failing to include the subject, exactly? You say the email gets sent when you submit a form, and when you use the test email option?

**Comment by ghalpha** [comment]
@benkeen That is correct. The issue only occurs when I generate a message ethier manually or automatically. The rest of the form is compiled and emailed 100% correct. I spent some time digging through the code and was trying to track down the step when the mail request is processed and how it compiles the message structure. No such luck in finding what created a bug in my specific installation.

**Comment by benkeen** [comment]
Hey @ghalpha, sorry - one more clarification.

> The issue only occurs when I generate a message ethier manually or automatically. 

When you say "manually" sending an email, do you mean via the optional functionality on the Edit Submission page, where you can choose the email template and send the email from there? And what do you mean by "automatically"?

Sorry if I'm being dense, I just can't quite follow the scenarios in which it's not working. Everything seems to be working fine on my end - but I have no doubt it's an issue, you're not the only one encountering it. :) 

Could you also supply the exact content of the Subject line for your email template (just so I can see).

**Comment by benkeen** [comment]
Breaking news! I can reproduce this consistently when sending the email in a single format: text or HTML. When sending both, I also see the subject line - that's what I've been using. Excellent! I'll investigate + include a patch for this in today's release. Hopefully it'll patch your scenario.

**Comment by benkeen** [comment]
I just updated the Form Tools Core + and the Swift Mailer module. Would you mind updating to confirm the problem is all fixed? It should be good now. Thanks!
https://formtools.org/download/

**Comment by ghalpha** [comment]
@benkeen You nailed it! Just upgraded and its working like a charm. Keep up the awesome work!

**Comment by benkeen** [comment]
Thanks! :D
