### ISSUE TITLE
FormTool behind FrizBox

### ISSUE THREAD

**Issue by Steffen1982** [formtools/core#162]
Hi,
I use FormTools for a simple survey of wedding guests. The installation was very fast.
FormTools runs on a Raspberry3, which is accessed via a Dyndns service and port forwarding.
With the direct IP and DynDns everything works great from the same network. If I'm on another network now, load the page within minutes and without layout. When I examine the page I find my internal IP in the <Script> area. How can I get this off?
![formtools](https://user-images.githubusercontent.com/37086639/36999563-cae9085a-20c0-11e8-8954-66d88f6a02c5.jpg)

**Comment by Steffen1982** [comment]
Hi Ben,
It's working. But if I press the Contiune button the content of the form will be deleted. I can sometimes find parts of the input in the database, but not always. Locally via IP it works.
I currently have the RPI complete without firewall on the Internet. Which ports are required?

**Comment by benkeen** [comment]
Heya - sorry @Steffen1982, I missed your question here. Any luck getting it sorted? 

Port-wise I'm not really sure... I know the DB connection defaults to 3306, but that's the extent of my knowledge. It's customizable though, via your `/global/config.php` file should you need to tweak it.
