### ISSUE TITLE
Error: Invalid JSON when adding a new form (FT3 beta)

### ISSUE THREAD

**Issue by elembe** [formtools/core#166]
When I try to add a new form, on the step before the last one (Field types) when I resolve all issues (action needed) and cklick "next step", I get the following msg:

> Error: Invalid JSON:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: parameter was not defined' in /home/content/61/4901761/html/FORMTOOLS/global/code/Database.class.php:117 Stack trace: #0 /home/content/61/4901761/html/FORMTOOLS/global/code/Database.class.php(117): PDOStatement->bindValue('original_form_i...', '1', 2) #1 /home/content/61/4901761/html/FORMTOOLS/global/code/Database.class.php(122): FormTools\Database->bind('original_form_i...', '1') #2 /home/content/61/4901761/html/FORMTOOLS/global/code/OptionLists.class.php(716): FormTools\Database->bindAll(Array) #3 /home/content/61/4901761/html/FORMTOOLS/global/code/Forms.class.php(1108): FormTools\OptionLists::createUniqueOptionList('1', Array) #4 /home/content/61/4901761/html/FORMTOOLS/global/code/actions.php(226): FormTools\Forms::setFormFieldTypes('1', Array) #5 {main} thrown in /home/content/61/4901761/html/FORMTOOLS/global/code/Database.class.php on line 117

Maybe something I messed up. I wanted to update to FT3, but I've seen a recomendation first to update to the latest FT2 modules. I didn't figure out quite well how to do that, so I downloaded the whole FT2 instalation file and I overwrited my databese. (Yes, of course I didn't backed it up :-) ). Then I updated to the FT3 properly, but now I cannot make my first form (to recreate a database).

**Comment by benkeen** [comment]
Hey @elembe, oops, sorry about that! This is just a small bug in the code (incorrect placeholder name). I'm going to fix it now and get a fresh Beta released today. 

And you should be fine with upgrading. I try to insist everyone updates to the latest modules just in case they were running something really ancient so any weird upgrade issues are resolved before moving to the FT3-compatible versions of the modules [a couple of them drop some of the *really* old upgrade code].  But worst-case scenario, if a module isn't working properly you can just uninstall + reinstall it. 

Thanks! :)

**Comment by elembe** [comment]
Thank you. Works fine now!

**Comment by benkeen** [comment]
Good to hear!

**Comment by praveenraj2018** [comment]
Hey,

Faced the same error while publishing the form. Using xamp with php 8.0 and mysql 8.

Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number in C:\xampp\htdocs\formtools\global\code\Database.class.php:126 Stack trace: #0 C:\xampp\htdocs\formtools\global\code\Database.class.php(126): PDOStatement->bindValue('form_id', '6', 2) #1 C:\xampp\htdocs\formtools\global\code\Views.class.php(915): FormTools\Database->bind('form_id', '6') #2 C:\xampp\htdocs\formtools\modules\form_builder\preview.php(79): FormTools\Views::getFormViews('6') #3 {main} thrown in C:\xampp\htdocs\formtools\global\code\Database.class.php on line 126

any solution?
