### ISSUE TITLE
FT3 Beta: Changed ip address in global config but admin console is using old address

### ISSUE THREAD

**Issue by nickbrandwood** [formtools/core#168]
1. Changed the ip address of the virtual machine (from NAT to bridged)
 --- 192.168.39.129 to 10.3.3.78
2. Changed the /global/config.php file to reflect changes.
3. Checked the admin console, but all links still point to old address
4. Restarted Apache, but no change.

If you look at the attached HTML, you will see that the links are correct for the first 109 lines.
from line 110 onlwards, the Div containing the menu_items class has links to the old ip address.
At the end of this section, the new IP address is used again.

WORKAROUND: Fix the IP address in the address bar.

[Forms.htm.txt](https://github.com/formtools/core/files/1825526/Forms.htm.txt)

**Comment by nickbrandwood** [comment]
checked again this morning and the addresses are now correct, probably a caching problem.

**Comment by benkeen** [comment]
Yeah, sounds that way. Updating the content of `config.php` should be reflected immediately on the next page refresh. Glad you got it fixed!
