### ISSUE TITLE
Not able to publish form

### ISSUE THREAD

**Issue by chakthy** [formtools/core#171]
Once I select the publish tab, I'm able to see the form on a separate window. The save buttons is there but it doesn't do anything. The publish button opens a new window to set a name for the form, the permissions and URL are correct but it does not create the file when the button is pressed. The window remains open and no message is displayed.

**Comment by benkeen** [comment]
Hi @chakthy, that's peculiar - there should be error handling in place in case the file can't be created for any reason. Have you created any forms in the past through the same mechanism or has it never worked for you? Also, are you familiar with chrome/firefox dev tools? I'm curious to know what the response is from the XHR request when you try generating the file.

**Comment by chakthy** [comment]
It hasn't work for me. I tried to look for the errors using Chrome but it is not showing any. It looks like the publish button is not active so it does not take any action. I pressed the "Test Folder Permissions" and the "Confirm Folder-URL Match" inside the publish Form pop up window and they show that everything is correct. But pressing the Publish button does not do anything.

**Comment by benkeen** [comment]
Hey @chakthy, sorry for not responding sooner - was out of town for a few days. 

I don't suppose I could get access to your installation to debug this? I can't think of anything offhand that would be causing it... If so, email me at ben.keen@gmail.com.

**Comment by chakthy** [comment]
Thanks for your help, but sadly I'm unable to grant you access because this will require corp approval. I'm attaching the picture of what I get from the developer console when using Chrome. It doesn't send an error, it seems like if the button was not active to take an action.  Not sure what else can I use to flag errors.

![screen shot 2018-04-11 at 2 49 00 pm](https://user-images.githubusercontent.com/37351467/38642538-95249290-3d97-11e8-8df8-bee0e974da35.png)

![screen shot 2018-04-11 at 2 20 05 pm](https://user-images.githubusercontent.com/37351467/38641156-8fb11134-3d93-11e8-93ca-d4d6860ab5b5.png)

**Comment by paulg10me** [comment]
I am having the same issue. When I first began testing, I was able to publish forms, so it has worked for me but seems to no longer respond to the button. The folder permissions and url validation tests are good. I also tried entering the form name with the .php extension, which gives an error. Is there any specific information I can give that would help to solve this?

**Comment by paulg10me** [comment]
I have run the System check module and Formtools core fails with the following files shown as missing -
Form Tools Core: FAIL. Missing files
- README.md
- composer.json

Not sure if this might be affecting the form builder module?

**Comment by benkeen** [comment]
Hey guys - sorry for not responding sooner, I've been mopping up a few other issues which has kept me busy. Mind if we move this conversation to the Form Builder repo here? 
https://github.com/formtools/module-form_builder/issues/18

It's clearly a bug, I just haven't managed to reproduce it yet. I'll add some comments on that thread.

**Comment by benkeen** [comment]
Closing this issue on this repo. We'll continue in that other issue.
