### ISSUE TITLE
Add form header line [example attached]

### ISSUE THREAD

**Issue by andreassandhi** [formtools/core#175]
Hello,

How to add form header to customize below title, like on attached.

Thanks a lot
![transfer-form](https://user-images.githubusercontent.com/12729046/38243096-ac2fde32-3760-11e8-8e38-9ac29c1122b9.jpg)

**Comment by benkeen** [comment]
Hi @andreassandhi, sorry for not getting back to you sooner - I've been out of town! 

Just so I'm clear, you're trying to customize a Form Builder template so you can output a form page like the screenshot you attached? Is each and every field in the grid a particular field in your form?
