### ISSUE TITLE
[issue] - Email from "field"

### ISSUE THREAD

**Issue by neijek** [formtools/core#176]
The issue is this, with the latest beta version as of today. I get duplicated text within the "from" field in emails.

To better explain:

Form as a field set as "email". Field type is "textbox" set as "medium <-256 chars" string.

in the "email section" of the form i set "Configure from email fields" as the above "email" with n/a for first name, last name.

in my emails template I set as recipient "administrator" (my email address) 

subject line i set to {$ANSWER_oggetto} (a field in my form)

and from i set to the only option witch is  "[from email field]: Email" 

doing so any test i run gives me this in the email source code:

```
To: xxxx@xxxxxxxxxxx.com
Subject: test
X-PHP-Script: xxxxxxxxxx.com/formtools/global/code/actions.php for 93.xxx.xxx.162
X-PHP-Originating-Script: 503:Emails.class.php
MIME-Version: 1.0
**From: testemail@testemail.com,  , testemail@testemail.com**
Content-type: text/html; charset=UTF-8
Message-Id: <E1f3etZ-0003Xb-NX@server.xxxxxxxxxxxxxxxxxx.com>
Date: Wed, 04 Apr 2018 11:39:57 +0200
```
 
If i set the "from" field as none(not recomended) it shows my server as the from, and it only shows it once. but any time i set the from as an email field as explained above, it will dupllicated it as above as well as cause that wierd empty space.. 
Help Smile

**Comment by benkeen** [comment]
Hey @neijek, sorry about that! This is a bug - I was just able to reproduce it. It only occurs with the non-Swift Mailer option. I'll see if I can patch this tonight.

**Comment by neijek** [comment]
Looks good 👍 thank's for the quick turn around.
