### ISSUE TITLE
After 3.0.0 upgrade PHP fatal error when editing a form submission

### ISSUE THREAD

**Issue by paul4ttuhsc** [formtools/core#186]
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "eval:{if $contents == ""}   <div class="cf_fi..."  on line 38 "<div class="cf_field_comments">{$comments}</div>"  - Unexpected "/" <-- \n  thrown in /var/www/html/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 38,

**Comment by benkeen** [comment]
Hmm, thanks @paul4ttuhsc. Sounds like maybe there was a problem updating your database record for one of your multi-select fields types (radios, checkboxes, dropdown, multi-select dropdown). I know this is a pain, but would you mind posting the content of the following database cells here? I just want to confirm that's the problem. 

It's in your [prefix]field_types table: the edit_field_smarty_markup column for those four field types, see screenshot: 

![db-cells](https://user-images.githubusercontent.com/512116/39024755-c9dd40c0-43f7-11e8-8cc5-43426b9d132a.png)

**Comment by paul4ttuhsc** [comment]
Ben, the multiselect field is empty. Here are the 4 files:

[smarty_checkboxes.txt](https://github.com/formtools/core/files/1932662/smarty_checkboxes.txt)
[smarty_dropdown.txt](https://github.com/formtools/core/files/1932663/smarty_dropdown.txt)

[smarty_radios.txt](https://github.com/formtools/core/files/1932664/smarty_radios.txt)

**Comment by benkeen** [comment]
Hey @paul4ttuhsc, yeah there was a problem with upgrading the field types with 3.0.0. I'm releasing 3.0.1 tonight - just upgrade to that when it's available and it should solve your problem. Sorry about that!

**Comment by benkeen** [comment]
I'm going to close this issue so it appears in the version tracking history. After upgrading, do let me know if you run into any problems at all.
