### ISSUE TITLE
FT3: Value from Radio Buttons, Checkboxes Not Being Displayed In Emails

### ISSUE THREAD

**Issue by calvineidt** [formtools/core#189]
After upgrading to FormTools 3, almost everything appears to be working as it should. One thing however that I have noticed is that emails are no longer displaying values from Radio Button or Checkbox fields. The placeholders are all listing correctly, but the values for the questions are displaying as expected, it is the submitted values that are not being displayed. They appear to be stored correctly in the database, but they are not coming through to the emails.

Thanks,

Calvin

**Comment by calvineidt** [comment]
Been digging into this, and so far I have got to a point where in FieldTypes.class.php in the function generateViewableField there is an if block that radio button values are entering, but they have no path out of, so are subsequently being lost.

`if ($field_type_info["view_field_rendering_type"] == "php") {

                list ($class_plus_namespace, $method) = explode("::", $field_type_info["view_field_php_function"]);

                // TODO instantiate the module instead
                if ($field_type_info["view_field_php_function_source"] != "core" && is_numeric($field_type_info["view_field_php_function_source"])) {
                    $module_folder = Modules::getModuleFolderFromModuleId($field_type_info["view_field_php_function_source"]);
                    @include_once("$root_dir/modules/$module_folder/library.php");
                }

                if (class_exists($class_plus_namespace) && method_exists($class_plus_namespace, $method)) {
                    $output = call_user_func($field_type_info["view_field_php_function"], $placeholders);
                }
            }`

I'm still digging through this to try and get to the ultimate root cause.

**Comment by calvineidt** [comment]
After coming up with a very hacky temporary solution in the code that I really wasn't happy with at all, I managed to track down the root of the issue to the `view_field_php_function` column in the `{PREFIX}_field_types` table. All of the function references there were to the old FormTools installation, such as `ft_display_field_type_radios`. Now that I have updated these to new format, `FormTools\FieldTypes::displayFieldTypeRadios`, everything appears to be working as expected.

I'll leave this open for now, if only because I thought I followed the upgrade path correctly, and am not sure how these fields did not get updated.

**Comment by pegaspar** [comment]
I have run into the same problem in #181. The 3rd point.

**Comment by benkeen** [comment]
Yeah it seems like there's an issue with the upgrade code - it's failing to update a few of the data types. Which FT2 versions did you upgrade from? I'm going to run some tests now.

**Comment by benkeen** [comment]
Yup, this was a bug - apologies. I have it fixed locally and I'll get 3.0.1 out the door tonight.
