### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by worivas** [formtools/core#190]
The mail arrives with a new username and password but when you want to enter it, it does not recognize it
Very good work Ken, you are a genius

**Comment by worivas** [comment]
I have Formtools 3 installed from scratch if it helps in solving the problem.

**Comment by benkeen** [comment]
Huh, thanks for the heads up... I'll check it out.

**Comment by benkeen** [comment]
Thanks for letting me know, @worivas! Turns out the temporary password was just fine, but the system was failing to recognize it so it would automatically boot you out. This has been fixed in 3.0.1 - I'll release it tonight.
