### ISSUE TITLE
Convert to HTTPS

### ISSUE THREAD

**Issue by mortom91** [formtools/core#194]
Hi all,
I am using ftool v3.0.1. I have recently installed an SSL certificate. The forms on the frontend seem to be fully operation, however the backend pages are not formatted correctly, because they are calling HTTP scripts and stylesheets.

I have changed the URL in ftools/admin/account/ but the issue remains. Is there any way I can reconfigure the backed to refer to the HTTPS:// addresses of the scritps and stylesheets?

Thanks in advance,
mortom91

**Comment by benkeen** [comment]
Hi @mortom91, the main URL is determined by your `$g_root_url` setting in your `/global/config.php` . If you change that to https the bulk of the URLs should immediately update. 

All the best!

**Comment by mortom91** [comment]
Hi @benkeen,
Thank you for your reply, but I still didn't manage to get things working.
Going through phpMyAdmin, the wpgr_options table shows both "siteurl" and "home" with HTTPS. I also tried having a look at the wp-config.php and the wp-settings.php and in FormTools' tables, but I was unable to locate the exact variable you described.

Is it possible that I have to create the variable or am I missing something else?

Thanks in advance,
mortom91

**Comment by benkeen** [comment]
Ah, it sounds like you're looking at a Wordpress database: siteurl and home are fields in a Wordpress table, not Form Tools. As are those wp-config.php and other file. Did you want help on Form Tools or Wordpress?

**Comment by mortom91** [comment]
Hi @benkeen,
Sorry for not being specific enough. I am indeed working on a Wordpress installation of FormTools. The installation was made with the help of Softaculous, which is embedded in my cPanel.

So, what updates should I do to convert my FormTools installation within Wordpress to get it to work with HTTPS?

Thanks,
mortom91

**Comment by benkeen** [comment]
Oh gosh - are you using the (very) old Wordpress plugin for Form Tools? I'm afraid that was dropped many years ago so it's just not compatible any more. I'm awfully sorry - to be honest, I completely forgot about the script.

**Comment by mortom91** [comment]
Hi @benkeen ,
Not sure that's the case, since using Softaculous does not lead to Formtools appearing in the Plugins page on Wordpress admin page. Isn't [this](https://www.softaculous.com/apps/others/Form_Tools) still updated?

Thanks,
mortom91

**Comment by benkeen** [comment]
Ah, that's good! Yes it's just Form Tools itself. I haven't used softaculous myself, but presumably you have access to the files on your server? What you'd going to need to do is track down the location of the Form Tools installation. Usually the URL of your login panel can give you a clue, but if not, contact your hosting provider for the exact location.

Then you'll need to make that change to the file I mentioned: the `config.php` file found in your `[formtools folder]/global/` folder. Sorry I can't be more help... I think it's just a matter of locating that file to make the changes to.

**Comment by mortom91** [comment]
THANK YOU! I finally found where I should be looking at. That small change in config.php solved it all.

Thank you for keeping up with the topic.

Regards,
mortom91

**Comment by benkeen** [comment]
Great to hear! :)
