### ISSUE TITLE
 Upgrade issue 3.0.1

### ISSUE THREAD

**Issue by madir71** [formtools/core#197]
Hai boss... i have a problem. My Form Tools got problem when system upgrade to 3.0.1. 
I use Oh Canada Themes. After Upgrade..my FORM TOOLS menu at left is gone. I can't use setting function,

This menu below
Forms
— Add Form
— Option Lists
Clients
Modules
Themes
Settings
— Main
— Accounts
— Files
— Menus
Your Account
Logout

can fix it?
Thank You

**Comment by benkeen** [comment]
Hi @madir71, sorry to hear that! The menu can disappear sometimes if there's invalid CSS/markup... that's the most likely cause. 

Couple of things to try:
- try a different browser (which are you using, by the way?). I'm curious to know if this was a bug that I didn't spot with a specific browser. 
- empty the content of your `/themes/oh_canada/cache` folder - just leaving the index.html file there. Then refresh.

I'll double check this tonight to make sure I didn't introduce something.

**Comment by madir71** [comment]
boss... still my Main Nav all missing..
Forms
— Add Form
— Option Lists
Clients
Modules
Themes
Settings
— Main
— Accounts
— Files
— Menus
Your Account
Logout

how can i get back again this Main Nav boss...?

**Comment by benkeen** [comment]
Hey @madir71 - did you follow my previous suggestion? What browser are you on?

**Comment by ramojo** [comment]
Replacing the contents of the theme folder works perfectly

**Comment by benkeen** [comment]
Brilliant, glad it got solved @ramojo!
