### ISSUE TITLE
Fatal PHP error in export module after 3.0.1 update

### ISSUE THREAD

**Issue by paul4ttuhsc** [formtools/core#202]
I'm not sure if this is a FormTools issue or an Export Module issue.  After updating to 3.0.1 I now get the following "unknown tag" error when attempting to export using a previous template:

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "eval:{foreach from=$submissions item=submissi..."  on line 4 "<tr><th align="left" valign="middle" colspan="2">R number: {display_field_by_colname col_name="col_1"}</th><th align="left" valign="middle" colspan="2">School: {display_field_by_colname col_name="col_17"}</th><th align="left" valign="middle" colspan="4">Name:    {display_field_by_colname col_name="col_4"}, {display_field_by_colname col_name="col_3"}, {display_field_by_colname col_name="col_5"}</th></tr>" unknown tag "display_field_by_colname" <-- \n  thrown in /var/www/html/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 4

**Comment by paul4ttuhsc** [comment]
I dug into my notes. Turns out this a customization:

[(http://forums.formtools.org/showthread.php?tid=1839)]

I've replied to the original forum post.

**Comment by benkeen** [comment]
Ahhh, that explains it. We may as well talk here - I've archived the forums now. 

Let me look at it this weekend and see what I can come up with. I'd imagine it's just a question of updating it for FT3. Keep you posted!
