### ISSUE TITLE
Views: Client Map Filter not working with extended client fields

### ISSUE THREAD

**Issue by dande63** [formtools/core#204]
Using: Form Tools 3.0 beta
Module: Extended Client Fields 2.0.3
Client Map Filter: Sponsor ID equals Sponsor ID - Also tried: Sponsor ID like Sponsor ID

Issue:

I created a custom field through the Extended Client Fields module and labeled it "Sponsor ID" and then under "Forms > (Form Name - Edit) > Views > (View Name - Edit) > Filters > Client Map Filters" I configured a form field (Labeled "Sponsor ID" - form field/FT column name: sponsorid) to equal the custom client field (Sponsor ID - Displays in Options dropdown list). Form is set for public access.  Created 3 client accounts and added a unique value to the extended client field (Sponsor ID) under "Clients (Client Name)" for each of the clients. On the form, I created a "sponsorid" field which is a column name in FT. I added a value to the sponsorid field for each test submission (Different value for each client). The values are unique and do not use the other profile fields such as name, company, etc. I did some test submissions for each client, logged into each individual account, and submissions do not show up under the form. I switched the Client Map Filter operator to "Like" instead of "Equals" and then all of the submissions show up for each of the clients rather than the submissions that contain the unique Sponsor ID which is supposed to enable each client to view only the submissions where the unique form value (Sponsor ID) equals the value of their extended client fields (Sponsor ID)

We had this same problem with an earlier version of FT and you created a patch for it which worked perfectly.

**Comment by benkeen** [comment]
Hi @dande63, thanks for letting me know! I did a little digging tonight and I did notice a problem that would prevent the feature from working. I've patched the issue locally and I'll release a new version of the module tomorrow night.
https://github.com/formtools/module-extended_client_fields/issues/6

One question though, what version of Form Tools 3 are you running? If it's not 3.0.0 or 3.0.1 I would urge you to upgrade off the beta first - there were numerous fixes made for the final 3.0 release that may cause additional problems.

**Comment by benkeen** [comment]
Update: I actually managed to release 2.0.4 of the Extended Client Fields module tonight that includes a patch. Mind testing it out when you get a moment?

**Comment by dande63** [comment]
Hello Ben,

I upgraded the extended client fields module and performed some tests. Everything appears to be working now. Thank you!

I'm still using the beta 3.0.0 version and had every intention to upgrade to the latest stable version, but I'm afraid I gave up yesterday after trying several times to download the upgrade files (zip). It seems there's a lot of traffic on that host. I will keep trying though.

Another minor issue you might consider looking into is the number of submissions that display under the form within each client account. I see the total number of all submissions for a particular form rather than a number of submissions specific to that client when the client filter map is being used. I'm assuming that this is the template code: `{display_num_form_submissions form_id=$form_id}`- Line 97 of index.tpl under directories themes > default > clients.. I'll probably remove it as I'm sure you currently have other priorities but I do love the idea of having that number there (if it's the correct number).

Thank you very much for your help!

**Comment by benkeen** [comment]
No problem, glad to help! And sorry about the upgrade script issue (that thing is the bane of my existence). Try again now - it should be online again now. 

And yeah, I know all about the submission count irregularity... it's actually a real doozy, believe it or not. I logged the following issue to explain the nature of the problem. It's partly UX + partly technical.
https://github.com/formtools/core/issues/118

I'll definitely tackle it at one point, but not quite yet.
