### ISSUE TITLE
If use password 0 cant login

### ISSUE THREAD

**Issue by BlackRule** [formtools/core#206]
Your "installation" scripts didn't tell me that if I create user with "Rules" as login and "0" as password I won't be able to login... I've been trying again and again. I could only login when I ran install again and created "rules" and "a123456" - don't know whether the problem was /also that login started with capital letter

**Comment by benkeen** [comment]
Huh! This has never come up once over the years :) but you're quite right, `0` isn't regarded as a valid password in Form Tools. The PHP code must think it's false or something. I'll take a look at this and try to patch it for 3.0.2.
