### ISSUE TITLE
Server Busy - Can't Download Updates

### ISSUE THREAD

**Issue by Rickcarlson103** [formtools/core#208]
Hi.  For the last few days, I have tried to upgrade from Formtools 2.2.6 to 3.0.1.  When I try to download the zip file, it gives this message:  Oops! The server is too busy to handle your request right now. Please wait and the page will keep trying every 30 seconds to generate your upgrade file. Depending on how busy things are, this may take a few attempts."  It is never able to download and it's been like this for a few days.  Should I just try next week, or late at night or is there something different I should do?  Thanks.

**Comment by benkeen** [comment]
Hmm! Thanks for letting me know @Rickcarlson103, not sure what happened there. Would you mind trying it again? It should work now.

**Comment by john-m-adams** [comment]
Hi,  I've had the same issue now for a bit over an hour.  Is that a typical server load now, or has it hung up?

Thank you!

**Comment by Rickcarlson103** [comment]
I have been able to download the update since my initial issue but it doesn’t instal properly. I tried twice and it left formtools hanging and not functioning at all so I had to revert to the old version. I haven’t had time to try again lately. 

Richard Carlson | Cuelenaere LLP | 200 Nexis Bldg, 450-2nd Ave North, Saskatoon SK S7K 2C3 | www.rickcarlson.com | mail@rickcarlson.com | sent from my phone

**Comment by stickpeople** [comment]
I am  now getting the message for the past hour and a half when trying to upgrade from 3.0.10 to 3.0.15.  

Oops! The server is too busy to handle your request right now. Please wait and the page will keep trying every 30 seconds to generate your upgrade file. Depending on how busy things are, this may take a few attempts.

Thanks

**Comment by benkeen** [comment]
Hey @stickpeople, mind trying it now? I thought this problem was localized to the Custom Build section but apparently not.

**Comment by stickpeople** [comment]
That worked!   Thank you.
