### ISSUE TITLE
pages will not advance for going live step of multi form API

### ISSUE THREAD

**Issue by travisbonifield** [formtools/core#215]
I have successfully been able to get my multi form pages to work through the test submission step but now when I change the code out from initialize to *$fields = $api->initFormPage(X); to go live my pages will not advance to the next page I am stuck on the first page.

Thee are 14 pages in my form including the thank you page. Here is the code for the first page that will not let me advance now to my second page, it worked for testing submission now it doesn't.

```php
<?php
require_once("../formtools/global/api/API.class.php");
$api = new FormTools\API();
$fields = $api->initFormPage(1);
$params = array(
    "submit_button" => "nxtbtn",
    "next_page" => "male_mor_q_2.php",
    "form_data" => $_POST
);
$api->processFormSubmission($params);
?>
    <html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/page.css" rel="stylesheet">
        <link href="css/main_male_style.css" rel="stylesheet" type="text/css">
        <link href="css/super-panel.css" rel="stylesheet">
        <script src="script/super-panel.js.download"></script>
    </head>

    <body>

        <div id="container">
            <header class="headclass">
                <a href="">SharedGoals.us by Ringful Health</a>
                <span data-panel="panel1" class="panel-button" style="z-index: 9001;"></span>
            </header>
            <div class="transparent-layer" style="z-index: 8999; opacity: 0; display: none;"></div>
            <div id="panel1" style="transition: all 200ms ease-in; opacity: 0; transform: translate(0px, -10%) translateZ(0px); visibility: visible; display: none;">
                <div id="vertical-nav">
                    <a href="http://test.accumeds.co/dashboard.jsp"><i class="fa fa-home"></i> Dashboard</a>
                    <a href="http://test.accumeds.co/profile.jsp"><i class="fa fa-user"></i> Profile</a> <a href="#"><i class="fa fa-lock"></i> Logout</a> <a href="#"><i class="fa fa-close"></i> Close</a>
                </div>
            </div>
            <div class="maincontentbx">
                <!--    content -->
                <form method="POST">
                    <div class="main-content" style="margin:25px 0px 0px 0px;">In the past 7 days how many times did you eat fast food meals or snacks?</div>

                    <div class="secondary-one">
                        <input type="radio" name="mohr_fastfood" id="mohr_fastfood_none" value="mohr_fastfood_none" />
                        <label for="mohr_fastfood_none">None</label>

                        <input type="radio" id="mohr_fastfood_1_3_times" name="mohr_fastfood" value="mohr_fastfood_1_3_times" />
                        <label for="mohr_fastfood_1_3_times">1 to 3 times</label>

                        <input type="radio" id="mohr_fastfood_4_more_times" name="mohr_fastfood" value="mohr_fastfood_4_more_times" />
                        <label for="mohr_fastfood_4_more_times">4 or more times</label>

                    </div>
                    <div class="space"></div>

                    <div class="main-content">
                        In the past 7 days how many servings of fruits and/or vegetables did you eat every day?
                    </div>
                    <div class="secondary-one">
                        <input type="radio" id="mohr_fruit_5_more_servings" name="mohr_fruit" value="mohr_fruit_5_more_servings" />
                        <label for="mohr_fruit_5_more_servings">5 or more servings</label>

                        <input type="radio" id="mohr_fruit_3_4_servings" name="mohr_fruit" value="mohr_fruit_3_4_servings" />
                        <label for="mohr_fruit_3_4_servings">3 to 4 servings</label>

                        <input type="radio" id="mohr_fruit_2_less" name="mohr_fruit" value="mohr_fruit_2_less" />
                        <label for="mohr_fruit_2_less">2 or less</label>

                    </div>
                    <div class="space"></div>
                    <div class="main-content">
                        In the past 7 days how many sodas and sugar sweetened drinks (regular, not diet) did you drink every day?
                    </div>
                    <div class="secondary-one">
                        <input type="radio" name="mohr_soda" id="mohr_soda_none" value="mohr_soda_none" />
                        <label for="mohr_soda_none">None</label>

                        <input type="radio" id="mohr_soda_1_3_times" name="mohr_soda" value="mohr_soda_1_3_times" />
                        <label for="mohr_soda_1_3_times">1 to 3 times</label>

                        <input type="radio" id="mohr_soda_4_more_times" name="mohr_soda" value="mohr_soda_4_more_times" />
                        <label for="mohr_soda_4_more_times">4 or more times</label>
                    </div>
                    <div class="transparent-layer" style="z-index: 8999; opacity: 0; display: none;"></div>
                    <div id="panel1" style="transition: all 200ms ease-in; opacity: 0; transform: translate(0px, -10%) translateZ(0px); visibility: visible; display: none;">
                        <div id="vertical-nav">
                            <a href="http://test.accumeds.co/dashboard.jsp"><i class="fa fa-home"></i> Dashboard</a>
                            <a href="http://test.accumeds.co/profile.jsp"><i class="fa fa-user"></i> Profile</a> <a href="#"><i class="fa fa-lock"></i> Logout</a> <a href="#"><i class="fa fa-close"></i> Close</a>
                        </div>
                        <br>
                        <br>

                    </div>
                    <div id="footer">
                        <input type='submit' name='nxtbtn' value="next" class='btn' />
                </form>
                <p style="text-align:center;font-size:smaller;font-style:italic;color:#666; margin: 20px;">
                    Copyright, 2018 Ringful Health
                </p>
                </div>
            </div>
    </body>

    </html>
```

**Comment by benkeen** [comment]
Hi @travisbonifield, hmm that looks fine to me. 

The most common problem I find with the API is the sessions. Try loading the form up in a different browser: can you get past the first page? Another trick is to manually navigate to the last page in your form by changing the query string. That'll ensure the session clearing code will be called. 

Let me know if you're still having trouble and I'll investigate further.

**Comment by travisbonifield** [comment]
Hi,

Thank you for your response. Yes, I have tried both of these things with no luck. I was able to go through the initialize part of the multi page form using the API tutorial but then when I go back after changing the code from "$fields = ft_api_init_form_page(X, "initialize");" to "$fields = ft_api_init_form_page(X);" I cannot get past the first page.

I have tried different browsers and navigatigating to the clear session page and clearing browser cache. Still cannot navigate past the first page. Here is my going live code again, first page:
<?php
require_once("../formtools/global/api/API.class.php");
$api = new FormTools\API();
$fields = $api->initFormPage(1);
$params = array(
    "submit_button" => "nxtbtn",
    "next_page" => "male_mor_q_2.php",
    "form_data" => $_POST
);
$api->processFormSubmission($params);
?>
    <html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="css/page.css" rel="stylesheet">
        <link href="css/main_male_style.css" rel="stylesheet" type="text/css">
        <link href="css/super-panel.css" rel="stylesheet">
        <script src="script/super-panel.js.download"></script>
    </head>

    <body>

        <div id="container">
            <header class="headclass">
                <a href="">SharedGoals.us by Ringful Health</a>
                <span data-panel="panel1" class="panel-button" style="z-index: 9001;"></span>
            </header>
            <div class="transparent-layer" style="z-index: 8999; opacity: 0; display: none;"></div>
            <div id="panel1" style="transition: all 200ms ease-in; opacity: 0; transform: translate(0px, -10%) translateZ(0px); visibility: visible; display: none;">
                <div id="vertical-nav">
                    <a href="http://test.accumeds.co/dashboard.jsp"><i class="fa fa-home"></i> Dashboard</a>
                    <a href="http://test.accumeds.co/profile.jsp"><i class="fa fa-user"></i> Profile</a> <a href="#"><i class="fa fa-lock"></i> Logout</a> <a href="#"><i class="fa fa-close"></i> Close</a>
                </div>
            </div>
            <div class="maincontentbx">
                
           <form action="<?php echo $_SERVER["PHP_SELF"]?>" method='POST'>
                    <div class="main-content" style="margin:25px 0px 0px 0px;">In the past 7 days how many times did you eat fast food meals or snacks?</div>

                    <div class="secondary-one">
                      <input type="radio" name="mohr_fastfood" id="mohr_fastfood_none" value="mohr_fastfood_none" />
                      <label for="mohr_fastfood_none">None</label>

                        <input type="radio" id="mohr_fastfood_1_3_times" name="mohr_fastfood" value="mohr_fastfood_1_3_times" />
                        <label for="mohr_fastfood_1_3_times">1 to 3 times</label>
						
                        <input type="radio" id="mohr_fastfood_4_more_times" name="mohr_fastfood" value="mohr_fastfood_4_more_times" />
                        <label for="mohr_fastfood_4_more_times">4 or more times</label>

                    </div>
                    <div class="space"></div>

                    <div class="main-content">
                        In the past 7 days how many servings of fruits and/or vegetables did you eat every day?
                    </div>
                    <div class="secondary-one">
                                <input type="radio" id="mohr_fruit_5_more_servings" name="mohr_fruit" value="mohr_fruit_5_more_servings" />
                        <label for="mohr_fruit_5_more_servings">5 or more servings</label>
						
                        <input type="radio" id="mohr_fruit_3_4_servings" name="mohr_fruit" value="mohr_fruit_3_4_servings" />
                        <label for="mohr_fruit_3_4_servings">3 to 4 servings</label>
						
                      <input type="radio" id="mohr_fruit_2_less" name="mohr_fruit" value="mohr_fruit_2_less" />
                        <label for="mohr_fruit_2_less">2 or less</label>
						
                    </div>
                    <div class="space"></div>
                    <div class="main-content">
                        In the past 7 days how many sodas and sugar sweetened drinks (regular, not diet) did you drink every day?
                    </div>
                    <div class="secondary-one">
                        <input type="radio" name="mohr_soda" id="mohr_soda_none" value="mohr_soda_none" />
                      <label for="mohr_soda_none">None</label>

                        <input type="radio" id="mohr_soda_1_3_times" name="mohr_soda" value="mohr_soda_1_3_times" />
                        <label for="mohr_soda_1_3_times">1 to 3 times</label>
						
                        <input type="radio" id="mohr_soda_4_more_times" name="mohr_soda" value="mohr_soda_4_more_times" />
                        <label for="mohr_soda_4_more_times">4 or more times</label>
                    </div>
                    <div class="transparent-layer" style="z-index: 8999; opacity: 0; display: none;"></div>
                    <div id="panel1" style="transition: all 200ms ease-in; opacity: 0; transform: translate(0px, -10%) translateZ(0px); visibility: visible; display: none;">
                        <div id="vertical-nav">
                            <a href="http://test.accumeds.co/dashboard.jsp"><i class="fa fa-home"></i> Dashboard</a>
                            <a href="http://test.accumeds.co/profile.jsp"><i class="fa fa-user"></i> Profile</a> <a href="#"><i class="fa fa-lock"></i> Logout</a> <a href="#"><i class="fa fa-close"></i> Close</a>
                        </div>
                        <br>
                        <br>

                    </div>
                    <div id="footer">
                   <input type='submit' name='nxtbtn' value="next" class='btn'  />
                </form>
                <p style="text-align:center;font-size:smaller;font-style:italic;color:#666; margin: 20px;">
                    Copyright, 2018 Ringful Health
                </p>
                </div>
            </div>
    </body>

    </html>

I appreciate your help, Thank you.

**Comment by benkeen** [comment]
The most likely cause is sessions not being stored, so on page 2, the API code thinks the user hasn't started from page 1 and boots them back to the start of the form. At least, that's my best bet. 

Would you mind posting the block of PHP code at the top of your second page - `male_mor_q_2.php`?

**Comment by travisbonifield** [comment]
Sure no problem.

<?php
require_once("../formtools/global/api/API.class.php");
$api = new FormTools\API();
$fields = $api->initFormPage(1);
$params = array(
    "submit_button" => "nxtbtn",
    "next_page" => "phq9_male.php",
    "form_data" => $_POST,
    "no_sessions_url" => "male_mor_q_1.php"
);
$api->processFormSubmission($params);
?>

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by travisbonifield** [comment]
PLEASE HELP

**Comment by benkeen** [comment]
Hi Travis, sorry I have day job and usually only have time to look at this in the evenings. I'll try to reproduce it locally, I don't see anything wrong with your config. Keep you posted.

**Comment by travisbonifield** [comment]
Hey no problem, I've been trying all day with no luck. I hope you do better
than I.

**Comment by benkeen** [comment]
Let's try this. On your second form page, after this line

```php
$fields = $api->initFormPage();
```

(N.B. the "1" param to initFormPage() is only required on the first form page, but I don't think that's causing the problem). 

After that line, add this:

```
echo "Contents of sessions: ";
print_r($fields);
exit;
```

Then go to your first form page, fill in all the fields and click continue. Make sure your form's action attribute is pointing to itself, so `<form action="<?php echo $_SERVER["PHP_SELF"]?>" method='POST'>`

What that'll do is, as soon as you get to the second page, it'll output to the screen what's been saved in sessions. I want to see if anything has in fact been saved.

**Comment by travisbonifield** [comment]
Just tried it and it is still doing same thing. The link is live at
http://www.mygoals.health/php_app/male_mor_q_1.php

If that helps any.

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by benkeen** [comment]
Huh! In that case it's a problem with this first page - we're getting there. 

I see your submit button has a name attribute of "submit". Could you check the "submit_button" param is set to "submit" in your PHP at the top of page 1, too, like below:

```php
require_once("../formtools/global/api/API.class.php");
$api = new FormTools\API();
$fields = $api->initFormPage(1);
$params = array(
    "submit_button" => "submit", // <!--- this line
    "next_page" => "male_mor_q_2.php",
    "form_data" => $_POST
);
$api->processFormSubmission($params);
```

**Comment by travisbonifield** [comment]
It is, I actually changed the name while I was troubleshooting earlier
today. triple checked that. it is correct. this is really strange, I just
don't get it.

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by benkeen** [comment]
Hah, it is rather yeah. Try this: at the top of your page before the require_once line, add this:

```php
if (isset($_POST)) {
   echo "received post.";
   print_r($_POST);
   exit;
}
```

Then load the page and try submitting the form again. Just want to see if it even recognizes that the form is being posted to itself.

**Comment by benkeen** [comment]
ack, actually make that first line:

`if (isset($_POST) && !empty($_POST)) {`

**Comment by travisbonifield** [comment]
Sure, now all I am getting is this at the top of the screen

received post.Array ( [mohr_fastfood] => mohr_fastfood_4_more_times
[mohr_fruit] => mohr_fruit_2_less [mohr_soda] => mohr_soda_4_more_times
[submit] => next )

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by benkeen** [comment]
Cool, okay, so the form post is working, that's good. Do you know what version of PHP your server is running? You can just add this to the top of the page if you're not positive. 

```
echo PHP_VERSION;
exit;
```

**Comment by travisbonifield** [comment]
I'm pretty sure its 7. Let me check tho

**Comment by travisbonifield** [comment]
yes running 7.1.14

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by benkeen** [comment]
Well at this point I really don't see anything wrong, so we're going to need to go into the processFormSubmission function to find out why it's not doing it's job. 

I've attached an updated version of the file that just outputs some strings "1,2,3,...". Mind renaming your old `[formtools root]/global/api/API.class.php` to something else, and uploading this one? 
[API.class.php.zip](https://github.com/formtools/core/files/2007540/API.class.php.zip)

Alternatively, if you fancy letting me just debug the issue directly (I'll need FTP access to your server), just email me at ben.keen@gmail.com.

**Comment by travisbonifield** [comment]
yeah, sure let me set up ftp for you, give me a sec.

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>

**Comment by benkeen** [comment]
There is also a related issue which I've created here: https://github.com/formtools/core/issues/217

Will close this one.

**Comment by travisbonifield** [comment]
OK, thank you, FTP is still open

*-Travis Bonifield*
* 509.723.8187*
* travisbonifield@gmail.com <travisbonifield@gmail.com>*
* travis@ringful.com*  <travis@ringful.com>
