### ISSUE TITLE
Form Tools Admin Menu Shows When You Go to My URL

### ISSUE THREAD

**Issue by kayliemckee** [formtools/core#216]
After completing the installation process, my website no longer shows at my url: www.klmvisuals.com. Instead the form tools admin login shows. If you go to www.klmvisuals.com/index.html my website shows. PLEASE help!

**Comment by benkeen** [comment]
Hey @kayliemckee, it sounds like you install Form Tools right in the root folder of your website. Oops! You'll need to install it in a subfolder, like `/formtools`. I'd suggest deleting all the Form Tools files and re-installing it. 

A quick fix in the meantime is to rename/remove Form Tools's index.php file which you'll find in the same folder as your `index.html` file. Web servers are configured to load files in particular orders. Yours loads `index.php`  before `index.html` (which is pretty common), so removing / renaming it should fix it.
