### ISSUE TITLE
Thank you page is not being disabled

### ISSUE THREAD

**Issue by jacobidiego** [formtools/core#219]
Hi,
After publishing a newly created form and unchecking review and thanks page, the second one is not removed, and checkbox is back to enabled.

How can I disable it?

**Comment by benkeen** [comment]
Hi @jacobidiego, sorry for the wait - I've had a busy couple of days doing a lot of support! This sounds like it's related to this issue that was just fixed:
https://github.com/formtools/module-form_builder/issues/22

Would you mind upgrading to Form builder 2.0.8 and trying again?

**Comment by jacobidiego** [comment]
I have just tested it, and didn't worked.

**Comment by benkeen** [comment]
Hi @jacobidiego, I do apologize - this is a bug. I'll try to get this patched tomorrow night and let you know when a new version is available.

**Comment by benkeen** [comment]
I just released Form Builder 2.0.9 that fixes this issue. Thanks for reporting it!
