### ISSUE TITLE
May seem like a strange question BUT

### ISSUE THREAD

**Issue by daimonbok1** [formtools/core#225]
I like using Formtool, BUT I have a database need that saves the data as it's entered (somewhat like access) but using html/php forms for unit activity sheets in vehicles and reports etc.

Can this be done with formtools and mysql?????

**Comment by benkeen** [comment]
Hi @daimonbok1, you mean as the user types in each field it would automatically save to the database? Yes, with some development work you could certainly hook this up with Form Tools - and just use it to house the data and submit/access the data. But honestly, I'd investigate other solutions already geared towards this exact scenario (a LOT less work!) like Google Docs or something of that ilk.

**Comment by daimonbok1** [comment]
Thanks, was trying to use something I’m more familiar with…

 

Gene
