### ISSUE TITLE
Thank you page is not being disabled

### ISSUE THREAD

**Issue by jacobidiego** [formtools/core#228]
#219 

Hi benkeen, I wont close this jet.
I have tested the new version 2.0.9. and I can see that the checkbox in formbuilder is saved, but the thank you page continue showing up after submitting. Was not disabled.

**Comment by benkeen** [comment]
Hi @jacobidiego, I think it's actually ok. The option in the interface named "Include Thanks page in nav" is just that: for the navigation only. All forms have a page that the user is redirected to after submitting the form. 

You don't want this in your case? Would you like it to just resubmit to the same page or something?

**Comment by jacobidiego** [comment]
Well yeah
I expected that by disabling the thank you page. Then it would only refresh the form ready for a new submission.
