### ISSUE TITLE
Submissions view in Form Builder form interface

### ISSUE THREAD

**Issue by jacobidiego** [formtools/core#238]
Just that.
I can't find a way to enable the list of lasts 10 entries to the database.

If it doesn't exists could you add this as Feature request?

**Comment by benkeen** [comment]
Hey @jacobidiego, by default when you log in, go to the forms page and click on "view" for any form it'll list the last 10 submissions made to that form (submissions are listed most recent first by default, but this can be edited in the View). Is this what you need?
