### ISSUE TITLE
Required copy button inside submission data

### ISSUE THREAD

**Issue by nag5575** [formtools/core#250]
Hi, As per my business requirement, I need a copy button beside add button to make duplicate record of selected submission record. Please refer the attachment  . Please Please help me....

Tons of thanks...
Nag
![copy](https://user-images.githubusercontent.com/40289968/41455678-8eb635f8-709b-11e8-9a7e-c3302fdde936.jpg)

**Comment by benkeen** [comment]
Yeah I think this is a doable! Let me see if I can get it into the next release.

**Comment by benkeen** [comment]
Hey @nag5575, just to confirm: yes, this feature will be in 3.0.3. I've got it working locally now.

**Comment by nag5575** [comment]
Tons of thanks Mr. Banjamin...Appreciate your prompt support... :-)

Best Regards,
Nag

**Comment by benkeen** [comment]
Closing. Added in 3.0.3. Should be released this week.
