### ISSUE TITLE
Restrict blank record by clicking add button

### ISSUE THREAD

**Issue by nag5575** [formtools/core#251]
Inside submission record, if we click on add button, blank record is creating, Is there any possiblility to restrict to create blank record. 
Thanks,
Nag

**Comment by nag5575** [comment]
Thanks a lot Benjamin, Appreciate your prompt response. Absolutely right,
After submission only a new record should be created.

Regards,
Nag

**Comment by benkeen** [comment]
Yeah. I think that would be a more natural behaviour, actually. Thanks, I'll give it some thought!

**Comment by benkeen** [comment]
Hey @AllMySoccer, yes absolutely! It's turned on and off in the View. Just go to Edit Form -> Views -> Edit View -> General tab and set the "Can add submissions" setting to "no". 

Hope this helps! And sorry for the long response time.
