### ISSUE TITLE
2 Questions - double information and client change password only

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#253]
Hi everybody,

I have 2 questions, 

1- someway to avoid to have same information in a field, in my case, avoid to have double and triple emails and data.
 
2- someway  to let the "client" edit only password.

Thanks in advance :)

**Comment by benkeen** [comment]
Hey @nelsondcosta23 right now the only way to prevent duplicates is by controlling the way the data is first inputted. By using an API form you can control it down to the last detail (e.g. use this method: https://docs.formtools.org/api/v2/check_submission_is_unique/). 

Sorry about that.
