### ISSUE TITLE
How to prevent duplicate form filling.

### ISSUE THREAD

**Issue by KrishnaPB** [formtools/core#255]
We have one for generated using form tool. how we can prevent from duplicate entry. Please provide me the steps to solve this.

**Comment by benkeen** [comment]
Hey @KrishnaPB, I'm afraid there's nothing out the box that prevents multiple entries with the same content - each will have their own unique submission ID, of course, but the rest of the data may be the same as other submissions.

If you're using the API, you can use this method:
https://docs.formtools.org/api/v2/check_submission_is_unique/

That let's you identify which fields you want to check for uniqueness.

**Comment by KrishnaPB** [comment]
Thank you. I will check
