### ISSUE TITLE
Referencing one form in another (Product table referencing customer that bought them)

### ISSUE THREAD

**Issue by Laurapaws** [formtools/core#257]
Hey so I'm just wondering if there's a way to do this above. I've set up a simple customer data input form for our jewellery business and would like to make another for entering the product that they bought.

The reason this can't be on the same form is because sometimes a customer might come back, or they might buy two at once (i.e. different wedding rings).

I imagine the ideal situation being that once a customer is created, the staff member could click something on the row to be sent to a product entry page for that customer. I can see one workaround to be filling out name/postcode in the product form - that'll get me shouted at for not doing a proper job though! :stuck_out_tongue_winking_eye:

**Comment by nelsondcosta23** [comment]
7am here, no coffee yet... so if I understood you what one form to search and fill information in other form?

**Comment by Laurapaws** [comment]
No sorry. Imagine you have a Customer table and a Product table in the database. Each product can only be bought once. What I'm trying to do is to first fill out a form for the Customer table, including their address, name and such, then be able to pass through a unique customer ID to the product table to link products to customers. The effect this would have is that you'd be able to drill down into a customer and see everything they have bought from us.

The more I look into this, though, the more I'm realising that it's probably something I'll have to use the API to put together manually. If that's definitely the case then I'll close the ticket :smiley:
