### ISSUE TITLE
graphic appear error

### ISSUE THREAD

**Issue by thebitdoctor** [formtools/core#258]
hi, I updated the website with a ssl certificate changing into from http to https, now the appearance of the website is like without the css files is there any chance to fix it?

**Comment by benkeen** [comment]
Oh sure! Just edit your `[form tools root]/global/config.php` file and update the `$g_root_url` setting to include https instead of http.

**Comment by nelsondcosta23** [comment]
Do what Ben tell you, and dont forget to change in setting the main tab and arquive tab to https :)
