### ISSUE TITLE
empty tables , no form saves any data exept for date ip etc...

### ISSUE THREAD

**Issue by madriz475** [formtools/core#271]
Make fresh installation created a simple form, submitted and no data is saved it records empty rows just saving  the default date , ip and modification date. tried several times and nothing last year i used it and no troubles, any idea why is not or saving empty fields?

Apache Version | 2.4.33
-- | --
PHP Version | 5.5.38
MySQL Version | 5.6.39-cll-lve
Architecture | x86_64
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 2.6.32-673.26.1.lve1.4.30.el6.x86_64

**Comment by benkeen** [comment]
Hey @madriz475, what kind of form is it? (https://docs.formtools.org/userdoc/form_management/form_types/)

If it's your own form, check 2 things:
1. The `<form>` tag should have a `method="post"` attribute (GET works too, but POST is more standard).
2. Your form fields have `name` attributes. 
3. Check the form in Form Tools actually has other fields. Maybe they didn't get created?

**Comment by madriz475** [comment]
Finally Discovered that something went wrong with the site account, I deleted and created it again reinstalled all and it worked again Maybe php or sql config went wronfg somewhere 


Thanks ALL!! 

:)
