### ISSUE TITLE
Show questions based on answers

### ISSUE THREAD

**Issue by CharlsBags** [formtools/core#274]
I'd like to known how to build a form that show questions based on answer:

Question 'Do you like'
- Answer A > Module with Questions 1,2,3
- Answer B > Module with Questions 4,5,6

Thank you

**Comment by benkeen** [comment]
Hi @CharlsBags, I'm afraid there's nothing out-the-box in Form Tools that lets you do something like this. I think what you'll need to do is code your own form to hide/show fields as you need.

Sorry I couldn't be more help!
