### ISSUE TITLE
Upgrade issue while upgrading from  version 3.0.2 to 3.0.3 

### ISSUE THREAD

**Issue by prbt2016** [formtools/core#277]
Hi,

After upgrading from  version 3.0.2 to 3.0.3 ,**{{DBPREFIX}}views** table does not contain the row
**`may_copy_submissions` enum('yes','no') NOT NULL DEFAULT 'no'** .

However this row is  present in the fresh installation of 3.0.3 .

Followed this process to upgrade 
https://docs.formtools.org/upgrading/

What causes this issue?

**Comment by benkeen** [comment]
Thanks @prbt2016, I'm going to try to get 3.0.4 released this weekend containing a couple of fixes. I'll include this in that. Thanks!

**Comment by benkeen** [comment]
This has been fixed and will be in the 3.0.4 release this weekend. I need to examine another issue before releasing the version to the wild, so stay tuned.
