### ISSUE TITLE
Optional IP Address 

### ISSUE THREAD

**Issue by stefan-schindler** [formtools/core#278]
Hi, nice work :)

It would be nice also to have option to remove the IP Address field, or is it just me not seeing the way it could be turned off?

**Comment by benkeen** [comment]
Thanks, hope it comes in handy! 

The IP address is always stored with each record, but you can hide it from view/download etc. by editing the form View and removing it there. 

Hope this helps!

**Comment by stefan-schindler** [comment]
I needed it because of the new GDPR law where even storing the IP address in database is a problem, if you don't need it necessarily. So the main issue is not with presenting the IP address in views, but the fact that it is stored in DB :)

**Comment by benkeen** [comment]
Oh I see. Hmm. At this moment I'm afraid there's no choice: it's baked in and can't be removed. That said, you could hook up a Submission Pre-Parser rule to strip it out for all new submissions. That may be the best approach. If that's useful, let me know and I'll put something together.

**Comment by nelsondcosta23** [comment]
Make a script that clean the ip_adress table, execute the script with a cronjob. 24/24 hours

**Comment by stefan-schindler** [comment]
Thanks for the tips. My first workaround was directly replacing the $_SERVER['REMOTE_ADDR'] with empty value in the core files, however unfortunately I had to abandon FormTools because it haven't had all the functionality I needed, for example conditional questions (which I get, are really hard to be implemented universally). But I think that in the future more and more people will be concered about storing only the neccessary data, so I think the ability to delete the IP address field would be a nice and appreciated feature by many.

**Comment by benkeen** [comment]
I've added this as a feature request here: https://github.com/formtools/core/issues/388
