### ISSUE TITLE
Add inline CSS code to all phone fields

### ISSUE THREAD

**Issue by Claude-Viglob** [formtools/core#286]
Hi,

I'm having trouble finding where to put inline CSS code for the phone fields.

We added Formtools in our CMS to give the option to our clients to make their own forms and it's great!
But, right now, the phone inputs display like this -->

![image](https://user-images.githubusercontent.com/42002184/43598576-fc670ad2-9652-11e8-9c69-ec8af31b70a2.png)

And I need something like this instead -->

![image](https://user-images.githubusercontent.com/42002184/43598721-613677fe-9653-11e8-9dcc-0aa52b2acc10.png)

Thanks in advance for the help, it's really appreciated.

Claude.

**Comment by benkeen** [comment]
Hi Claude, 

Ah, curious! So it *should* look like what you want, just out the box. The HTML markup outputted contains a `size` attribute on each field which should govern how wide each input field is. I would imagine that there's some CSS going on in your form that is overriding that behaviour and making them full width. If you can post a link to your form I could take a look and suggest some CSS to override it.

**Comment by Claude-Viglob** [comment]
Hi Ben,

Here's the link to my form.

http://assoutf8.cleanviglob.com/modules/formulaires

Thank you.

**Comment by benkeen** [comment]
No problem! This CSS will overwrite your styles to return it to show the default widths:

```css
body #input_ft > input[name="tel_1"], 
body #input_ft > input[name="tel_2"], 
body #input_ft > input[name="tel_3"] {
	width: inherit !important;
}
```

**Comment by Claude-Viglob** [comment]
It will work for this form, but since our clients can make their own forms, I don't know what the name of the input will be.

Is there a way to add this css to every phone input without knowing what their name will be?

**Comment by benkeen** [comment]
Hey @Claude-Viglob,

Ah I see. It looks like a modified Form Builder template, correct? So what you could do is add in an extra class to each field that specifies what field type it is. 

Here's an example. This modifies the Default Template Set's "Form Page" template:

```
{{navigation}}

<h2>{{$page_name}}</h2>

{{error_message}}

<form action="{{$page_url}}" method="post" enctype="multipart/form-data"
  id="ts_form_element_id" name="edit_submission_form">
  <input type="hidden" id="form_tools_published_form_id" value="{{$published_form_id}}" />
{{foreach from=$grouped_fields key=k item=curr_group name=row}}
  {{assign var=group value=$curr_group.group}}
  {{assign var=fields value=$curr_group.fields}}

    <a name="s{{$group.group_id}}"></a>
  {{if $group.group_name}}
    <h3>{{$group.group_name}}</h3>
  {{else}}
    <br />
  {{/if}}

  {{if $fields|@count > 0}}
  <table class="table_1" cellpadding="1" cellspacing="1" border="0" width="798">
  {{/if}}
    
  {{foreach from=$fields item=curr_field}}
    {{assign var=field_id value=$curr_field.field_id}}
    <tr>
      <td width="180" valign="top">
        {{$curr_field.field_title}}
        <span class="req">{{if $curr_field.is_required}}*{{/if}}</span>
      </td>
      <td class="answer" valign="top">
        <div class="pad_left field_type_{{$curr_field.field_type_id}}">
        {{edit_custom_field form_id=$form_id field_info=$curr_field field_types=$field_types
          settings=$settings submission_id=$submission_id}}
        </div>
      </td>
    </tr>
  {{/foreach}}

  {{if $fields|@count > 0}}
    </table>  
  {{/if}}

{{/foreach}}

{{continue_block}}

</form>
```

Note this line: `<div class="pad_left field_type_{{$curr_field.field_type_id}}">`: that adds a class to the div that wraps each form field with a `field_type_X` class, where `X` is the field type ID. 

If you then refresh the form page and check the source, all phone number fields will have a unique class for that row (in my testing it's `field_type_7`) which you can use to style, like so:

```css
body #input_ft.field_type_7 {
	width: inherit !important;
}
```
(Assuming you left the input_ft ID on the div as well - not in the code above).

Hope this helps...!

**Comment by Claude-Viglob** [comment]
Hi Ben,

I'll try this tomorrow morning, but I have a good feeling about this.

Thank you so much for your help, you're my savior haha!

**Comment by Claude-Viglob** [comment]
Hooray!! It worked.

![image](https://user-images.githubusercontent.com/42002184/43679875-874bc5a8-97fb-11e8-8ca5-91a6bcd54ef8.png)

Thanks for taking the time to test and find the solution to my problem!
