### ISSUE TITLE
Pass error message(s) to external form via query string

### ISSUE THREAD

**Issue by zgramana** [formtools/core#289]
As an external form user, I want `process.php` to pass error messages to me via the form's redirect URL query string so that my static page can display error results so that if a user fails to click the reCAPTCHA "I'm not a robot" checkbox, I can display the error message.

Bonus points for also (optionally) passing the form entries they submitted to `process.php` as well.

**Comment by benkeen** [comment]
Hey @zgramana, sorry for never getting back to you. 

Yeesh! I'm afraid that's not doable. The only way the captcha error gets caught is via sessions behind the scenes, so it doesn't add anything to the query string. But did you check out this tutorials? It covers those two exact scenarios you mentioned:

Recaptcha with POST forms: https://docs.formtools.org/tutorials/post_form_captchas/
Refilling form fields with POST forms that fail captcha: https://docs.formtools.org/tutorials/post_form_captchas/reentering_fields/
