### ISSUE TITLE
installation error when step3

### ISSUE THREAD

**Issue by rickywu** [formtools/core#299]
cache folder already set full permssions:
drwxrwxrwx 2 www-data www-data 4096 Aug 14 15:47 cache/

php7.0 with nginx and php-fpm

but still got error:
```
2018/08/14 15:50:22 [error] 483#483: *52868 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/html/themes/default/cache/wrt5b7289be0b72a8_76231808 <--
  thrown in /var/www/html/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php on line 49" while reading response header from upstream, client: 118.122.*.*, server: 52.80.*.*, request: "POST /formtools/install/step3.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "52.80.*.*", referrer: "http://52.80.*.*/formtools/install/step3.php"
```

**Comment by benkeen** [comment]
Hey @rickywu, sorry for not responding earlier - I actually my own installation the moment I saw your post to check I didn't introduce anything in 3.0.6, but it appears to be fine. 

I've found on some servers that even though the folder itself is a read-writable, the PHP process can't actually write to the folder. Are you using any sort of CMS to control your site? Once I encountered a configuration setting in a users .htaccess access file that prevented this. You might want to check that. Failing that, you could perhaps contact your hosting provider to see what they recommend. 

I'm going to create a ticket to improve the FT code here though. During the step that checks the folder is rewritable, it should actually attempt to create a temporary file there as well - just to confirm that it truly is read-writable to the PHP process.

**Comment by rickywu** [comment]
I fixed this problem, the parent folder should be writable by the user of php processor, means the /var/www/html should be writable by www-data in my case.

Thanks
