### ISSUE TITLE
Multi Upload

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#300]
Hi, anyone have an idea to make a multi upload file?
The ideia is, have a field and can upload what ever he wants.

Maybe that field create a folder and read everything inside the folder.... ideias?!

**Comment by benkeen** [comment]
Yeah very doable. Especially now; the existing file uploader is pretty dated but now HTML5 (multiple) file uploading is pretty well supported. 
https://caniuse.com/#feat=input-file-multiple

**Comment by nelsondcosta23** [comment]
Hi Ben, multi upload ROCKS HARD :)

Just a question, how can I send the links within an email?

`    <td><a href="{$FILEURL_anexos}">{$FILENAME_anexos}</a></td>`

output

> upload/cmarquivo/5_CM-anexos-20190225.mim.jpg:4_CM-anexos-20190225.wallpaper1.jpg:4_CM-anexos-20190225.wallpaper2.jpg:4_CM-anexos-20190225.workflowmanagement1.jpg

**Comment by benkeen** [comment]
Ooh, drat. Let me look at this tomorrow night - it may be possible with just plain Smarty to do what you want, but I'll probably want to add a method to make it a lot simpler. Keep you posted.

**Comment by benkeen** [comment]
And actually, I'll close this ticket now it's been added. :) Will open another one.

**Comment by benkeen** [comment]
Hey @nelsondcosta23, glad you caught this! But sorry, I actually don't have a fix for this just yet. I hoped I'd be able to find a workaround with Smarty but it's eluded me tonight. Bit of a fussy problem. 

I'll be sure to include a fix for this in 3.0.14.

**Comment by nelsondcosta23** [comment]
Hi @benkeen don't worry :)
Take the time you need, I don't have any idea how smarty works but if I found out some solution I share
