### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by aleenf1** [formtools/core#301]
I'm trying to update the view and comes out the fatal error

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'may_copy_submissions' in 'field list'' in /home/cmtix10h/public_html/global/code/Database.class.php:71 Stack trace: #0 /home/cmtix10h/public_html/global/code/Database.class.php(71): PDO->prepare('\n UP...') #1 /home/cmtix10h/public_html/global/code/Views.class.php(753): FormTools\Database->query('\n UP...') #2 /home/cmtix10h/public_html/global/code/Views.class.php(695): FormTools\Views::updateViewMainSettings('3', Array) #3 /home/cmtix10h/public_html/admin/forms/edit/page_edit_view.php(30): FormTools\Views::updateView('3', Array) #4 /home/cmtix10h/public_html/admin/forms/edit/index.php(122): require_once('/home/cmtix10h/...') #5 {main} thrown in /home/cmtix10h/public_html/global/code/Database.class.php on line 71

My Database.class.php on line 68 to 71 is like that:

{
        $query = str_replace('{PREFIX}', $this->table_prefix, $query);
        $this->statement = $this->dbh->prepare($query);
    }

Can somebody help to solve the issue?

**Comment by benkeen** [comment]
Hmm, hey @aleenf1 - what version of Form Tools are you running? `may_add_submissions` was added in an earlier version. Did you upgrade or do a fresh install of your current version? If you upgraded what version did you upgrade from?

Thanks!

**Comment by aleenf1** [comment]
Hey @benkeen  i'm upgrading from 3.02 to 3.03, just today realised no longer able to save the view after modified.

**Comment by benkeen** [comment]
Ah okay, best to upgrade to 3.0.6: that should fix this problem. 

Let me know if you still encounter it after upgrading.

**Comment by aleenf1** [comment]
Okay, solved after updating it. Thanks @benkeen

**Comment by benkeen** [comment]
No problem!
