### ISSUE TITLE
Offline Forms not showing for clients

### ISSUE THREAD

**Issue by hugomad** [formtools/core#305]
Like the title says, whenever a form is put offline, only the administrator account can see them (namely the submissions).
Found an old forum thread for the same issue where it had been fixed (2009): [https://forums.formtools.org/showthread.php?tid=51](url)

**Comment by benkeen** [comment]
Hi @hugomad, yes this appears to be a bug. Thanks for letting me know! I'll patch it in the next 3.0.x release.

Note for myself: also, when changing a form to offline, on the Edit Client -> Forms tab, offline forms don't appear as an option either.

Hmm... I think I'm going to rename this setting, too. `Offline`/`Online` are misleading terms and suggest all manner of possibilities (e.g. the form being visible). Ultimately the point of the setting is specifically to control whether Form Tools accepts new submissions through any means (internal form, external form, form builder form, API). So maybe an "Accepts new submissions" checkbox would be clearer.

**Comment by benkeen** [comment]
Fixed in 3.0.7.
