### ISSUE TITLE
Fatal error:  Call to a member function prepare() on null

### ISSUE THREAD

**Issue by HarborSide** [formtools/core#310]
I upgraded from 2.2.6 to 3.0.6 (latest version), all seems well. We are using our own form, not the form builder. 

When I test our form for the first time (since upgrade), I receive Fatal error: 
Call to a member function prepare() on null in ./ft/global/code/Database.class.php on line 71

Can you help me resolve this error so that our users don't encounter the issues when filling in form details. Thank you,
HarborS

**Comment by benkeen** [comment]
Hey @HarborSide, 

Yeah, probably best that you upgraded, 2.x is pretty old by now. 

For your form problem, are you using the API, or is your form an External Form where you submit the contents to `process.php`? 

That's a pretty generic error... could you maybe check your PHP error logs and see if it provides a few more details like a stacktrace? 

Ben

**Comment by HarborSide** [comment]
We are using an external form.

The error points to this line item (of the Database.class.php) from the upgraded form tools file:
$this->statement = $this->dbh->prepare($query);

Googling the issue ("Call to a member function prepare() on null") seems to suggest a correlation between db and PDO, and the way each should be defined (& their exceptions).

I'm looking deeper into PHP error logs, but do want to add that the form builder works.

This issue with the external file remains unresolved! 
HarborSideS

**Comment by HarborSide** [comment]
I am looking to update this ticket. In using the form builder, I receive an error when I click to "edit" an entry: Fatal error: Call to undefined function smarty_modifier_custom_format_date() in 

and then it gives the directory path. Can you assist with this issue please? Thank you. 
HarborSideS

**Comment by sf23103** [comment]
Did you find a solution to this?  I am experiencing this with FT 3.0.9 on external forms

**Comment by HarborSide** [comment]
No solution as yet. The error still exists. and when I turn on date picker, the entry is no longer viewable except by submission ID. Error is present in that instance as well.

**Comment by benkeen** [comment]
I'm afraid I don't have anything to suggest beyond checking the error logs again and check the stacktrace to find the whole list of files that lead to the error in Database.class.php - all SQL queries get routed through that file, but somewhere up in the stack it'll show the actual file that contains the SQL query. That's the one we need to track down.

Alternatively, if you're really stumped and don't mind me debugging the issue right on your site, email me at ben.keen@gmail.com and I can take a look.

**Comment by flcowboy7** [comment]
@benkeen - I just got this same error on the other two installs I just upgraded to 3.0.9. Error happens whenever an API form is submitted. PHP log doesn't show a stacktrace, just the same error message.

**Comment by benkeen** [comment]
> Did you already make a bug for this in the next core version?

Yup! I'll put aside the file upload module update I'm doing & start on that tomorrow.

**Comment by HarborSide** [comment]
Thank you, Ben, please continue to keep me advised on this issue.

 

WE HAVE A NEW ISSUE. Last week, we secured our site https:// And now the view is all messed up: https://www.ibew910.org/ft/

 

I went to form tools site and uploaded the new classic grey and blue themes into the ft/theme folder.

 

LOGIN DETAILS:

Username: ibew910

Password: guest

 

I went through the database and turned all http:// links in form tools to https://. Our view did not change.

 

I went in to the website, and made sure it read: https:// as well.

 

Please login and let me know how I might fix the view form ; I am not sure how going from http:// to https:// messed it up.

 

Thank you,

Bev

 

 

 

 

 <http://www.harborsideservices.com/> cid:image001.png@01D33F6F.37815960

Beverly Sterling-Affinati

Proprietor, HarborSide Services

Web Development & Marketing

 

A WOMAN OWNED-VETERAN OWNED BUSINESS

Phone: (315) 408-0884

Email: harborsideservices@gmail.com

 

 

"My grandmother would constantly say, 'Sister, when you get, give. When you learn, teach.'"
~ Maya Angelou, author

**Comment by HarborSide** [comment]
Thank you,

 

I have made this change,

Bev

 

 

 

 

 <http://www.harborsideservices.com/> cid:image001.png@01D33F6F.37815960

Beverly Sterling-Affinati

Proprietor, HarborSide Services

Web Development & Marketing

 

A WOMAN OWNED-VETERAN OWNED BUSINESS

Phone: (315) 408-0884

Email:  <mailto:harborsideservices@gmail.com> harborsideservices@gmail.com

 

 

"My grandmother would constantly say, 'Sister, when you get, give. When you learn, teach.'"
~ Maya Angelou, author

**Comment by flcowboy7** [comment]
@HarborSide - Probably should create a new issue for this, but you'll ultimately need to have a separate .htaccess file with special directives added to the root of the formtools directory on your server.

**Comment by HarborSide** [comment]
Thank you for keeping me updated. I appreciate the information and what the new .htaccess file special directives should say. We are still seeing an error, 

Bev

 

 

 

 

 

Beverly Sterling-Affinati

Proprietor, HarborSide Services

Web Development & Marketing

 

A WOMAN OWNED-VETERAN OWNED BUSINESS

Phone: (315) 408-0884

Email: harborsideservices@gmail.com

 

 

It's the dawn of of a New Year - let's welcome it with all the enthusiasm necessary to assure a successful, prosperous twelve months.

**Comment by HarborSide** [comment]
I opened a ticket under 'new issue'. You may close this ticket.
