### ISSUE TITLE
Serious Database error when using dearch

### ISSUE THREAD

**Issue by erewhom** [formtools/core#313]
Hi 

System hit a serious error when doing a search from views 
I'm running 3.06

a screenshot of the error is below 
![error](https://user-images.githubusercontent.com/43051521/45266630-fdea2300-b455-11e8-8b4b-609c2aae718f.png)

**Comment by benkeen** [comment]
Hi @erewhom, thanks for letting me know! Drat, I thought I fixed this very issue a couple of versions ago, but apparently it's still around. 

I'll fix this in the next release.

**Comment by benkeen** [comment]
Closing - fixed in 3.0.7.
