### ISSUE TITLE
Question - Clients only change password

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#324]
Hi guys, how are you?

There is any way in code or other method, to the clients only be able to change the password on settings?

Thanks in advance

**Comment by benkeen** [comment]
Hey @nelsondcosta23! I actually don't quite follow the question though - do you mean change their own password security settings?

**Comment by nelsondcosta23** [comment]
Hi Ben,

The clients can change user name, email, password and other fields.
I need a way to the clients only can change the password field.
Because I don't want them to change user and mail.

Even if I have to edit the code :p

Thanks

**Comment by benkeen** [comment]
Ahhh, gotcha. Yeah unfortunately that's not offered just yet - but I'll make a note of it to include in FT 3.3 (the permissions rewrite release).

Doctoring the code is a pretty desperate move, but when you gotta you gotta! I'd suggest creating a copy of your default theme, then in your copy, disable those fields in the template markup. That, at least, will allow you to safely upgrade without having anything overwritten. The template file for that is here: `/themes/default/clients/account/tab_main.tpl`. 

At that point when clients log in they'll see those fields greyed out. Cool. The next problem is that the code that runs when you update the page assumes the request contains that info. So we'll need to overwrite that. Take a look at this chunk of code:
`https://github.com/formtools/core/blob/master/global/code/Clients.class.php#L500-L518`. You'll need to tweak that to remove the fields you don't want the client updating. 

NOT a beautiful solution, and beware that all upgrading will require you to re-do that change.

So yeah, 3.3 can't come soon enough. :)

**Comment by nelsondcosta23** [comment]
That was my plan :)

Thanks Ben, and thanks for adding this as a future feature request.
