### ISSUE TITLE
Upgrade to 3.0.8 from 3.0.2

### ISSUE THREAD

**Issue by Jesperanza** [formtools/core#329]
I already have 3.0.2 and the database running fine. Went to upgrade to 3.0.8 and am encountering the following:

I've run through the [upgrade steps ](https://docs.formtools.org/upgrading/)up til Step 6, the login page. I don't get the login page, but i get an install page. If i run through that, it flags that i have a database already created.

![image](https://user-images.githubusercontent.com/29239673/46096611-a6ee8880-c18d-11e8-93e4-745365752321.png)

So then, I moved the config.php from the backup formtools folder to the same spot in the new formtools folder. This is what i'm getting: a "blank" screen.

![image](https://user-images.githubusercontent.com/29239673/46096557-81fa1580-c18d-11e8-816d-a23a9b8c6eee.png)

What am i doing wrong? Thank you.

**Comment by benkeen** [comment]
Hi @Jesperanza, 

Sorry for not responding sooner! You actually shouldn't need to reinstall anything after an upgrade... were you automatically redirected to the installation script after upgrading? If so, it sounds like your `/global/config.php` file may have been overwritten. If that isn't defined, the script thinks it's a fresh installation and takes you to the installation script.

Did you backup your old files? If so, check to see if the config.php file still exists and just copy it into your `global` folder. That should return everything to normal.

Ben

**Comment by Jesperanza** [comment]
I figured that was the case. If you read the second half of my question again, you'll see I have tried moving my backup config.php file over, but am getting a half-blank screen. Thoughts about what might be causing that? thanks.

**Comment by benkeen** [comment]
Sorry @Jesperanza! I missed the second part of your post. 

Couple of things to try:
- Clear out the content of your theme cache folder (themes/default/cache) and try refreshing the pag. This has never been an issue before but just recently an issue came up with another installation where Smarty had created an invalid cache file for a page.
- If that doesn't fix it, check your PHP error logs on the server and see if it's outputting anything helpful. 
- Also, just to rule it out, you might want to open developer tools on your browser and see if the page is trying to load resources but can't get them. That would mean there's either a problem with the server doling up the files, or the files no longer exist. 

Different browser's dev tools vary, but on Chrome you can just go to the "Console" tab for all errors to get listed. 

Let me know how it goes.

**Comment by Jesperanza** [comment]
I have it working now. Thank you.

Initially, i see was setting it up wrong. I wanted to eliminate loosing submissions during the upgrade process, so i created another folder for the update and was just going to change filename and config, but that obviously didn't work. All good now.
