### ISSUE TITLE
Specify email field does not work, 3.0.8

### ISSUE THREAD

**Issue by gummisko** [formtools/core#332]
Hello Ben, 

Sorry, another issue, maybe brought to your attention already for I have encountered in earlier FT3.0x versions. When I try to specify what field is email-field in order to set response-email email-address I get a 'file not found' error.

Please see attached image for clearification

![erroremail](https://user-images.githubusercontent.com/16030076/46288756-1813ae80-c587-11e8-88e3-6e4186767d38.jpg)

Regards

gerard

**Comment by benkeen** [comment]
No worries, thanks for the heads up! Another one for 3.0.9. :)
