### ISSUE TITLE
Form creation bug - for external, direct forms with private access 

### ISSUE THREAD

**Issue by tkelling** [formtools/core#333]
Hello,

I discovered a bug with the form creation process. I've used Formtools for eight years and haven't seen this before version 3. We've used version 3 for months but haven't created a new form until now.

The issue occurs when creating an "external" and "direct" form with "private" access. When following those options, I sometimes get a blank page but mostly it forces the API installation instructions instead of the simple post method that we want and always use.

I've tested this many times and on a couple browsers. It appears to be a consistent issue. It appears to be related to Formtools version 3.

The workaround I'm using is creating forms with only "administrator only" access. Then I change the form to "private" access and add clients after launching the form.

Thanks,

Thad

**Comment by benkeen** [comment]
Hi @tkelling, thanks for the heads up! I won't have time this evening to look at this but I'll take a look tomorrow. Assumings it's a bug (it sounds like it is) I'll do a 3.0.9 release to fix it. 

Thanks!

Ben

**Comment by benkeen** [comment]
Yup, this is a bug. Thanks again for letting me know.

**Comment by tkelling** [comment]
Hi again. Can you say when we should expect the 3.0.9 release with this fix and whatever other improvements you're making? Thank you.

**Comment by benkeen** [comment]
Hey @tkelling, sorry for the wait on this, I've been out of town. I won't promise getting it released by this weekend but it shouldn't be much longer. Just need to handle a few other things first.

**Comment by benkeen** [comment]
All fixed. I'll get 3.0.9 out this afternoon.
