### ISSUE TITLE
I want to modify the form, but every time I made it, need to modify again. Is there a way to do it  in the one who generate the php one.

### ISSUE THREAD

**Issue by dropej** [formtools/core#334]

**Comment by benkeen** [comment]
Hi @dropej, 

Sorry for not responding sooner - I was out of the country for a few weeks. 

I actually don't quite follow your problem though... what sort of form are you using? An internal, external or Form Builder form? Are you editing the raw PHP of a Form Builder form? (That wouldn't be a good idea...!)

**Comment by dropej** [comment]
Yes, I was editing Form Builder Form. What is that you recommended? Please, excuse my newbie.

**Comment by benkeen** [comment]
No worries! The _generated_ Form Builder forms can't be edited directly. What you need to do is either edit the fields / View to change what fields appear in them, or edit the Form Builder templates themselves so your form looks different. For that, go to Modules -> Form Builder -> Template Sets - > Edit. That section contains all the markup and CSS used in your form. That's where you'll want to edit.

Hope this helps!

**Comment by dropej** [comment]
Thanks.
