### ISSUE TITLE
Your test email could not be sent.

### ISSUE THREAD

**Issue by spronay** [formtools/core#338]
New to Formtools. Installed and configured 3.0.8 in https environment on shared hosting server. Everything seems to work **except** I can't use Formtools to send emails as expected. When submitting test form, no emails arrive. And under the Test tab in the email template editor (admin/forms/edit/index.php?page=edit_email), sending a test email consistently gives me "Your test email could not be sent."

Configuration and Recipients all appear to be okay. Any ideas?

**Comment by benkeen** [comment]
Hi @spronay,

Sorry for not responding sooner! I've been out of town. 

Sending emails can be notoriously fickle, and depends a lot on the way your PHP and server has been configured. If the out-the-box emails don't get sent, I'd suggest using the Swift Mailer module that uses SMTP instead.
https://docs.formtools.org/modules/swift_mailer/

It's a much more reliable way to send emails. 

Ben
