### ISSUE TITLE
Failed query in _ft_cache_form_stats, line 1704

### ISSUE THREAD

**Issue by Rickcarlson103** [formtools/core#344]
I was trying to use "Operations" in MyPhpAdmin to "copy" an existing table into the form tools tables area.  I foolishly thought it was going to save me a lot of time.  I had started an ft_form_8 through formtools.  It had no data in it.  I tried to copy the structure and data but it said that ft_form_8 already existed so it would do it.  I therefore deleted ft_form_8.  I repeated the copy structure and data and it did so. Now when I go into formtools, I get this error. None of my forms appear any more.  I've obviously disrupted the ability of formtools to know what its tables are.  Can you tell me how to fix this?  Thanks!  The error message is:
Failed query in _ft_cache_form_stats, line 1704    
I do have a backup that would have the old formtools directory and contents in it so I could restore that but I have no idea if that's going to resolve anything as I didn't modify anything in formtools.  I modified the table mentioned above by deleting and replacing it.

**Comment by benkeen** [comment]
Thanks for posting the solution, @Rickcarlson103 & glad you got it figured out!
