### ISSUE TITLE
Problem wit FormTools 2.2.5 - no redirection of mails

### ISSUE THREAD

**Issue by Nemino** [formtools/core#352]
Hello!
I never worked with Form Tools before, but now I want to use an own form on a website.
So I installed FormTools from the site of my webhoster.
Than I "add form" at first and everything worked well without an error message.
Afterwards I edit this form and added an email with all settings like "Configuration", "Recipient(s)", "Content" and "Test". 
Everything works well. All messages, which I send from the form on my website will store on my account from FormTools. The problem is, that no message will redirected to the email(s) I defined at the settings?!
I have to log me in at FormTools to see if anyone has send me a message. 
What have I to do, that I will receive emails from the form on my website or isn´t it possible to redirect the messages? If not - why can I state one or more email addresses?
Thanks !

**Comment by benkeen** [comment]
Hi @Nemino, sorry for not responding sooner - been out of town!

Emails with PHP are notoriously fickle. Different hosting providers implement mail() differently and many prevent certain features (like sending multipart HTML/text content, or controlling the header fields). This is done to prevent people using the hosting providers to send spam. 

Anytime you run into trouble with the default email functionality in Form Tools you should look at the Swift Mailer module. That lets you tie it into your own SMTP host (e.g. gmail) to send emails. That's MUCH much more reliable and consistent. 
https://docs.formtools.org/modules/swift_mailer/

All the best!

Ben
