### ISSUE TITLE
Custom Display Formats upgrade issue

### ISSUE THREAD

**Issue by matsed** [formtools/core#360]
Hi,

I'm using the Custom display format "30. 08. 2011. 20:00"  "datetime:dd. mm. yy.|hh:mm" on the submission date in some forms. When testing the upgrade from 2.2.6. to 3.0.8. this field does not display any values in the form submissions or any other view in 3.0.8. but there are no problems with it in 2.2.6.

This is the setting in use:
SELECT * FROM `ft_field_type_setting_options` WHERE `ft_field_type_setting_options`.`setting_id` = 22 AND `ft_field_type_setting_options`.`option_order` = 14

Is this a bug? Thanks,
Mat

**Comment by benkeen** [comment]
Hmm, I'm not sure if this is a bug or not yet. In your upgraded FT installation, can you add a date in that field, save it & see the correctly saved date? Or does it always show nothing? 

Testing locally that particular custom display format works fine. But possibly there's an issue that only shows up for upgrading. Let me know about the above and I'll look further.

**Comment by matsed** [comment]
Hi, thanks for the fast reply.

I've added a new submission and it doesn't show up. Could it have anything to do with the php_processing field in ft_field_types table?

Thanks,
Mat

**Comment by Dtrieb** [comment]
Same Problem here in Version 3.0.4.

**Comment by benkeen** [comment]
k, thanks @dtrieb. I'll check this out in the next release (3.0.10). Clearly sounds like a bug.

**Comment by benkeen** [comment]
I'll release both the core + Custom Fields update tonight.

**Comment by benkeen** [comment]
Correction: _tomorrow_ night. Didn't quite get everything done. :)
