### ISSUE TITLE
Add description to form

### ISSUE THREAD

**Issue by ryanstubbs** [formtools/core#365]
Is there any way to currently add a description to the top of a form?

I'm currently using form builder with the latest version of Form Tools but it would be great to add an opening paragraph to a form.

**Comment by benkeen** [comment]
Sure, no problem! To do that, you'll need to add a new placeholder to the form. The documentation doesn't go into terribly much detail I'm afraid, but give this page a read:
https://docs.formtools.org/modules/form_builder/customization/anatomy/placeholders/

Here's a bit more detailed description on how to do it: 

1. In your Form Tools UI (as administrator) go here:
Modules -> Form Builder -> Edit template set (the one you're using) -> Placeholders tab. 
2. Click "Add Placeholder".
3. On the next field, add the following settings:
- `Placeholder Label`: Form intro paragraph
- `Placeholder`: intro_paragraph
- `Field type`: textarea
- `Default value`: (just leave blank)

Then click "Add Placeholder". At this point, you've basically created a new setting that users can fill in when creating/editing forms in the form builder. 
4. Now click on the `Templates` tab (we're still in the Form Builder, editing the same template set). The next step is to actually reference that placeholder in your templates so it displays something in the page. 

Edit the template that has "Form Page" as the Template Type. Templates can have any number of these, so you may need to edit multiple ones. Somewhere near the top, probably under the title, just add: `{{$P.intro_paragraph}}`

5. The final step is to actually add the text to your form. Go to Forms -> Edit Form (the one you want to edit) -> Publish tab and click the Edit icon row for the published form you want. Then, in the form builder dialog that appears, expand the "Placeholders" section in the left nav. If you're using the same Template Set you just edited, you'll see your new "Form intro paragraph" setting. Fill in some blurb and click "Apply Settings >>". Tada! 

Hope this helps!
