### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Inbroch** [formtools/core#366]
I am using cPanel and have created a new folder inside my publichtml folder called "formtools". I uploadede the zip file and extracted inside the formtools folder. i then copied all of the files from the formtools/nubuilder4-master folder to the formtools folder so that I could type in: investorhq.com.au/formtools and it would boot. It came back with a Error 500. I contacted my hosts and they said teh nuconfig.php file had the wrong settings in it.

I am new to this kind of thing and have followed the instructions but there isn't any instructions telling me what to configure my nuconfig file with before the "Welcome" part starts.

**Comment by benkeen** [comment]
Hey @Inbroch, 

I'm not quite familiar with how cpanel handles Form Tools. Does it lead you through the Form Tool installation process (a 6-step process with the green Form Tools header)? Also, by default Form Tools requires a `global/config.php` to exist, not a `nuconfig.php` file, so again I guess that's something specific to cpanel.

Perhaps give this page a look at. It specifies all the settings that can exist in the configuration file:
https://docs.formtools.org/userdoc/getting_started/config_file/

Normally, your file should look something like this: 

```php
<?php

// main program paths - no trailing slashes!
$g_root_url = "http://yourdomain.com";
$g_root_dir = "/path/to/yourdomainfolder";

// database settings
$g_db_hostname = "mysql.yourhost.com";
$g_db_port = "3306";
$g_db_name = "yourdbname";
$g_db_username = "yourdbusername";
$g_db_password = "pwd123";
$g_table_prefix = "ft_";

?>
```

Also, you might want to take a look at your PHP error logs. That'll probably contain some useful information about what precisely went wrong.

**Comment by Inbroch** [comment]
Firstly, "Thanks" for responding so quickly on a Sunday (here in Australia
anyway!)

No, literally, I extract teh files in teh folder, type in:
investorhq.com.au/formtools and don't get past that befoe it hits me with a
error 500.

I don't get any response at all. My host told me it was going to the
nuconfig file which shows this:

 $nuConfigDBHost                 = "127.0.0.1";
    $nuConfigDBName                 = "ihqops";
    $nuConfigDBUser                 = "root";
    $nuConfigDBPassword             = "";
    $nuConfigDBGlobeadminUsername   = "globeadmin";     //-- globeadmin
username
    $nuConfigDBGlobeadminPassword   = "nu";             //-- globeadmin
password
    $nuConfigTitle                  = "nuBuilder 4";
    $nuConfigIsDemo                 = false;
$nuConfigTimeOut              = 1440;
/*    $nuWelcomeBodyInnerHTML = "
<div id='outer' style='width:100%'>

<div id='login' class='nuLogin'>
<table>
<tr>
<td align='center' style='text-align:center;height:50px' colspan='2'>
<div id='nulogo' style='margin:50px 0px 20px 65px;background-size:100%
100%;background-image:url(\"graphics/logo.png\");width:200px;height:80px;'></div>
</td>
</tr>
<tr>
<td style='text-align:right;margin:0px 5px 0px 20px;'><span
style='padding:0px 5px 0px 40px;'>Username</span></td>
<td style='text-align:left'><input id='nuusername'/></td>
</tr>
<tr>
<td style='text-align:right;margin:0px 5px 0px 20px;'><span
style='padding:0px 5px 0px 40px;'>Password</span></td>
<td style='text-align:left'><input id='nupassword' type='password'
onkeypress='nuSubmit(event)'/></td>
</tr>
<tr>
<td style='text-align:center' colspan='2'>
<input id='submit' type='button' class='nuButton'  style='margin:20px 0px
0px 50px;width:90px;height:30px;' onclick='nuLoginRequest()' value='Log
in'/>
</td>
</tr>
</table>
</div>
</div>
";
*/
    if(array_key_exists('REQUEST_URI', $_SERVER)){
        if(strpos($_SERVER['REQUEST_URI'], basename(__FILE__)) !== false){
            header('HTTP/1.0 404 Not Found', true, 404);
            die();
        }
    }

?>

Any suggestions?

**Comment by benkeen** [comment]
Ah, thanks for the clarification! But I'm afraid I'm not sure I can help... sounds like your host was right: there's a problem with that config file & I'm afraid I don't know how cpanel works. If I were debugging it, I'd start with tracking down the PHP error log file, but beyond that you may want to contact your hosting provider again to see if they can provide a few more clues.

Sorry I couldn't be more help. Setting stuff up is always a pain...

**Comment by Inbroch** [comment]
Mate, no need for apologies, thankyou so much for responding on a
Sunday......I hope you

It's cool, I'll work it out eventually.

If ever you need some advice to do with property, happy to help FOC.

Good on you mate.

**Comment by Inbroch** [comment]
Why don't the instrcutions say about configuring the nuconfig first? I'm
not arguing it, just wondering if there's a step I'm missing that may have
been included since the webpage I'm looking at.

**Comment by Inbroch** [comment]
I worked out the problem mate. I'm an idiot was the problem. I was
uploading another open source package to my root folder. Have uploaded the
correct one now and on my way.

Again, a big "Thanks Mate" for your prompt reply.

If ever you want to invest in Australian property, I owe you a big one.

JA.

**Comment by Inbroch** [comment]
Do you know if it's possible to create subforms using Form Tools?
