### ISSUE TITLE
Add bootstrap to a theme

### ISSUE THREAD

**Issue by varbuzov** [formtools/core#367]
How would one add bootstrap to Formtools. i would like to make pages responsive. Tried adding stylesheet links to header.tpl (since it is used in all pages) but that did not pan out. Any suggestions?

**Comment by benkeen** [comment]
Hey @VladLandau, actually that's exactly how I'd go about it: make a copy of the default theme and modify however you wish. You can add in bootstrap JS + CSS there and modify the other templates to add the / convert the appropriate markup. How come it didn't pan out? 

Updating the UI is slated for FT 3.2, but that's still a ways off yet.

**Comment by benkeen** [comment]
I'm afraid I don't have much to suggest. This is just a question of getting the CSS + markup in your theme right. Sorry about that.
