### ISSUE TITLE
Subforms

### ISSUE THREAD

**Issue by Inbroch** [formtools/core#368]
Is it possible to create subforms in Formtools?

**Comment by benkeen** [comment]
Hey @Inbroch, 

Forms are pretty much just unique and largely unrelated at this point. What particular functionality did you hope to get? Like a section in a form that lets you add multiple records into a different form or something?

Ben

**Comment by Inbroch** [comment]
Hi Benand thanks for responding

Exactly that. I need  to relate records to most of my forms and with some,
have multiple records inside others.....like the way you have "Contacts"
within "Accounts" and also I have "Projects" which have "Stages" which have
"Tasks" which have "Sub Tasks".....and that's just the tip of the iceberg.

It's a shame as it's the best looking form I have been able to see but
without any programming skills (besides "Deluge" in Zoho Creator) I am
unable to create this model with Form Tools.

**Comment by benkeen** [comment]
Yeah, this would be really nice to have. But at this stage it's still under the "Feature Request" heading. Sorry about that!
