### ISSUE TITLE
FORM TOOLS CORE - ft_email_templates - missing column: view_mapping_view_id

### ISSUE THREAD

**Issue by sf23103** [formtools/core#371]
I just upgraded to 3.9.  When doing the system check, I am getting the error:
**FORM TOOLS CORE - ft_email_templates - missing column: view_mapping_view_id** when checking the Form Tools Core

**Comment by benkeen** [comment]
Hey @sf23103, huh! What version did you upgrade from? 

Glancing over the code, `view_mapping_view_id` has been a field in the `{prefix}email_templates` for a long while. I was wondering if maybe you were upgrading from a version earlier than Form Tools 2.2.5?

**Comment by sf23103** [comment]
Upgraded from 2.2.5 after updating the modules. I ended up having to revert back to 2.2.5 after updating to 3.0.9. None of my external forms would load. I posted that error in a separate issue.

**Comment by benkeen** [comment]
Thanks, @sf23103 - this was just reported by another user. I'll add a check in the next release to confirm the field exists and add it if it doesn't.

**Comment by benkeen** [comment]
Merged. Will be in next release.
