### ISSUE TITLE
 Fatal error: Call to undefined function ft_check_form_exists() in /home/path/to/ft/global/api/api.php on line 344

### ISSUE THREAD

**Issue by sf23103** [formtools/core#372]
Just upgraded to FT 3.0.9 and all of my external forms now show:  

Fatal error: Call to undefined function ft_check_form_exists() in /home/path/to/ft/global/api/api.php on line 344

**Comment by sf23103** [comment]
Just re-uploaded all of the files and am now getting a different error:  

Fatal error: Call to a member function prepare() on a non-object in /home/srpdv2/public_html/forms/global/code/Database.class.php on line 71

**Comment by sf23103** [comment]
I reverted back to 2.6, and then completed the entire process again.  I'm getting the same error message above on all of my external forms.  (Fatal error: Call to undefined function ft_check_form_exists() in /home/path/to/ft/global/api/api.php on line 344)

Here's the environment info: 

Form Tools Core Version: 3.0.9
Core Version Upgrade Track: unknown,2.1.5-main-20111022,2.1.8-main-20111107,2.1.9-main-20111206,2.2.1-main-20120206,2.2.3-main-20120423,2.2.5-main-20120503,2.2.6-main-20130629,2.2.5-main-20120503
API Version: 1.1.4
PHP Version: 5.4.45
MySQL Version: 5.5.61-cll
PHP Sessions: Available
Suhosin Extension: Not Installed
Curl Extension: Available
SimpleXML Extension: Available
____________________________________
MODULES (name, version, enabled)
Arbitrary Settings, 2.0.2, Yes
Client Audit, 2.0.2, Yes
Custom Fields, 2.0.1, Yes
Database Integrity, 2.1.1, Yes
Export Manager, 3.0.5, Yes
Extended Client Fields, 2.0.4, Yes
File Upload, 2.0.2, Yes
Google Maps Field, 2.0.2, Yes
Hooks Manager, 2.0.3, Yes
IP Security Check, 2.0.4, Yes
Media Gallery, 1.0.1, Yes
Pages, 2.0.6, Yes
Submission History, 2.0.4, Yes
Submission Pre-Parser, 2.0.4, Yes
Swift Mailer, 2.0.6, Yes
System Check, 2.1.3, Yes
TinyMCE Field, 2.0.7, Yes
____________________________________
THEMES (name, version, enabled)
Classic Grey, 1.1.2, Yes
Deep Blue, 1.1.2, Yes
Default, 1.0.0, Yes

**Comment by benkeen** [comment]
Good heavens, Alex! Great to hear from you! Hope things are going well. 

The upgrade package *should* have included the new API version, but it definitely sounds like an old version is the culprit. Quick test you could do is download the API manually from here:
https://github.com/formtools/api/releases/tag/2.0.0

Then just copy all the files into your /global/api folder (overwriting the old `api.php` file & adding a few others).

**Comment by sf23103** [comment]
All is well!  I’m so excited you’re back to FT. Don’t worry, I’ve been lurking just getting ready to do a bunch of upgrades. 

Ok I’ll do an API update and let you know how it goes. Thx for the response!

**Comment by benkeen** [comment]
btw, we figured this one out. The problem was that on his server the API form was instantiating the core twice (not his fault - it was set up properly), which caused the second instantiation to fail to read the config.php file which had been included via a `require_once` (so the second time did nothing). That then loaded up the config settings to all be blank, causing the error. 

I'll release a patch for this in 3.0.10.
