### ISSUE TITLE
Error without having made a change

### ISSUE THREAD

**Issue by mderouge** [formtools/core#374]
Following error message while accessing Formtools. No changed had been made recently 

Fatal error: Uncaught Error: Call to a member function prepare() on null in /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/Database.class.php:71 Stack trace: #0 /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/Settings.class.php(84): FormTools\Database->query('\n ...') #1 /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/User.class.php(50): FormTools\Settings::get(Array) #2 /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/Core.class.php(816): FormTools\User->__construct() #3 /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/Core.class.php(388): FormTools\Core::initUser() #4 /home/httpd/vhosts/derougemont.org/afb.triceno.com/index.php(15): FormTools\Core::init() #5 {main} thrown in /home/httpd/vhosts/derougemont.org/afb.triceno.com/global/code/Database.class.php on line 71

**Comment by benkeen** [comment]
Hi @mderouge, you're the third person who's ran into this in the last few days. Very worrying! 

So where do you see this? On the login page?

**Comment by mderouge** [comment]
Tank you for the feedback.
I got it as raw text when accessing the site, before any login. 
You may try : http://afb.triceno.com
(same with https)
It isn't neither op. system nor browser related. 
Best regards 
Michel de Rougemont 


____
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma plus ou moins longue brièveté.


-------- Courriel d’origine --------
De : Benjamin Keen <notifications@github.com>
Envoyé : 25 novembre 2018 19:16:58 GMT+01:00
À : formtools/core <core@noreply.github.com>
Cc : mderouge <michel.de.rougemont@mr-int.ch>, Mention <mention@noreply.github.com>
Objet : Re: [formtools/core] Error without having made a change (#374)

Hi @mderouge, you're the third person who's ran into this in the last few days. Very worrying! 

So where do you see this? On the login page?

**Comment by mderouge** [comment]
Hi Benjamin,

I tried, without any improvement.

Best regards

Michel

 

De : Benjamin Keen <notifications@github.com> 
Envoyé : lundi, 26 novembre 2018 01:28
À : formtools/core <core@noreply.github.com>
Cc : mderouge <michel.de.rougemont@mr-int.ch>; Mention <mention@noreply.github.com>
Objet : Re: [formtools/core] Error without having made a change (#374)

 

Hey  <https://github.com/mderouge> @mderouge,

Hmm, very worrying indeed. Would you mind trying a quick change?

Edit your global/code/Core.class.php file and look for the following string:

require_once(self::getConfigFilePath());

Try changing that to

require(self::getConfigFilePath());

This might be unrelated. It was just causing a similar issue on someone else's server, so I was curious to know if this was the cause here too.

**Comment by mderouge** [comment]
As surprise the site that came out of order without warning (hosted at a place where no other problems were experienced) is now functional again!
End of the story, at least for the moment
Thank you for your kind attention Benjamin!

**Comment by benkeen** [comment]
Haha no worries, thanks for following up. :)
