### ISSUE TITLE
Upgrade 2.2.5 -> 2.2.6 (Blank Screen)

### ISSUE THREAD

**Issue by flcowboy7** [formtools/core#407]
Attempting to get my cores updated to 2.2.6 before making the leap to 3.0.9. Download files, check. Unzip files, check. Log out of UI, check. Upload files, check. Refresh UI: BLANK.

I have tried this at least half a dozen times, but I always end up with the same result of a blank screen. For now, I've had to revert back to 2.2.5. Any clue why this might be happening?

Still running PHP 5.6.39. Actually was upgrading FT before upgrading to PHP 7.1. Maybe I should upgrade PHP first?

**Comment by flcowboy7** [comment]
I should mention, this particular install uses a custom directory: /formtools-name

**Comment by benkeen** [comment]
Hey @flcowboy7, 

Sorry you're having trouble! This doesn't sounds like a front-end (JS) problem - a blank page means some sort of server problem or PHP code execution problem. 

Odd... 2.2.5 to 2.2.6 was a pretty benign update, I think. But no, don't update to PHP 7 yet: Form Tools 2.x doesn't support it so if you do that before it definitely won't work. 

Could you check your PHP error logs to see if it gives us any clues? It may contain a helpful stack traces.

**Comment by flcowboy7** [comment]
Hi @benkeen -

Nothing there. :( I've even tried various browsers and clearing cache files. Still blank. If I revert back to 2.2.5 (using my backup - thank goodness!), the login screen shows up again with the message "successfully updated to 2.2.5".

I'm beating my head against the desk here.

**Comment by flcowboy7** [comment]
I just tried upgrading from 2.2.5 to 2.2.6 on a different domain (reseller vs dedicated server). I got the header across the top, but the rest was blank. The FireFox Console had the following to say, but still no PHP error log:

`
TypeError: document.login is undefined[Learn More] formtools:29:16
<anonymous>
https://ripnote.com/formtools/:29:16
resolveWith
https://ripnote.com/formtools/global/scripts/jquery.js:16:13113
ready
https://ripnote.com/formtools/global/scripts/jquery.js:16:9257
A
https://ripnote.com/formtools/global/scripts/jquery.js:16:15073
`

**Comment by flcowboy7** [comment]
Even more odd - on the first domain (where I got the totally blank page), once I reverted to 2.2.5 I ran the Orphan Clean-Up from the System Check Module (v1.0.3), but ti never completed. It gets this far, but then never gives me a success message:

TABLE: ft_email_template_when_sent_views
Test description: 
Checks for records mapped to now-deleted email templates and Views.
Results:
- num tests: 6
- num orphans: 0

**Comment by flcowboy7** [comment]
Here are the environment variables for the first domain (blank page after upgrade):

Form Tools Core Version: 2.2.5
Core Version Upgrade Track: 2.1.8,2.1.9-main-20111206,2.2.0-main-20111231,2.2.1-main-20120206,2.2.2-main-20120301,2.2.3-main-20120423,2.2.5-main-20120503,2.2.6-main-20130629,2.2.5-main-20120503,2.2.6-main-20130629,2.2.5-main-20120503
API Version: 1.1.4
PHP Version: 5.6.39
MySQL Version: 5.6.41
PHP Sessions: Available
Suhosin Extension: Not Installed
Curl Extension: Available
SimpleXML Extension: Available
____________________________________
MODULES (name, version, enabled)
Core Field Types, 1.0.2, No
Export Manager, 2.1.1, Yes
File Upload, 1.1.0, Yes
Pages, 1.2.6, Yes
Submission History, 1.1.5, Yes
Submission ID Manager, 1.1.1, Yes
Submission Pre-Parser, 1.1.4, Yes
Swift Mailer, 1.1.2, Yes
System Check, 1.0.3, Yes
TinyMCE Field, 1.0.8, Yes
____________________________________
THEMES (name, version, enabled)
Default, 1.0.0, Yes

**Comment by flcowboy7** [comment]
Hi @benkeen -

Rather than investigate the table verification issue further, I opted to upgrade to 3.0.9. The most beautiful message I've seen all week?

"Your installation has been upgraded to 3.0.9"

However, the table verification is still not running. (Or it's taking an exorbitant amount of time). Should I be concerned about this? Or should I go ahead and upgrade the PHP version once I've gotten this far for all of my installs?

The only other issue is that the message regarding the Core Field Types module is still present, even after uninstalling the module and deleting the folder from the server. Shouldn't that have gone away when I deleted the folder?

**Comment by flcowboy7** [comment]
Oh dang - I didn't realize I was going to have to change the code in all of my API forms....! They're all broken now :(

Trying to follow along with the new API tutorial (https://docs.formtools.org/api/v2/). It says that once the new code is added to the form it should just work. But - it doesn't. It's throwing undefined function errors at me now.

**Comment by flcowboy7** [comment]
Sorry for the constant comments. Just trying to provide info as I get it. Attached is a copy of the PHP on a basic API form (obfuscated for security reasons). I added the new API.class.php call and the $api object. In theory - the form should just 'work" now, right? Very first error: 

Fatal error: Call to a member function prepare() on null in /home/user/public_html/formtools-name/global/code/Database.class.php on line 71

[api-form.zip](https://github.com/formtools/core/files/2696359/api-form.zip)

**Comment by flcowboy7** [comment]
Hi again @benkeen -

I updated the /global/code/Core.class.php file as per your suggestion here: https://github.com/formtools/core/issues/374#issuecomment-441488035

The form is now submitting properly.

**Comment by flcowboy7** [comment]
@benkeen problem with SwiftMailer was with my browser cache. I had apparently logged in to another FT install with the same browser and it was mucking up the SMTP settings.

**Comment by flcowboy7** [comment]
Also - the new code to use to start an API form:

`require_once("../formtools-uscra/global/api/API.class.php"); // FT 3.0.9`
`$api = new FormTools\API(); // FT 3.0.9`

It isn't necessary for existing forms, right? I thought I needed to append all my old forms, but it appears they all work without that added code. They still use:

`require_once("../formtools-uscra/global/api/api.php");`

**Comment by benkeen** [comment]
Hey @flcowboy7,

I'm really so sorry I haven't had time to help out this last little while, it's been very busy here.

If you're still encountering this issue on your API form:

> Fatal error: Call to a member function prepare() on null in /home/user/public_html/formtools-name/global/code/Database.class.php on line 71

Try making this small change. Edit your `global/code/Core.class.php` file and on line 457 change this:
```require_once(self::getConfigFilePath());```
to:
```require(self::getConfigFilePath());```

See if that solves it. This fix will be in 3.0.10, but additional confirmation is welcome!

> ... It isn't necessary for existing forms, right? I thought I needed to append all my old forms, but it appears they all work without that added code. 

Actually, instantiating the API *is* required, so I'm a little puzzled why that's working... are they just one-page forms? That might explain it.

Again, sorry for not being around - I have a couple more busy days before I can really get back to FT but I'll try to help out your other issues.

**Comment by flcowboy7** [comment]
Everything is working now except the Table Verification. Yes, they are all single-page forms. So, you're saying that if they were multi-page forms, I would need both the OLD API call AND the NEW API calls?

**Comment by flcowboy7** [comment]
@benkeen - Only thing left on this issue is the OP - blank screen when upgrading from 2.2.5 to 2.2.6. Not sure if it's worth a bug or not. Maybe just tell people on the docs to upgrade from 2.2.5 to 3.0.0 first, before upgrading to 3.0.9? (Which is what I ended up having to do).

**Comment by benkeen** [comment]
Hey @flcowboy7! Yeah, the blank screen on 2.2.5 to 2.2.6 is still a puzzler for me. I've really pretty sure that's a perfectly fine update to do, so no, I won't post about it. I think it's fine people upgrade to that version, I don't know what happened on your server. 

And now 3.0.10 is released, the two issues you spotted - the table verification problems (due to your DB name) and the API form throwing that error - are now both fixed, so again I'm fine people upgrading directly from FT2 to the latest FT3 version. 

That said, I *should* point out that upgrading from 2.2.5 to 3.x was fine.

Thanks very much for your help in the forums, btw!

**Comment by flcowboy7** [comment]
Anytime @benkeen! It's been a hot minute, for me, too. But I'm getting the hang of this whole Github thing, I think :)
