### ISSUE TITLE
Core Field Types - Remains after uninstall

### ISSUE THREAD

**Issue by flcowboy7** [formtools/core#409]
Upgrading from a 2.x version to a 3.x version of FT core. The modules screen says:

"This module is no longer needed in Form Tools 3. Please uninstall the module, then delete the /home/user/public_html/formtools-name/modules/core_field_types/ folder on your server."

After uninstalling the module and deleting the folder from the server, the message remains on the Module screen. Tried clearing browser cache, logging out and logging back in. Still there. Doesn't seem to be causing any problems, so just a cosmetic issue.

![image](https://user-images.githubusercontent.com/42279189/50252069-d0493a00-03b3-11e9-917c-2172c6aa8447.png)

**Comment by benkeen** [comment]
Ah yeah, don't worry about it - you're fine. After deleting the `modules/core_field_types` folder as you've done, just click the Refresh Module List button at the bottom of that page. That should remove it, no?

**Comment by flcowboy7** [comment]
Ha ha ha - I didn't even see that there. Feel free to mark this as closed....lol.
