### ISSUE TITLE
Export Manager Error

### ISSUE THREAD

**Issue by Trefilov22** [formtools/core#413]
Just installed formtools and have some data entered into my DB.  Trying to export the data to an Excel spreadsheet.  I went to the module section to check to see if the Export Manager module is installed, and it is not.  I try to install it, and get the following error:

There was a problem installing this module. There was a problem creating the tables/data for this module. Please report the following error in the forums:  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'ft_module_export_groups' already exists
--

Any suggestions on how to fix this issue?  Thanks!

**Comment by benkeen** [comment]
Hmm! Either the installation half-installed the Export Manager module & now it's in a sort of limbo state, or your database contains the table by other means... Did you encounter any problems during the installation process? And what version are you installing - 3.0.9? 

A quick fix would be to simply go into your database (do you have phpMyAdmin access?) and remove these tables:
```
ft_module_export_groups
ft_module_export_group_clients
ft_module_export_types
```

Those are the DB tables used by that module.

**Comment by Trefilov22** [comment]
Ben,

Yes I am using 3.0.9.  I didn't have many records in the DB, so I just started from scratch and it is working fine now.  Thanks for the info though, I will keep this for down the road!

Merry Christmas!
Brian
