### ISSUE TITLE
force https:// messes up form tools display and functionality

### ISSUE THREAD

**Issue by HarborSide** [formtools/core#426]
Last week, we secured our site https:// And now the view is all messed up. This occurs when you paste force https:// script onto the .htaccess file. 

# HTTPS Redirect
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
# HTTPS Redirect

Is there some scripting l might use for form tools to correct this issue?
HarborS

**Comment by benkeen** [comment]
Hey @HarborSide, that should be fine! 

Did you check your `global/config.php` file to ensure the `$g_root_url` setting includes https instead of http?

**Comment by HarborSide** [comment]
YES!! Thank you. That worked. Please close this ticket.
HarborS

**Comment by flcowboy7** [comment]
@HarborSide - You should be able to close tickets you started by clicking the "Close issue" button at the bottom of the page (below the comment field). It's next to the Comment button.
