### ISSUE TITLE
Upgrading 2.0.4 -> 2.2.6 -  Server Timeout

### ISSUE THREAD

**Issue by brantleyenglish** [formtools/core#450]
Hey I'm trying to upgrade formtools before our webserver for [harrisonfireprotection.com](http://harrisonfireprotection.com/) switches to php7. First I will upgrade to 2.2.6 and then to 3.0.10 (hopefully).

After logging in, when I click the 'update' link in the top right corner:
![alt text](https://sh-drop.s3.us-east-1.amazonaws.com/be/Screen%20Shot%202019-01-17%20at%201.33.00%20PM.png)
I am redirected [here](https://formtools.org/upgrade/?m=2.0.4&beta=&api=1.0.1&t1=classicgrey&tv1=1.0.9&t2=deepblue&tv2=1.0.8&t3=default&tv3=1.0.0&m1=export_manager&mv1=1.0.3&m2=pages&mv2=1.1.3&m3=swift_mailer&mv3=1.0.4).

After selecting x2.2.6 core/modules and clicking download, the server begins timing out and redirects to this page:
![alt text](https://sh-drop.s3.us-east-1.amazonaws.com/be/Screen%20Shot%202019-01-17%20at%201.37.10%20PM.png)
I have been getting this server time error for the past three days with no luck. Am I going through the correct process to update formtools?

Any help will be much appreciated. Thanks!

**Comment by benkeen** [comment]
Going to close this now. It appears to be working fine.
