### ISSUE TITLE
File Upload Error

### ISSUE THREAD

**Issue by benib596** [formtools/core#453]
Hi After upgrading the file upload module it change the language of the particular module.

Kindly check.

**Comment by benkeen** [comment]
Hey @benib596, thanks for letting me know. Your interface is in English? What language does the module appear in? Is it just within the module section or in your form as well?

**Comment by benib596** [comment]
Hi Ben.

Yes it is only inside that module and something like Hebrew language.  Not
sure.

Ben

**Comment by benkeen** [comment]
Will fix with that other ticket. Closing.

**Comment by benkeen** [comment]
This was patched in 2.1.1 of the module.
