### ISSUE TITLE
clean installation latest version - http 500 error. 

### ISSUE THREAD

**Issue by eternity575** [formtools/core#454]
Clean installed it on my site www.hasorkim.co.il/m ...
no matter what directory i go (install/root) i get http 500 error.
any help would be appreciated.
thanks!

**Comment by benkeen** [comment]
Hi @eternity575, sorry you're having problems! Are you seeing this during the installation step, or after having installed it? 

Also, are you using PHP 5.3 or later? 

Maybe try adding this to your `global/config.php` file to see if it outputs any handy error messages to the screen:

```php
$g_default_error_reporting = 2047;
```

Failing that, take a look at your PHP error logs to see if it provides any helpful information.

**Comment by eternity575** [comment]
darn it... php version 5.2.2.. ill ask my host about it.. any workaround?

**Comment by eternity575** [comment]
my host switched me to 7 in a second.. but it messed my old email web client...
know any new open source ones? lol
thanks!

**Comment by benkeen** [comment]
haha no problem. Good luck finding a new web client... ;)

**Comment by Patdaman1** [comment]
my server is using 7.2.7 of php i cant when i go to the root i get The requested URL /index.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by igipess** [comment]
Error HTTP ERROR 500 - when click on Publish tab.
