### ISSUE TITLE
Version 3.0.12 - Manual.html issue

### ISSUE THREAD

**Issue by Yannick45** [formtools/core#459]
Updating to version 3.0.12 i'm not able via ftp to upload the following file : \global\codemirror\doc\manual.html. I tried to do it and i get an error with a file 0 octet. In addition doing this My computer shuts down when trying several times. It seems to have a violation somewhere. It only occur with the file mentioned.
Best regards,

**Comment by benkeen** [comment]
Hi @Yannick45, I took at look at the file but there's nothing special about it - it's just a regular HTML file. I'm not sure why it would cause any problems on your system, but I'm pretty sure it's unrelated to the computer errors you're seeing. Perhaps try just FTing that one file separately to confirm it's not the issue. More likely it's a problem with the FTP client you're using, or perhaps running out of memory?

**Comment by Yannick45** [comment]
Hi @benkeen,  I used another way to transfer the file and it worked properly. So, I would assume it was a problem with my FTP client. Thanks a lot for your help.
