### ISSUE TITLE
New versions of modules don't update their desc in the DB

### ISSUE THREAD

**Issue by benkeen** [formtools/core#460]
Huh! Never spotted until now, but this bug has probably been around since the dawn of time. I noticed when updating the description blurb for the File Upload module the upgrade didn't show the new text.

Very minor, but should be fixed in 3.1.0.

**Comment by benkeen** [comment]
This is a result of the module description actually being pulled from the LANG file and not the module. This is confusing. 

I think it makes most sense to drop the field from the DB altogether & just reference the appropriate value from the lang file dynamically on page load.

**Comment by flcowboy7** [comment]
May need to re-open this on 3.0.15.


Module Description | Notice:  Undefined index: description in /home/[user]/public_html/formtools/cache/9c0a8dd1f3c4d06a0393948a9aa20a9efa61303d_0.file.about.tpl.php on line 51

9c0a8dd1f3c4d06a0393948a9aa20a9efa61303d_0.file.about.tpl.php on line 51 =
<td class="pad_left_small"><?php echo $_smarty_tpl->tpl_vars['module_info']->value['description'];?>
