### ISSUE TITLE
Error creating a form

### ISSUE THREAD

**Issue by luisdamo** [formtools/core#461]
Form Tools Version 3.0.12
php 7.3

The error message is:
Error: Invalid JSON: 
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\formtools\global\code\Files.class.php on line 280
{"2":"test1"}

When I try to edit a field,nothing appears in the second tab, Options, just a 'loading..' message, and nothing in the third tab too.

**Comment by luisdamo** [comment]
Solved downgrading php 7.3 to php 7.2

**Comment by benkeen** [comment]
Hey @luisdamo, thanks for this. Yeah I patched it in the upcoming 3.1 branch, but I'll also patch it in the 3.0.x branch with the next release. You should certainly be able to run PHP 7.3+. 

Thx!

**Comment by luisdamo** [comment]
Thanks, @benkeen

**Comment by benkeen** [comment]
Closing. Will be in 3.0.13 release.
