### ISSUE TITLE
Request to Reopen: Server Busy - Can't Download Updates

### ISSUE THREAD

**Issue by john-m-adams** [formtools/core#463]
Please reopen issue #208, for a new case of the identical issue:

### Server Busy - Can't Download Updates #208 

Thank you!

Note, Similar Closed issue here:
### Upgrade to 3.0.1 - no zipfile generated, server busy #434

**Comment by benkeen** [comment]
Thanks! I just made a temporary fix right now so it should work again in the short term. I'll look into a longer term fix.

**Comment by john-m-adams** [comment]
Thank you!
