### ISSUE TITLE
[help] adding some private code to "Review Page"

### ISSUE THREAD

**Issue by stfour** [formtools/core#474]
Dear all, I'm really happy with form tools, everything works great. I need help as I like to add a my own script in the "Review page" but it isn't clear to how to do it. Basically I have in the form some checkboxes where user can "check" some payments (ex. 1st 500.0 euro, 2nd. 250, 3rd 100 and so on). In "Review page" I want to show the sum of checked items.
I think I should "create" a placeholder and put it in the page, but I've no idea how and where do it.
Someone is so kind to take me on the right way ?
Thank you in advance
Marco (stfour)

**Comment by stfour** [comment]
Ok, After studying how things works, I'm now quite sure this is an useless question. It can be done directly in template using smarty. You can close this "request" ;)

**Comment by benkeen** [comment]
Glad you figured it out! Thanks @stfour.
