### ISSUE TITLE
Letter Only Validation

### ISSUE THREAD

**Issue by ncanqn** [formtools/core#482]
Hi Ben,
During testing I found that Letter Only Validation does not accept space. I would like to use this to validate name or any letter only box.
Do you think it should accept space?
Regards,
Ken

**Comment by benkeen** [comment]
Hey again! Fair question... I'd say no, it should only accept letter like right now, but I understand that you may want spaces too. 

To do that, you can again use the Custom Fields module (see details in my other response) - you can customize the validation rules however you want.

**Comment by ncanqn** [comment]
Thanks for your instruction Ben.
I will customise it. I am very excited about this tool.
Regards,
Ken

**Comment by MayaV369** [comment]
> Hey again! Fair question... I'd say no, it should only accept letter like right now, but I understand that you may want spaces too.
> 
> To do that, you can again use the Custom Fields module (see details in my other response) - you can customize the validation rules however you want.

Hi ,

Can you share the details and url of the your response ? I am having the same issue

Thanks
