### ISSUE TITLE
Custom field, user name. - fixed with FT 3.13

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#484]
Somebody have any idea how can I create a field that will be automatically filled with the name of login user?
thanks in advance

**Comment by ncanqn** [comment]
Hi @nelsondcosta23,
This is what I am looking for as well. I would get the login username to identify the person who submits the form.
Based on my understanding, this can only be archived with AD/LDAP integration or web service must run under Windows with Integrated Authentication to be able to pickup the system variables.
Correct me if I am wrong.
Cheers.

**Comment by nelsondcosta23** [comment]
Here :)

https://docs.formtools.org/userdoc/views/main_tab/

Since version 3.0.13 of the Core, you can also enter the following placeholders. These work for any Form Tools user account (admin or client) and will have their values replaced with their content.

{$ACCOUNT_ID}
{$USERNAME}
{$EMAIL}
{$FIRST_NAME}
{$LAST_NAME}
