### ISSUE TITLE
Placeholders for multiple file upload fields

### ISSUE THREAD

**Issue by benkeen** [formtools/core#487]
As per Nelson's comments in #300, check the placeholders for the file uploads (and documentation).

```
<td><a href="{$FILEURL_anexos}">{$FILENAME_anexos}</a></td>
```

**Comment by benkeen** [comment]
I have a pretty decent fix this this. 3.0.14 will introduce a `{display_files}` Smarty method which can be called from any email template (text/html) and output the file or list of files in whatever format that's needed: filename, filename with link, full URL, plus full control over delimiters. Should get 3.0.14 out very soon.

**Comment by nelsondcosta23** [comment]
wow nice :)

**Comment by benkeen** [comment]
Yeah it's been a crazy few days with work but I'm hoping to get 3.0.14 out tomorrow night that'll include this fix. I just have 1 more doc page to write.

**Comment by benkeen** [comment]
Hey @nelsondcosta23, the email templates have been updated with 3.0.14 (just released) to include a smarty function to handle rendering the single/multiple files properly. It'll work out the box, but here's a page explaining the function:
https://docs.formtools.org/userdoc/emails/displaying_files/

**Comment by nelsondcosta23** [comment]
I ll test today :)
