### ISSUE TITLE
System Check MySQL FAIL

### ISSUE THREAD

**Issue by darusdp** [formtools/core#488]
When doing the FormTools install at step 2 I get:

PHP Version | 7.1.26 | PASS
PDO available | Yes | PASS
MySQL available | Yes | FAIL
PHP Sessions | Available | PASS
Write Permissions | /upload/ | PASS
                              | /themes/default/cache/ | PASS

The MySQL is available but fails. There is no option to ignore.
I was able to start the FormTools install so I think Web server, PHP is setup well enough. Set read/write perms on /themes/default/cache/

My environment:
Windows 10 Enterprise (I have admin right to desktop)
Mongoose Web Server 6.9
MySQL 8.0.15.0
	create user username@localhost identified by 'password';
	grant all privileges on * . * to username@localhost;
	FLUSH PRIVILEGES;
PHP 7.1.26 VC14 x64
FormTools 3.0.13-20190224

Thanks!

**Comment by darusdp** [comment]
I got passed this part by doing the following in the PHP.INI file and restarting the web server.
		extension_dir = "ext"
		extension=php_pdo_mysql.dll

Hopefully all goes well going forward.

**Comment by benkeen** [comment]
Thanks for the heads up @darusdp - and the workaround in your case!

**Comment by poggdogg** [comment]
Ubuntu:
sudo apt-get install php-mysql
Probably similar in other distros.
