### ISSUE TITLE
Fatal error: require(): Failed opening required ...

### ISSUE THREAD

**Issue by lolekbolek20** [formtools/core#491]
Greetings! 

When I try to open our site http:/mydomain.com/index.php, I have an error from various PCs and in various browsers: 

Fatal error: require(): Failed opening required '/home/election/public_html/ftools/vendor/composer/../ramsey/array_column/src/array_column.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/mydomain/public_html/vendor/composer/autoload_real.php on line 66 

autoload_real.php has this:

65    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
66        require $file;

This error appears periodically, sometimes a few times a day, so the site is inaccessible, but then it clears and the form (and the site) is accessible again until the next hiccup.

I saw online some suggestions to run "composer update", but I am not sure how to do that or whether that would fix it at all. Could you help me?

**Comment by benkeen** [comment]
Hey @lolekbolek20, what version of Form Tools are you using? 

The fact that it occurs erratically is really very strange. If it occurred all the time I'd understand it, but now and then is most peculiar... 

You're not using a load balancer for the Form Tools instance? i.e. have it installed on two different servers, but use the load balancer to load it from different servers?

**Comment by lolekbolek20** [comment]
Thank you for the quick reply, Ben!

We are hosted by an ISP, so I don't know whether they use a load balancer for our domain, but I will ask.

So far, what I had from them is:

"While analyzing the error log i could see that your php code attempting to access a file outside your home directory and failing to access it and that is why you are getting the error message.

The file "/home/election/public_html/ftools/vendor/composer/../ramsey/array_column/src/array_column.php" is placed outside your home directory (/home/mydomain) and your user (mydomain) currently don't have access to it. 

Could you please consider reviewing your php coding ? "

So, one unknown is why this happens sporadically, and I will check that with our ISP, while the second unknown is why this happens at all.  If you have an idea as of a script to run/permissions to change/file to move, perhaps that will fix out problem and it won't re-occur sporadically or otherwise?

**Comment by benkeen** [comment]
Yeah, interesting response... `
"/home/election/public_html/ftools/vendor/composer/../ramsey/array_column/src/array_column.php" is placed outside your home directory`? Presumably /home/election is your home directory, so that's fine: the relative path in the middle of the full path is a little odd, but it would still be well within your home directory. 

And then like you said, that still doesn't explain the problem occurring off and on. I'm afraid I don't have much to suggest beyond asking them for more info... I still don't see any problem with the code here. Sorry about that!

**Comment by lolekbolek20** [comment]
You were right, Ben.  My ISP said:

This was a bug on php version your website was using before. We have used the same version but a custom compiled php for your website.

So, it was something at their end and (I hope) they fixed it.  Thank you for your advice!

**Comment by benkeen** [comment]
Ah nice! Glad I could help.
