### ISSUE TITLE
How to hide a View Field Group from customers?

### ISSUE THREAD

**Issue by lolekbolek20** [formtools/core#498]
Greetings,

In Form Builder View, I have two groups.  A bigger one for our customers to fill out and a smaller one for internal use by our staff.  Both field groups are showing on the web page when customers access it.  How can I hid the second group?

**Comment by benkeen** [comment]
Hey @lolekbolek20,

Field groups are bound to the View, so anyone that accesses the view will see the fields are you have arranged them. Sounds like you may need to create a second View containing for your customers that doesn't include the internal staff-only fields. Are you using the Form Builder? If so, you'd just edit the Form Builder form to use that new View instead.

**Comment by lolekbolek20** [comment]
Beautiful, Ben!

I created a Customer view and it only shows some fields and not all, just what we needed!
