### ISSUE TITLE
Upgrade version 2.2.6 to 3.0.13 modules area not working

### ISSUE THREAD

**Issue by AdStaak** [formtools/core#502]

**Comment by AdStaak** [comment]
I downloaded the .zip and merged it over my existing version. The new core seems to work, butthe modules tab does not work.

I downloaded a new zip for the modules (it recognises the new core) and merged it, but that did not help. Biggest problem is that my published forms as published by the form_builder module do not work any more!

**Comment by AdStaak** [comment]
This issue is still open.

**Comment by benkeen** [comment]
Hey @AdStaak, yes, I'm afraid that will need you to republish all your Form Builder forms as described in the red box here: https://docs.formtools.org/upgrading/3_0_0/

That should fix your forms.

**Comment by AdStaak** [comment]
Shouldn't the module section work for that in the first place?

**Comment by benkeen** [comment]
Oh I see! Did you remove your `[form tools]/modules/core_field_types/` folder? I think that can cause the modules page to not load.

**Comment by AdStaak** [comment]
Just read this following your link, sounds hopefull.. wait a minute..

**Comment by benkeen** [comment]
No worries - sorry for the lousy doc on that page, it's not at all easy to follow. Been meaning to update it for ages, just hasn't happened yet.

**Comment by AdStaak** [comment]
I deleted the [form tools]/modules/core_field_types/  folder and I logged in as admin, but my "modules" button at the left still shows a blank page.

**Comment by benkeen** [comment]
Hmm, rats, that was by far the most likely cause of this. 

Other things to try:
- What theme are you using? If it's not the default, could you try switching to the default theme for your admin user? Just want to rule that out. 
- clear the themes `[form tools root]/theme/[theme folder]/cache` folder (you can just delete anything in it) just to ensure Smarty hasn't cached the blank page. 

If neither of those work, time to go debugging:
- in your `global/config.php` add in this line 
```
$g_default_error_reporting = 2047;
```

Then go back to the Modules page and see if you see error output on the screen. 

- Lastly, failing all that you'll need to go to your PHP error logs on your server to see what - if any - errors are being thrown.

**Comment by AdStaak** [comment]
Before doing that, I just noticed that my synchronisation also wants to delete serveral folders in  formtoos/admin/modules/ 

I might have resynchronised some modules folder to the wrong spot before,
so I'm no removing those folders now first...

My local copy to be synchronised is now my previous version with the update on top and that folder removed. To be continued..

**Comment by benkeen** [comment]
Ok good luck! I'm going to be away for a couple of hours. Do hope it gets resolved easily!

**Comment by AdStaak** [comment]
Thanks,

I deleted the cache files for the default theme I'm using.
I added the debug flag, but execution does not get that far yet:

The page shows a http error 500 now. 

Currently my server runs on php5, I will try php7.1 now (for which I had to upgrade in the first place).

I will look for error logs or how to enable those on my server (provider),

**Comment by AdStaak** [comment]
php7.1 is running now on my server, and formtools core is still ok (as expected),
but the same problem exists with the modules section.
I added some echos for debugging in the modules/index.php and they show up fine,
the debug flag that i added does not show any results yet.
My chrome developer mode does not give any clues yet in the console,
I am looking for the php debug option at my provider now...

**Comment by AdStaak** [comment]
Log file found: A file can not be found, that's in the folder I removed?
I will look in the update package if it's there (

[Sun Mar 10 19:16:25.760798 2019] [proxy_fcgi:error] [pid 16570:tid 140697483044608] [client 84.29.39.151:55772] AH01071: Got error 'PHP message: PHP Warning:  require_once(/home/ruudsmus/domains/polkafest.nl/private_html/formtools/modules/**core_field_types**/library.php): failed to open stream: No such file or directory in /home/ruudsmus/domains/polkafest.nl/private_html/formtools/**global/code/Modules.class.php** on line 729\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/home/ruudsmus/domains/polkafest.nl/private_html/formtools/modules/core_field_types/library.php' (include_path='.:/usr/local/php71/lib/php') in /home/ruudsmus/domains/polkafest.nl/private_html/formtools/global/code/Modules.class.php on line 729\n', referer: https://polkafest.nl/formtools/admin/forms/

**Comment by AdStaak** [comment]
no such code in the update package (as expected).

Line 729 says:
        require_once("$root_dir/modules/$module_folder/library.php");

so the variable $module_folder is not correct.


The debugging of file modules/index.php shows that this is the section from which there is no return:

// Hacky patch. Longer term plan, see: https://github.com/formtools/core/issues/82
if (Core::$user->getLang() !== "en_us") {
    $overridden_modules = array();
    foreach ($modules as $module_info) {
        $module = Modules::getModuleInstance($module_info["module_folder"]);
        $module_info["module_name"] = $module->getModuleName();
        $module_info["description"] = $module->getModuleDesc();
        $overridden_modules[] = $module_info;
    }
    $modules = $overridden_modules;
}

**Comment by AdStaak** [comment]
I will wait for you suggestion now before I continue trying something myself.

It is about 8 pm in NL now, time to call it a day. At tuesday 8pm I might find some time to continue on this issue. 

Many thanks for the help, I will review the Dutch strings for you on success!

**Comment by benkeen** [comment]
Thanks, help with the translations would be great. :) 

But regarding your problem, I'm genuinely puzzled. My hunch is that this is either caused by some old files being cached or the files weren't all uploaded from the 3.x zipfile. Looking over the code, I don't see how your problem would occur... There's nothing in the 3.x code that I can see that tries to import anything from that folder: all it does it get the list of modules from the DB to include (core_field_types was never strictly a "module", it didn't have an entry in the `modules` table), then include them. 

Drat, wish I could offer some advice but at this point I think it may have to be debugged directly. If you're royally stuck, email me at ben.keen@gmail.com and I can help debug it on your server.

**Comment by AdStaak** [comment]
My database area ft_modules has an entry for core_field_types (author Encore Web Studios) though!
(origin language en_us) It has a description in the database:

This module contains all the default field types available for your forms: input fields, textareas, radios, checkboxes, dropdowns, multi-select dropdowns, phone number fields, dates, times, and code/markup fields. This module cannot be uninstalled.

I can edit the database directly if required...

**Comment by AdStaak** [comment]
That tedule could not be uninstalled before, and is not a module any more (probably for that reason) in version 3  (and it's code is probably situated elsewhere).

So I guess I can delete this module entry from the database directly... I will wait for your advise...

**Comment by benkeen** [comment]
There's an entry for it in your ft_modules table? My mistake... I didn't think it was logged there. But yes, if you see if there you can safely just remove the row in the table.

**Comment by AdStaak** [comment]
It works! The module page shows up now.
Deleting the entry for core_field_types in the ft_modules table finally did the job.
I was able to update all my modules now.
I recreated my forms with the new Form Builder module and all my forms are back again!

Thank you for your great support!
