### ISSUE TITLE
Is there a limit to number of fields?

### ISSUE THREAD

**Issue by rlohuis** [formtools/core#519]
I tried to add fields to a new form.
After about 80 - 90 fields, i can not add more.
I get an error: The form field 'product_category' could not be added.
Tried it with multiple forms, on different systems (Ubuntu, Arch, with Mysql, MariaDB, and PHP 7.2, 7.3)
Is there a limit to the number of fields?

**Comment by benkeen** [comment]
Hi @rlohuis, no there's no limit, but MySQL has a limit on the total size of all VARCHAR fields in a database table. Try adding a field with `Large` or `Very Large` as the field size and see if that works.

Form Tools should detect if you're about to run out of VARCHAR size and warn you, so let me know if it works or not and I'll log this as a bug if so.

**Comment by rlohuis** [comment]
Hi @benkeen, Thanks for your answer.
You are correct, adding fields with Large or Very Large as the field size works.
Although i did not see a warning.
Thanks again, problem solved!

**Comment by rlohuis** [comment]
Hi @benkeen, I think i was a bit too optimistic a few days ago.
Now after adding about 20 extra fields i run into the same problem. I even changed all fields to Large.
With no results.
I am stuck at 113 fields. 
I could provide an SQL export if that would help in locating the problem

Any way thanks in advance for any help!

Raymond

**Comment by crsleeth** [comment]
Were you able to solve this? I am unable to add fields after 118. I imagine I will need 200+ fields so I'm hoping you have a solution. I'm using MairaDB version 15.1 through Ubuntu 18.04's repos.

**Comment by rlohuis** [comment]
Hi @crsleeth 

I solved my problem by setting max_input_vars = 4000 in php.ini.
Now i have over 250 fields and did nut run into problems again.

Hope this helps you!

**Comment by crsleeth** [comment]
Thanks!! I changed all fields to TEXT as a temporary fix but I'll edit the php.ini like you suggest if I run into it again.
