### ISSUE TITLE
Dropdown filed showing blank values

### ISSUE THREAD

**Issue by pererjancar** [formtools/core#520]
Dropdown field created as Form Field content (using data from submissions from another form) showing blank values at the top of dropdown even there is no such data in source table.

![image](https://user-images.githubusercontent.com/48955271/55195198-19c3d500-51ac-11e9-817c-4012d40615a0.png)

**Comment by benkeen** [comment]
Hey @pererjancar, this definitely looks like a bug. Is your form an external form?

**Comment by benkeen** [comment]
This will technically introduce a breaking change, but I'll document it. For people who need a blank entry, they can choose to enter a field with spaces or a "----" string or something.
