### ISSUE TITLE
Update all themes for new build process

### ISSUE THREAD

**Issue by benkeen** [formtools/core#521]
- [x] Deep blue
- [x] Classic Grey
- [x] Oh Canada

**Comment by nelsondcosta23** [comment]
I have to be honest Im wating for this for a millénium XD
Can you share what you have in mind Ben?

**Comment by benkeen** [comment]
Hey @nelsondcosta23, sorry I missed your comment. This isn't anything too exciting, I'm afraid! With 3.0.14 I basically added in a simple way for me to work on the Core, plus any module in a very easy way. Now I just check out all the repos and run a single command locally & it run various grunt tasks to minify CSS and copy them into a local folder for development work. This ticket is to do the same for themes. 

The one upshot at this point is that the themes (which I'm about to update right now) will have properly minified CSS which'll mean faster a page load time. But down the road I can use this same technique for other build processes, like JS minification and using webpack and stuff. 

Like I said, not too exciting as an end user but very much needed!
