### ISSUE TITLE
Change form ID

### ISSUE THREAD

**Issue by crsleeth** [formtools/core#525]
When a new form is created it will get the form ID of 1 (ft_form_1) but even if this form is deleted the next form ID will be 2 (ft_form_2). Is it possible to change the form ID or reset the auto counter (AUTO_INCREMENT?) similar to the Submission ID Manager module? I have successfully changed a forms ID by copying a ft_form table to a new table and updating both the ft_forms and ft_form_fields, but am hoping there is another way because new forms still follow the incrementing value.

**Comment by crsleeth** [comment]
I see now I can reset the AUTO_INCREMENT of the ft_forms table.

**Comment by benkeen** [comment]
Interesting - may I ask why you need this? If it's useful I could maybe bake it into a feature at some point.

**Comment by crsleeth** [comment]
Its mostly because I'm a perfectionist and don't like seeing the single form on the website with anything other than ID 1. An argument for adding it as a feature would be that its confusing for users. When they log in and see the forms available to their account they may question why the only form they can see is labeled anything other than "1" as its ID. For example if they see its ID as "13" they might wrongful assume they're missing out on something.
