### ISSUE TITLE
Uploaded file can not be deleted using submission account view

### ISSUE THREAD

**Issue by AdStaak** [formtools/core#527]
After upgrading from core 2 to core 3 (and updating all modules) the submission account login view does not allow to remove uploaded files any more. Message "permission denied" appears. 
Any clues?

**Comment by nelsondcosta23** [comment]
Admin menu, files, and check folder permission and link permission

**Comment by AdStaak** [comment]
Both report OK.

I looked in the code and found a routine name that might missing an "s".

both routine getViewField and getViewFields exist, the first one has no parms, the second has two.

The code in file actions.php seems to use the wrong function call, missing "s" but two params...

Am I right?

		// check the submission and field being deleted belongs to the View the user is in
		$view_field = ViewFields::getViewField($view_id, $field_id);
		if (!Submissions::checkViewContainsSubmission($form_id, $view_id, $submission_id) || empty($view_field)) {
			output_json_with_return_vars(array(
				"success" => false,
				"message" => "Permission denied."
			));
			break;
		}

**Comment by nelsondcosta23** [comment]
hmmm about the code the best person is @benkeen , but check it your folder permissions change to 777 only to test, if it works... tell me and I tell you all folders and files permissions.

**Comment by benkeen** [comment]
Hey @AdStaak, thanks for reporting this! Yeah this looks like a bug. I'll look at it this weekend.

**Comment by benkeen** [comment]
Try adding this line to your Submission Accounts `modules/submissions_accounts/users/index.php` file, after line 28:

```php
Sessions::set("form_{$form_id}_view_id", $view_id);
```

I haven't quite got to the bottom of it yet, but that value isn't being set in sessions & it's needed for deleting the submission. I'll keep digging tomorrow and get a new version of Submission Accounts that fixes this. 

Thx again for reporting it!

**Comment by AdStaak** [comment]
@BenKeen, Did you look at my suggestion above about the wrong routine call? Look carefully, you are missing an "s" so the wrong function is called (which does not accept params) and the return value is not correct.

**Comment by benkeen** [comment]
I did - but that looks okay actually! `ViewFields::getViewField()` takes 3 params, with the 3rd being optional. `ViewFields::getViewFields()` takes two, with the second being optional. We're calling the right method here: we just want information about the single field.

**Comment by benkeen** [comment]
I'm going to close this & fix it in that ticket linked above. That fix I mentioned is working fine.
