### ISSUE TITLE
filename no longer displayed as link

### ISSUE THREAD

**Issue by greeeeeeenate** [formtools/core#530]
since one of the last updates, filenames of uploaded files are no longer displayed as links in the detailed view. I uploaded .pdf files and only the filename ist displayed.

**Comment by benkeen** [comment]
Hey @greeeeeeenate, which page is this exactly? I checked the following pages + scenarios and everything does look okay for me:
- submission listing page, single file upload
- submission listing page, multiple file upload
- edit submission page (readonly field), single file upload 
- edit submission page (readonly field), multiple file upload 

All scenarios show a clickable link when there's a single file uploaded. If the field is configured to allow multiple files to be uploaded and there ARE > 1 file uploaded, you just see a "3 files" string (or whatever) on the submission listing page, but that's expected. 

If your scenario is one of the above, try going into the module and clicking the "Reset Field Type" button to reset it to to it's factory defaults. Maybe an upgrade issue...?

**Comment by greeeeeeenate** [comment]
it is in the export type HTML > OneByOne
i call it with a link: <a href=details.php?form_id={$form_id}&view_id={$view_id}&export_type_id=3&submission_id={$submission_id}>Anzeigen</a>

here the code of OneByOne:

```
<input type="button" onclick="window.print()" value="Seite Drucken" />
<h1>{$form_name} - {$view_name}</h1>

{strip}
{foreach from=$submissions item=submission}
    {assign var=submission_id value=$submission.submission_id}
    <table cellpadding="2" cellspacing="0" width="100%" class="print_table one_item">
    {foreach from=$display_fields item=field_info}
        {assign var=col_name value=$field_info.col_name}
        {assign var=value value=$submission.$col_name}
        <tr>
            <th width="140">{$field_info.field_title}</th>
            <td>
                {smart_display_field form_id=$form_id view_id=$view_id submission_id=$submission_id field_info=$field_info
                    field_types=$field_types settings=$settings value=$value}
            </td>
        </tr>
    {/foreach}
    </table>
{/foreach}
{/strip}
```

**Comment by benkeen** [comment]
Ah, gotcha. Okay, I'll take a look.

**Comment by greeeeeeenate** [comment]
i updated everything, not it works. Thank you!
