### ISSUE TITLE
Validation Rules /  Required (Marked )  , but does not work ...

### ISSUE THREAD

**Issue by luizcesar1980** [formtools/core#534]
I have some forms with "File" field, they are marked as "Required" but still allow the user to follow the form submission ...

Anyone have any tips on what to do?

**Comment by benkeen** [comment]
Hey @luizcesar1980, is this a Form Builder form or within Form Tools itself? What versions of Form Tools and the File Upload module do you have running? 

Also: what browser are you on. Do you see any javascript errors on the page?

**Comment by luizcesar1980** [comment]
I am using Formtools version **3.0.14**, with Form Builder version 2.0.10.
I tested it with several browsers.
It has no Java Script error.

At first, the fields marked "Required" worked.
Now it's not working anymore. Even with the required field marked, it allows the user to confirm the submission.

**Comment by benkeen** [comment]
Hey @luizcesar1980, sorry for not getting back to you earlier. 

Hmm... sounds like something else may be going wrong besides just this. A few questions:
- Are there any javascript errors on your form?
- Did you customize the Form Builder templates at all for your form? 
- Did you upgrade to this particular Form Builder/Form Tools version, or is this a fresh install? If the former, could you try resetting the Field Types module by selecting it on your Modules page and clicking the "Reset" button.

**Comment by luizcesar1980** [comment]
Thanks for your help.
I did not update the "Form Builder" module.
I made the installation and create the forms, already with version 2.0.10.

I really need to sort this out. Because users are filling out the forms without the complete fields.

I just realized this, after I left the "Other" fields empty in Setings / Files. (to accept any file).
Do you think this can be a problem?

**Comment by luizcesar1980** [comment]
A complement of information.
I keep trying to solve this problem and realized that the validation of the "required" field is failing, since the Field Type is "File".

**Comment by benkeen** [comment]
Hey @luizcesar1980, I don't quite follow - you're trying to add validation to File fields, so isn't that correct? 

Also, if your form is publicly available could you send me a link to it? (Feel free to email me at ben.keen@gmail.com).

**Comment by luizcesar1980** [comment]
http://trackone.ddns.net:88/forms/modules/form_builder/published/optioncare_block.php

Hello, thank you for helping me.
I'm linking to a form.

I required the Upload file, to the file field (but you can follow and finish, even without uploading the file).
This is happening to everyone.

**Comment by benkeen** [comment]
Thanks, @luizcesar1980 - drat, I do apologize, this is a bug. I think it's a problem with the File Upload module but I'll investigate and if it's just a module, release a new version of it tomorrow night. I'll post back here when it's released.

**Comment by benkeen** [comment]
I'll release File Upload 2.2.3 shortly that contains a fix for this. Thanks again for reporting this and sorry for the bug!

Closing.

**Comment by luizcesar1980** [comment]
Thank you very much.
I look forward to the availability of the file to update the module.
We will always be in contact ...

**Comment by benkeen** [comment]
No problem! It should be available right now. Just click "Update" in your Form Tools installation to get redirected to Form Tools website where you can download the new version.

**Comment by luizcesar1980** [comment]
Can you send me the link?
You are not grasping the Update option.
In the formtools.org site you still do not have the link of the new version.

**Comment by benkeen** [comment]
Just click on the "Update" link at the top right of your Form Tools installation: 

<img width="1023" alt="ft" src="https://user-images.githubusercontent.com/512116/56784901-ba0b1a80-67a7-11e9-8d88-c8e443b20c2f.png">

That will take you to the Form Tools site where you should see a page like this: 

<img width="1243" alt="upgrade" src="https://user-images.githubusercontent.com/512116/56784926-dc9d3380-67a7-11e9-91c0-0f6a62c679bb.png">

You can generate a fresh download file containing the new version of the module. 

Alternatively you can always download versions right from github:
https://github.com/formtools/module-field_type_file/releases

Here's the installation instructions if you do it manually:
https://docs.formtools.org/userdoc/modules/installing/

**Comment by luizcesar1980** [comment]
I was able to do the update.
The same form I sent you to test, now it worked.

(I had to redo the field configuration as "required")

I think it will work on everyone else ...
I'll update, everyone, thank you again ...
