### ISSUE TITLE
Website Download Custom Build - down

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#544]
Hi Ben, 

Website when download custom build is down.

**Comment by benkeen** [comment]
Sigh, thanks Nelson. Patched again. 3.1 can't get done quick enough. 

On that note, btw, 3.0.15 is almost done - should get it out the door this weekend.

**Comment by willcwell** [comment]
Custom Build is still down

**Comment by nelsondcosta23** [comment]
Hi Ben, how are you?
Website its busy :P
