### ISSUE TITLE
module-submission_history-2.0.4 will not install

### ISSUE THREAD

**Issue by willcwell** [formtools/core#556]
ver 3.0.15

**Comment by nelsondcosta23** [comment]
can add some screenshots?

**Comment by willcwell** [comment]
Are these the kind of screenshots you wanted or do you need something different.

**Comment by willcwell** [comment]
I got the module to install but "Load History" does not populate. Changes are written to the database but nothing happen when clicking "Load History"
I changed the Submission History to Auto-load history on edit submission page to "yes" it just shows an animated gif spinning. Please help.
![Capture](https://user-images.githubusercontent.com/50843203/58426765-77b94f80-806b-11e9-9ac5-19e338eb91a4.PNG)

**Comment by benkeen** [comment]
Hey @willcwell, sorry for not being around to help out. I'll check this out tomorrow night to make sure nothing's recently gone wrong & get back to you then.

**Comment by benkeen** [comment]
Sorry about that @willcwell, this appears to be a bug. I'll create a ticket on the Submission History repo and link to it. Not sure what happened.. nothing particular has changed that would cause this, so I suspect it'll be a quick fix. If all goes well I'll release an update to the module tomorrow night. See the linked ticket for more info (will add in a moment).

**Comment by benkeen** [comment]
Closing - will patch on the ticket above.

**Comment by benkeen** [comment]
Hey @willcwell - thanks again. I released 2.0.5 tonight that patches this problem.
https://github.com/formtools/module-submission_history/releases/tag/2.0.5

**Comment by willcwell** [comment]
Ben – Whatever you did worked. Thank a million.
Please note the install is “folder name” specific.
Meaning I had to rename module-submission_history-2.0.5 to submission_history before I had an option to install it. Maybe I overlook this in the documentation.
module-submission_history-2.0.5 -------> submission_history
Thank again for all of your great work.

**Comment by benkeen** [comment]
No problem, glad to help! Yes, the renaming of the folder is a nuisance. I documented it here:
https://docs.formtools.org/userdoc/modules/installing/

But it's not obvious at all. I'm slowly plodding my way towards Form Tools 3.1 which will greatly simplify the whole installation process (no more manual installation of components or renaming things like this). 

All the best - 

Ben

**Comment by nelsondcosta23** [comment]
Hi, when download FT the "Submission History" its grey(cant select)
