### ISSUE TITLE
Forcing HTTPS removes page formatting

### ISSUE THREAD

**Issue by Jarod997** [formtools/core#579]
I force HTTPS on my pages to support Google fonts and their map API, and which (AFAIK) should cause any other things to break - except when HTTPS is on all the formatting on the FormTools pages (admin pages, not the actual form) is lost. 

Also, all the buttons except for "search" on `/admin/forms/submissions.php` won't work.

**Comment by benkeen** [comment]
Heya, so you updated your global/settings.php `$g_root_url` for the https? I gotta admit, FT has supported secure sites for a long long time so it's a bit puzzling it's causing problems now. Does it break on the login page too? If so, could you post a link to your login page (or email me at ben.keen@gmail.com if it's private) so I could take a look?

**Comment by Jarod997** [comment]
Aww poop, I knew it was a simple mistake. So I force HTTPS through my base .htconfig, but I had not included "https" specifically in the `global/config.php - $g_root_url` -- it was still "http". After specifically including the "S", it would seem all the formatting is back where it should be. Thanks again Ben.
