### ISSUE TITLE
Number of pages

### ISSUE THREAD

**Issue by Landlordsa** [formtools/core#582]
Hi ... Is there a way to create a form with more than 6 pages / tabs?  Alternativly can the last field on Tab 6 be used to open a different form?
Thanks

**Comment by nelsondcosta23** [comment]
im pretty sure at this moment FT cant do that

**Comment by Landlordsa** [comment]
Thanks for the response Nelson.  I'm very much a newbie and really enjoying FT.  Can you give me an idea how I add multiple pages to a form?

**Comment by Landlordsa** [comment]
Now I'm pushing my luck lol.  Can the date field default to todays date on opening the form?

**Comment by benkeen** [comment]
haha sorry @Landlordsa, that's not doable just yet either... great feature request though.

**Comment by Landlordsa** [comment]
Can you give me an idea how I add multiple pages to a form?

**Comment by Landlordsa** [comment]
When trying to add another field I am getting an error:
'The form field 'bedroom2_lights' could not be added.' 
Is this due to Total Fields?  If so where do I increase this value?
Is there a limit to the amount of fields per report?
