### ISSUE TITLE
edited submission via phpmyadmin. Now I get a MySQL syntax error editing a submission

### ISSUE THREAD

**Issue by mmelon** [formtools/core#588]
Hi. More out of curiosity than anything else, I corrected a submission directly in the DB using phpmyadmin. Now i cant edit submissions in the back end. I am getting:

Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM frmga_form_2 WHERE is_finalized = 'yes' ' at line 2

so presumably it's inserted something in a way FT doesn't like. Is it the extra single quote?

**Comment by benkeen** [comment]
Hey @mmelon, hmm yeah possibly! Do you remember which fields you edited? 

The section of SQL you quoted looks okay to me, honestly. But sometimes the errors aren't quite as clear as I'd like.

**Comment by mmelon** [comment]
It's weird I really didn't do anything dangerous. Just edited a field of type text and removed some content. The MySQL executed fine and I could see the change. The full error is this:

Uh-oh.
The system encountered a serious database error. This should not occur. Please report these details on github.

Class: FormTools\Submissions 
File: .../global/code/Submissions.class.php
Line: 1308
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM frmga_form_2 WHERE is_finalized = 'yes' ' at line 2

Is it something to do with the fact that the submission are no longer finalised because they were edited externally?

It doesn't do it on the original form (I edited both) but it does on a copy I made using the form backup module.

**Comment by mmelon** [comment]
the only other difference i can think of is the backup version has been made private. The original is public. I tried adding a submission. I got the error but going back in, the submission had been added.

**Comment by mmelon** [comment]
ok my mistake. There was a field in the copy that was referencing a field in the original that had been deleted. It should have broken earlier and maybe did but i didn't notice it. Removed the field referencing a dropdown in the original that i took out, fixed.
