### ISSUE TITLE
Forms built and configured but  500 error on publishing

### ISSUE THREAD

**Issue by MidCheshireMC** [formtools/core#600]
Hi,

I am getting a 500 error when pressing the publish tab button in Form Tools.  The rest of the functionality worked absolutely perfectly.

Running LAMP server on Centos 7 ?
Any ideas would be gratefully received

![Formtools](https://user-images.githubusercontent.com/54587096/63777329-d72d3280-c8da-11e9-981b-e84e5c88dd89.JPG)

Thanks
MidCheshire MC

**Comment by kniiiip** [comment]
I had the exact same error today and when I looked in the error logs I didn't have write permissions in some subfolders of the /themes/default folder.

The problem was solved after giving recursive write permissions to the /themes/default folder

**Comment by MidCheshireMC** [comment]
In the end I wrote my own PHP / html that used my existing database and dropped FormTools.
That's great you found the permissions issue on /themes/default folder as I'll re-use FormTools on another project.

Thanks
MidCheshireMC
