### ISSUE TITLE
Typo in Adding something to a specific form page

### ISSUE THREAD

**Issue by radamesi** [formtools/core#612]
Thank you so much for this software!

Using code in [Adding something to a specific form page](https://docs.formtools.org/modules/form_builder/usage/common_tasks/targeting_specific_form_page/), under **Specifying a form or View**, I have noticed that the equal after the && clause uses only one = symbol.

When we update the template using that syntax, Apache logs an issue like this:

`PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "eval:{{navigation}} <h2>{{$page_name}}</h2> ..."  on line 5 "{{(if $current_page == 1 && $form_id = 5)}}"  - Unexpected " " <-- \n  thrown in /var/www/html/formtools/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 5`

When we change the = to ==, the issue is solved. Maybe updating the documentation would be useful for other users...

Thanks!

**Comment by benkeen** [comment]
Ooh, thanks! I'll fix this right now.

**Comment by benkeen** [comment]
Fixed.
