### ISSUE TITLE
can I paste tabular data from a worksheet

### ISSUE THREAD

**Issue by splaisan** [formtools/core#613]
I would like to fill multiple rows of multiple fields at once from an existing worksheet by copy paste.

is this possible? how?

Something like [tablesgenerator](http://www.tablesgenerator.com/) linked to a form and filling it in one paste action

I now send an empty excel file to my customers and they return it filled with data (and often errors)

**Comment by nelsondcosta23** [comment]
See if it helps https://github.com/nelsondcosta23/CSV-to-SQL

**Comment by splaisan** [comment]
Thanks Nelson,
I will see if this can be come to play.
Best
