### ISSUE TITLE
Update to 3.0.15: blank modules page

### ISSUE THREAD

**Issue by thosau** [formtools/core#614]
Hi @all,

I've tried to upgrade my FormTools-installation from 2.2.6 to 3.0.15.
I logged off from FormTools, unzipped the downloaded files und put them via ftp on the server.
After login to FormTools I get the 'standard' FormTools-page showing me version 3.0.15. But when I want to open the modules page, I only get a blank screen.

The servers error logfile says:
`26.09.2019 16:39:31 domain.com [client xxx:xx:xxxx::] PHP Fatal error:  Call to a member function getModuleName() on boolean in /FormTools_root/admin/modules/index.php on line 54`

and

```
26.09.2019 16:55:27 domain.com [client xxxx:xx:xxxx::] PHP Fatal error:  Uncaught Error: Call to a member function getModuleName() on boolean in /FormTools_root/admin/modules/index.php:54
26.09.2019 16:55:27 domain.com [client xxxx:xx:xxxx::] Stack trace:
26.09.2019 16:55:27 domain.com [client xxxx:xx:xxxx::] #0 {main}
26.09.2019 16:55:27 domain.com [client xxxx:xx:xxxx::] thrown in /FormTools_root/admin/modules/index.php on line 54
26.09.2019 16:55:37 domain.com [client xxxx:xx:xxxx::] PHP Fatal error:  Uncaught Error: Call to a member function getModuleName() on boolean in /FormTools_root/admin/modules/index.php:54
```

For test purposes I changed the PHP-version from 5.6 to 7.2, but that didn't solve the problem. Maybe the above written messages are from the same error, one time from 5.6, one time from 7.2. But I'm not sure...

I checked the database whether it contains a 'ft_modules'-table like it is written here:
https://github.com/formtools/core/issues/583
But my database contains no such entry 'ft_modules'...

Any help would be appreciated.

Regards, thosau

**Comment by Voels** [comment]
Hello Thosau,
I found out, the table´s name is just "modules" (not "ft_modules")
There I found the entry "Core Field Types....." (in my case it was id=5)
After deleting this line ("Core Field Types.....") the page [FormTools]/admin/modules/ is shown (after refreshing the page).
The modules are shown now.
Greetings
Voels

**Comment by Voels** [comment]
Hi again,
after doing steps as mentioned in https://github.com/formtools/core/issues/614?_pjax=%23js-repo-pjax-container#issuecomment-536135798
it should be possible to enter the "module"-menu and doing the specific module-updates as described in step 7: https://docs.formtools.org/upgrading/
_"Log in as the administrator and go to the Modules page. There, click the Upgrade button for all modules that require it. "_

Greetings,
Voels

**Comment by benkeen** [comment]
Thanks for reporting this. The error handling is rather poor on the Modules page. I'll include a patch for this in 3.0.20.
