### ISSUE TITLE
Issue while Installing Form Tools 3.0.17 on PHP 5.3

### ISSUE THREAD

**Issue by prbt2016** [formtools/core#620]
Hi,

I  was trying to manually install Form Tools 3.0.17 on PHP 5.3. However i encounter with an error. While starting the installation on PHP 5.3, i get a blank page like this.

![error](https://user-images.githubusercontent.com/17871448/66106262-0d955600-e5db-11e9-8637-ad71d8c9585b.png)

So to further inspect the issue, I checked Apache error log, It shows following error:

PHP Fatal error:  Call to undefined function FormTools\\http_response_code() in /{{path}}/{{to}}/{{ftools}}/global/code/General.class.php on line 1487, referer: http://{{domain.com}}/ftools/install/

What could be causing the issue?. Script works fine on PHP 5.4. However the minimum PHP requirement mentioned on website is PHP 5.3+ here:
https://docs.formtools.org/userdoc/getting_started/system_requirements/

Are the PHP requirements changed. Could you please check this at your end and fix this issue for PHP 5.3?

**Comment by nelsondcosta23** [comment]
plz just dont use php5.3, upgrade for php7
if need help to upgrade just tell me your SO, and what apache/ningx server are you using.
Ah ofc if you are using plex, virtualmin, cpanel, or other.... or nothing at all.

**Comment by benkeen** [comment]
Drat, thank you so much for letting me know @prbt2016! I'll check it out and release an update tonight.

Yeah, upgrading to PHP 7 never hurts @nelsondcosta23 :) but I'd like to continue supporting older versions of PHP for as long as I can.

**Comment by benkeen** [comment]
This fix is in the 3.0.18 release. Let me know if you have any troubles.
