### ISSUE TITLE
Forms not saving

### ISSUE THREAD

**Issue by ocbroadband** [formtools/core#623]
Hello,

I'm having random issues with forms not saving, however, they are completing the form as expected and passing all the criteria for field requirements.   Currently running v3.0.15.  This is essentially a registration form that is duplicated from last year with just some displayed dates changed, and a different form number.   Is there anything related to this version that might cause this, or is there something I can check to determine where the issue might be occurring?

**Comment by benkeen** [comment]
Hey @ocbroadband, hope all is well! 

Where exactly does this occur? After creating a new form through the interface? So you step it all through and then it doesn't save? Does it disappear altogether or do you need to re-edit it or something to make it save properly?

I'd start by looking at the PHP and MySQL error logs to see if there's any interesting errors in there. I glanced over the history of recent versions and nothing in particular stands out for this area of the codebase.

**Comment by ocbroadband** [comment]
Hi Ben,

Yea, I've gone through and looked at it, however, I'm not finding anything that I would consider to be odd.  But I'm not quite the guru to find anything that may be right in front of me either.  I was thinking about upgrading, but we're right in the middle of registration, and I don't want to bork it up just in case, so I was going to wait.  What's your suggestion?

**Comment by ocbroadband** [comment]
Hi Ben,

Sidenote.  I 'may' have found an issue with my host, but am waiting to see how it falls out.  I'll advise.

Lyle

**Comment by benkeen** [comment]
It's unlikely... It does rather sound like a litany of problems you're having - the missing Swift Mailer table in particular is really very worrying indeed. So you said you were in the middle of registration? Data is still coming in just fine for your existing forms? I'd definitely wait for the registration to be over - you don't want to risk destabilizing anything further. 

Once that's done you could look into upgrading.

**Comment by ocbroadband** [comment]
Hi Ben,

Thanks for the reply.  Yea, I'm not sure if this is just a coincidental issues occurring or what, but I'm trying to isolate as much as I can.  :)  Yes, form data is coming in, but its sporadic.  I can provide some login info if you want to poke around.   My host is telling me there is a memory issue which is a crock as this is the exact same installation that I ran last year flawless, just a new form, and changing the year info on the actual form.   Anyway, let me know, I'm anxious to hopefully get this resolved.

**Comment by ocbroadband** [comment]
Closing this issue as it appears it was related to the referenced issue https://github.com/formtools/core/issues/639 I have opened.
