### ISSUE TITLE
Not issue per se, but question about possibility of filtering forms

### ISSUE THREAD

**Issue by littlehummerboy** [formtools/core#624]
Love the software.
I have a question about this scenario:
I have one database with 2 fields, one is for a name string field, the other for a status type field, ie living or dead.  I can then create different views to see either people who are living, or dead, or both.  I can also change the default view and apply a filter so that by default only a selected group of fields are displayed.  This all works as expected.

I now create a second form, in which one of the field types is a multiple selection type, such as a multi select drop down, radio, or checkbox, and the settings are using a form field content, pulling a field from the first form, hoping it will show only the filtered data.  Even if the default View has a filter applied to it, the new form always shows ALL the forms using this field.

Is there any workaround for this short of the API?
Thanks

**Comment by benkeen** [comment]
Hey @littlehummerboy, thanks for the post! 

Honestly, that feature really isn't all that useful. All it lets you do is get a list of values from another form into a different form. There's no tying together of the information at all, or doing anything advanced like it sounds you need. So yeah, I think you'll need the API for this. 

Sorry about that - 

Ben

**Comment by coffeecuplid** [comment]
I'm kind of seeing something similar (new to formtools as well):

Say you have two forms:
  1) List of stores: this would list store details - name, location, square footage, hours open, etc
  2) List of products:  product description, details, create dropdown to select which store sells this product
(Note: one can have multiple forms here, maybe a employee list per store, etc. The important thing is to make sure the store name is the same across all forms via dropdown)

In #2, the dropdown is based upon the store id in table 1.

If I use the formtools interface and only want to see products in store with a certain name (for example to modify entries), I can't search on that store name in table #2, I need to look at table #1, figure out what ID represents the store name, then search table 2 for that ID.

I'd like to be able to have a web page which has an "edit products" button under a "Kroger" store listing and that would take me to the formtools form #2 only listing the Kroger products for editing records
