### ISSUE TITLE
Update link not working

### ISSUE THREAD

**Issue by joshmckibbin** [formtools/core#631]
https://formtools.org/upgrade/ is not working. It is showing a 500 server error when I click the update link.

**Comment by benkeen** [comment]
Thanks @joshmckibbin. I did a site update a few days ago that did a massive refactor for updating to PHP 7; this may be related. I'll look at it today.

**Comment by benkeen** [comment]
Sorry about that. It's online again now.

**Comment by joshmckibbin** [comment]
Thanks for your quick response. Unfortunately, for me, the issue still remains. I'm trying to upgrade from 3.0.15. Let me know if there is any other info that you need from me.

**Comment by tkelling** [comment]
@joshmckibbin did you solve this? I seem to be having the exact same problem today. I'm stuck on 3.0.15 and when clicking the "Update" link I get the 500 error.

**Comment by benkeen** [comment]
Hey @tkelling, what browser are you using? Just trying to fathom why this isn't working for people.

**Comment by tkelling** [comment]
@benkeen, thanks for looking. I was on Chrome desktop when it was not working earlier. I just tried on Chrome mobile and it worked.

**Comment by joshmckibbin** [comment]
I'm not sure what changed but I just tried it again in Chrome and it worked.

**Comment by tkelling** [comment]
@benkeen, it works now. I'm not sure what changed. Thanks.

@joshmckibbin, thanks for testing. It's working again for me now. Seems like it works intermittently for some reason.
