### ISSUE TITLE
Google Maps API - JS ERROR(solved) - Add Location Botton

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#632]
Hi guys, how are you?
Do you have any extra tips for google maps api to work?

I use the API and get the error on the form
![image](https://user-images.githubusercontent.com/11686595/66951514-75738400-f052-11e9-9b29-e9948bf4b1a5.png)

API - key module
![image](https://user-images.githubusercontent.com/11686595/66951570-93d97f80-f052-11e9-96ca-e39f7d6db868.png)

**Comment by nelsondcosta23** [comment]
Solved, problem with API
Any one knows how add "location" botton? I mean press a botton to locate where I am?

**Comment by benkeen** [comment]
Hey @nelsondcosta23, that should actually be pretty straightforward. Let me take a look at it.

**Comment by nelsondcosta23** [comment]
I was looking inside the code of module.class and custom field until now I had done some stuffs. But the location botton until now I have no ideia.
By the way for the people who might need this, if you want extra option like

![image](https://user-images.githubusercontent.com/11686595/66976700-c73ffc80-f09a-11e9-87ce-e90586b3388a.png)

Just go module -> Custom Field -> Google Maps -> JS -> and:
    zoom: 17, (ZOON)
    center: new google.maps.LatLng(41.1579438, -8.629105299999992), (LOCATION OF START)
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    streetViewControl: true,
    mapTypeControl: true,

**Comment by benkeen** [comment]
Hey @nelsondcosta23, I've got it working locally and I'll add it to the next version of the google maps module. However, the web API to get the user's lat/lng coordinates only runs consistently on browsers using `https`, not `http`, so I'll only add the button for secure websites. Screenshot attached.

<img width="773" alt="Screen Shot 2019-10-16 at 10 07 57 PM" src="https://user-images.githubusercontent.com/512116/66979230-a5765380-f061-11e9-9743-1266ba7f105d.png">

**Comment by benkeen** [comment]
Closing. I created an issue on the Google Maps module above.

**Comment by benkeen** [comment]
I just released 2.1.0 of the Google maps module - I'll update the docs tonight.

**Comment by benkeen** [comment]
2.1.1 is updated to properly update the DB. And yeah - it'll overwrite any custom changes you made, Nelson, so be warned!
