### ISSUE TITLE
Server sent charset unknown to the client

### ISSUE THREAD

**Issue by herongyang** [formtools/core#634]
Hi, 

I am new to Form Tools and getting the following error during the installation of the Core downloaded today:

Sorry, we were unable to connect to the database using the information you supplied. The error message the database returned is: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers

Maybe I missed some steps on MySQL database. But I am able to access it with the "mysql" command line client with no problem. 

Please help.

Thanks.

**Comment by herongyang** [comment]
I resolved the issue by re-installing the MySQL server.

**Comment by benkeen** [comment]
Thanks for letting us know, @herongyang! Glad it's resolved.
