### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by luizcesar1980** [formtools/core#636]
I am having trouble exporting information to XLS or CSV.
When I try to export any form with multiple records, I get an error message in the browser. Time Out
I saw a post indicating that increase the time in PHP.INI, I made some attempts hand did not solve the error.
What can I do to successfully export records over 1000, 2000, 5000 items?

Thank You

**Comment by nelsondcosta23** [comment]
You have to change the php configurations
cache, timeout, etc...
The time it self might not solved the problem. Change the size of file, etc...

**Comment by guitarbeard** [comment]
I think I found the timeout issue here https://github.com/formtools/module-export_manager/blob/master/code/Module.class.php#L597

I commented that line out and now it uses my php.ini file's max_execution_time

**Comment by benkeen** [comment]
Thanks @guitarbeard - I'll add a setting to the Export Manager module this weekend to allow that be customizable. I'll patch it on that other ticket on the Export Manager repo.
