### ISSUE TITLE
FormTools upgrade link is down

### ISSUE THREAD

**Issue by nelsondcosta23** [formtools/core#647]
Hi Ben, how are you?
Upgrade link is down "https://formtools.org/upgrade/"

![image](https://user-images.githubusercontent.com/11686595/68509017-e0863400-0267-11ea-8eb1-2240145a5216.png)

**Comment by benkeen** [comment]
Hey Nelson, hmm seems ok to me! Mind checking again? Wonder if the site went down for a bit.

**Comment by Yannick45** [comment]
I get the same error. The link is down for a while. I already reported a month ago...

**Comment by nelsondcosta23** [comment]
Hi Ben, How are you? Still down.
Isnt very important we can get from the site :P

**Comment by IainDelaney** [comment]
Yes, sorry, it's broken for me, too.

**Comment by benkeen** [comment]
Apologies all, I see it now. Looking into it now.

**Comment by benkeen** [comment]
Would someone mind trying again now?

**Comment by Yannick45** [comment]
It works fine now. Thanks :-)

**Comment by benkeen** [comment]
Thanks @Yannick45 - very sorry about the problem, everyone. I wasn't testing by sending the right data to the upgrade script so didn't hit the condition that caused the error. 

Let me know if anything like this pops up again. Closing.
