### ISSUE TITLE
API: checkSubmissionIsUnique() not working properly after upgrade to FT3

### ISSUE THREAD

**Issue by thosau** [formtools/core#648]
Hi @all,
up to now, I was using FormTools2 with API V1.x. After upgrading to FormTools3 with API V2.x, an important part of my form validation does not work properly any more.

In my form, I want to check the uniqueness of the user's e-mail-address. Unfortunately, the e-mail-column contains further information like timestamp and editor of data, all divided by the pipe-char "|".
E.g. the e-mail-column looks like this:
"name@domain.com|2019-10-24 08:13:37|Grandma"

With FormTools2, I checked the uniqueness of e-mail-address with the following statements:
```
$mail=explode('|', $_POST['E_Mail']);
$criteria = array(       
         "(SELECT SUBSTRING_INDEX(e_mail, '|', 1))" => $mail[0]);
ft_api_check_submission_is_unique($myFormID, $criteria,
          $fields["form_tools_submission_id"]);
```

This worked fine, but with following FormTools3-instruction I get error-code 554 and the check against uniqueness fails. 
```
$mail=explode('|', $_POST['E_Mail']);
$criteria = array(       
         "(SELECT SUBSTRING_INDEX(e_mail, '|', 1))" => $mail[0]);
$api->checkSubmissionIsUnique($myFormID, $criteria,
          $fields["form_tools_submission_id"]);
```
(API is correctly included, as other FormTools-API-instructions work fine). For test purpose I let echo the FormTools-API-Class the produced SQL instruction. I am not very familiar with SQL, but possibly there is something wrong, because in my opinion it checks "column_name=column_name" and not "column_name=value"...
`SELECT count(*) FROM {PREFIX}form_5 WHERE (SELECT SUBSTRING_INDEX(e_mail, '|', 1)) = :(SELECT SUBSTRING_INDEX(e_mail, '|', 1)) AND submission_id != :submission_id`

Any help would be appreciated to fix the uniqueness check.
Thanks in advance, thosau

**Comment by benkeen** [comment]
Hi @thosau, interesting one! I took a look and I think it's actually working correctly. The reason it's no longer working for you with the new version of the API is that it now uses PDO for all database query creation, and it works differently than before. Previously, you could kind of hack around it like this to pass arbitrary SQL into it, but PDO is designed to prevent precisely that. Allowing queries to be constructed in that manner opens up your application to SQL injection attacks. 

I've been puzzling it over how to expand that function to let you do what you need, but I think I'd suggest just doing a custom query in your PHP and not using the API method anymore. 

To do that, try something like this (untested - but something along these lines should work):

```php
$api = new FormTools\API();
$db = FormTools\Core::$db;

$mail = explode('|', $_POST['E_Mail']);

$db->query("
    SELECT count(*) FROM {PREFIX}form_5
    WHERE (SELECT SUBSTRING_INDEX(e_mail, '|', 1)) = :email
   AND submission_id != :submission_id
");
$db->bindAll(array(
    "email" => $mail,
    "submission_id" => $fields["form_tools_submission_id"]
);
$db->execute();

echo $db->numRows; // if this is 1 it's unique. Anything more and it ain't!

```

**Comment by thosau** [comment]
Hi @benkeen,
thank you very much for your fast response and sorry for charging you with the non-proper-working API-function. Sorry, that was my fault.

As I haven't used PDO before, I couldn't get your lines going in reasonable time (your lines produced no output and I couldn't get going the PDO-error-handler...). So I tried to make it with 'mysqli', which works fine now for me. Thanks for your effort!

For other people having the same problem: here are the lines with which I could make it.
```
$formular = 'form_5';
$mail=explode('|', $_POST['E_Mail']);

$query = "SELECT count(*) FROM ".$formular."
              WHERE (SELECT SUBSTRING_INDEX(e_mail, '|', 1)) = '".$mail[0]."'
              AND submission_id != ".$fields["form_tools_submission_id"];
          $result_fv=$mysqli_fv->query($query);
          if($result_fv){
            $line=$result_fv->fetch_assoc();
            $rowNum = $line['count(*)'];
            echo "Number of rows: ".$rowNum."<br>";
          }
```

Regards, thosau
