### ISSUE TITLE
Cannot Add Record in Filtered View

### ISSUE THREAD

**Issue by dettjw01** [formtools/core#683]
I have tried seven ways from Sunday to make this work, but am not able to create a view where the user can submit new records if there is a filter applied.  The filter is applied to the search records screen, but when the user tries to add a record by clicking the "Add Submission" button, it simply refreshes the search page and puts a blank record into the database.  What am I doing wrong?

**Comment by dettjw01** [comment]
I don't know if this is the correct solution, but I added a pipe to the end of the filter to allow NULL or empty entries.  The filter in the view was kicking the user out of the form because they created an entry but the field was NULL.  This was filtered out by the view.  
Seems like a bug, not a feature.  ?

**Comment by nelsondcosta23** [comment]
I never saw that before.
Can you share a print?
