### ISSUE TITLE
Forbiden

### ISSUE THREAD

**Issue by mjvmst** [formtools/core#69]
when i edit section Emails, e recive error:

Forbidden

You don't have permission to access /formtools/admin/forms/edit/index.php on this server.

**Comment by benkeen** [comment]
Hi @mjvmst - sorry I missed this issue. Did you ever solve it? I confess I haven't run into the issue - it sounds like the file permissions may be off for that particular file.

**Comment by mjvmst** [comment]
Hi,

I manipulate the info in database.

Thanks!

 

 

De: Benjamin Keen [mailto:notifications@github.com] 
Enviada: 5 de novembro de 2017 02:45
Para: formtools/core <core@noreply.github.com>
Cc: mjvmst <mjvmst@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [formtools/core] Forbiden (#69)

 

Hi @mjvmst <https://github.com/mjvmst>  - sorry I missed this issue. Did you ever solve it? I confess I haven't run into the issue - it sounds like the file permissions may be off for that particular file.
