### ISSUE TITLE
Form Edit Errors - Fields, Views

### ISSUE THREAD

**Issue by WMGS** [formtools/core#71]
In form edit: admin/forms/edit/index.php?form_id=1&page=main

**Clicking on Fields, then Update (at bottom) throws:**

Notice: Undefined index: edit_fields_sortable__rows in /home/mysite/public_html/cms2/global/code/Forms.class.php on line 1526

Notice: Undefined index: edit_fields_sortable__new_groups in /home/mysite/public_html/cms2/global/code/Forms.class.php on line 1528

Notice: Undefined index: edit_fields_sortable__deleted_rows in /home/mysite/public_html/cms2/global/code/Forms.class.php on line 1562

**Clicking update button on views throws:**

Notice: Undefined index: view_list_sortable__rows in /home/myflroffice/public_html/cms2/global/code/Views.class.php on line 631

Notice: Undefined index: view_list_sortable__new_groups in /home/myflroffice/public_html/cms2/global/code/Views.class.php on line 632

Notice: Undefined offset: 1 in /home/myflroffice/public_html/cms2/global/code/Views.class.php on line 636

Notice: Undefined index: group_name_ in /home/myflroffice/public_html/cms2/global/code/Views.class.php on line 638

**Clicking update email template throws:**

Notice: Undefined index: recipients in /home/myflroffice/public_html/cms2/global/code/Emails.class.php on line 1022

Warning: Invalid argument supplied for foreach() in /home/myflroffice/public_html/cms2/global/code/Emails.class.php on line 1024

**Comment by WMGS** [comment]
Uploaded and installed again on same server (VPS), different domain, and all worked fine. 

Server throwing errors (above post) has an SSL cert. installed. Not sure if that helps with identifying the problem.

**Comment by benkeen** [comment]
Excellent, thanks @WMGS! Very helpful stuff! :) 

I have the warnings/notices turned up very high on the alpha, just to see what stuff shakes loose. This is good info.

**Comment by benkeen** [comment]
I think this is all fixed now so I'm closing.
