### ISSUE TITLE
Installation issue Form Tools 3

### ISSUE THREAD

**Issue by BamboBob** [formtools/core#72]
During step 3 of Form Tools 3 I get following error: "Fatal error: Uncaught --> Smarty: unable to write file /volume1/web/themes/default/cache/wrt59c6220ebb0fb7_38535300 <-- thrown in /volume1/web/formtools3/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php on line 49"

I'm running MariaDB 10 and the script passed all checks:
![form tools 3 install step 2](https://user-images.githubusercontent.com/32217186/30771727-519149b0-a04e-11e7-8101-e1ebc945cc1c.jpg)

The write permissions should be fine as the script did write a couple of files:
![form tools 3 install cache files](https://user-images.githubusercontent.com/32217186/30771720-33325bbc-a04e-11e7-88ff-60b02c3edbb2.jpg)

**Comment by benkeen** [comment]
Curious... like you said, it was clearly able to write to the folder initially at least. Couple of things to try:

- manually change the permissions on the folder to full read-write. Maybe the PHP user agent suddenly lost write permissions to that folder, or the folder itself got changed by the system somehow..
- failing that, delete the whole folder and create a new one with write permissions. 

I haven't encountered this problem before, but those are worth trying.

**Comment by BamboBob** [comment]
Thanks, Ben
Unfortunately your suggestions did not work. I wonder whether this could be caused by certain PHP settings. Do you have any idea which core or specific plugin settings may be involved with processing at this step?

**Comment by benkeen** [comment]
Hey @BamboBob, looking over the code I don't see anything particularly unique or different about that page. How about checking your PHP logs and seeing if that contain any more info? Kind of baffled here, to be honest.

**Comment by BamboBob** [comment]
Hi @benkeen, I've checked several logs and cannot find anything other than this:
![form tools 3 install apache log](https://user-images.githubusercontent.com/32217186/30829357-dc7cb174-a240-11e7-816f-5b801f395d74.jpg)

I'm afraid it doesn't add much.

**Comment by benkeen** [comment]
Hey @BamboBob, no not too helpful, drat. Everything I've read on this says that the permissions on the folder aren't right or the PHP user has lost the rights to write to the folder/file. At this point, all I can suggest is contacting your hosting company to see if they have any ideas...

**Comment by benkeen** [comment]
I'm going to close this issue - if it re-occurs or there's any other info, let me know. But the path does look incorrect, so I think that's the problem.

**Comment by BamboBob** [comment]
Hi @benkeen, I hadn't seen your earlier edit. I can't recall getting a notification.
Indeed the path is wrong, but I cannot find /global/config.php file. Should it been created already? Also no references to $g_root_dir
