### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by cloudpilot73** [formtools/core#73]
Hi,

I appear to be having an issue with standards errors on the login screen and when logging in, i get the same errors on a blank screen. I've been through the list of strftime codes, but can't find the issue?

![formtools](https://user-images.githubusercontent.com/28367195/30885076-da35e808-a309-11e7-847c-2f9ebd1f8cfa.PNG)

**Comment by benkeen** [comment]
Hi @cloudpilot73, interesting! So I wouldn't worry: I deliberately left all warnings & notices to be displayed in the alpha version, just so I can see what minor issues may be occurring in case they're symtoms of some deeper problem. For the prod release I'll disable these minor issues and you'll never see them. 

That said, I'd like to patch up as many as I can. This particular issue is pretty minor: I think in your instance your server doesn't have a timezone set so PHP is making a guess at it, and then showing that error. 

Would you mind creating a PHP file on your server with this content and loading it up to see what gets output? 

```
<?php
echo "Timezone: [" . ini_get("date.timezone") . "]";
?>
```

If I can determine that nothing has been defined, I'll set a default value in the code & you'll never see those warnings.

**Comment by cloudpilot73** [comment]
Hi @benkeen ,
I uploaded the file, but no change. I'm still getting the same message. I even changed the timezone via ssh, but still getting the same.
Is there any way of overriding this?

**Comment by benkeen** [comment]
Hey @cloudpilot73 - to be clear, so you're getting that same message on the file you uploaded? i.e. you loaded that file in your browser & even just that one line of code to get the timezone is throwing that error? I think you should take that to your hosting provider and ask them what's going on... it sounds like maybe the server has been misconfigured. 

I did some testing on my end: I removed the timezone setting from my php.ini file and called that line, but it just outputs `Timezone: []` - no errors or anything, even with error_reporting() set to 2047 (all errors, warnings etc). 

What version of PHP are you on, by the way?

You _can_ override this with the latest Alpha: just overwrite your files with everything in the latest alpha package (https://formtools.org/download/alpha.php) and add the following line to your `/global/config.php` file:

```$g_default_error_reporting = 1;```

But I'd still contact your hosting provider. This may be a symptom of something more sinister going on...! :)

**Comment by benkeen** [comment]
Hope this got solved! I'm just doing some spring cleaning & will close this based on the above.
