### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY093]:

### ISSUE THREAD

**Issue by dvddrn8** [formtools/core#799]
This message comes up when Publish this form is pressed.  First time creating and evaluating Form Tools.  I did select Form Builder to create a new form.
Is Form Builder a purchased module?
@dvddrn8
[Error HY093 using Form Builder.txt](https://github.com/formtools/core/files/6711736/Error.HY093.using.Form.Builder.txt)

**Comment by sys-int2021** [comment]
Just installed formtools for the first time and got the same error.

I resolved it as follows:

1.    Open file: formtools\global\code\Views.class.php
2.    Goto line 911
3.    Change the $ in front of form_id to :
       so it reads WHERE v.form_id = :form_id
4.    Save the file
5.    Restart your webserver (ie Apache)

The form builder popup will now be displayed.

**Comment by dvddrn8** [comment]
Thank you for your input on this error.
My PHP file Views.class.php must have been already corrected at time of my download.
It reads:
                SELECT *
                FROM   {PREFIX}views v, {PREFIX}list_groups lg
                WHERE  v.form_id = $form_id AND
                       v.group_id = lg.group_id
                ORDER BY lg.list_order, v.view_order

I checked every occurrence of ‘form_id’ in the PHP file and they are correct.

Hopefully someone would find a  specific fix to my error.  In the mean time I will continue in trying to find the cause of my error.

David Duran
***@***.******@***.***>

***@***.***D76BFE.33453DC0]
Industrial Electronics Services, Inc
Physical Address: 122 Kwickway Lane, Gray, TN 37615
Phone: 423-477-0118
Fax: 423-477-8700
Web: www.iesgray.com<http://www.iesgray.com/>

Mailing Address: 213 Suncrest Street, Gray, TN 37615
***@***.******@***.***D76BFE.33453DC0]

**Comment by sys-int2021** [comment]
Your WHERE statement is saying $form_id
this is wrong, it should say :form_id as it is placeholder for a variable used within a prepare statement.
If you follow the instructions given you will find it corrects this error.

**Comment by dvddrn8** [comment]
You are correct. Thank you.
I need another cup of coffee.

It is great to have your support.  Many Thanks.


David Duran
***@***.******@***.***>

***@***.***D76C00.DAD7BB10]
Industrial Electronics Services, Inc
Physical Address: 122 Kwickway Lane, Gray, TN 37615
Phone: 423-477-0118
Fax: 423-477-8700
Web: www.iesgray.com<http://www.iesgray.com/>

Mailing Address: 213 Suncrest Street, Gray, TN 37615
***@***.******@***.***D76C00.DAD7BB10]
