### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by Klemens-sz** [formtools/core#817]
When are Formtools planned to be adapted and made available for the already released PHP version 8.0?

**Comment by benkeen** [comment]
Hey @Klemens-sz, I just released 3.1.0. It's running fine for me on PHP 8.2, but do let me know if you spot any problems. You can download the new version on the main download page here: https://formtools.org/download/ - but I'll be updating the Upgrade page in coming days to explain why the upgrade functionality is no longer automated.

As I [posted on the website](https://formtools.org/news/) I'll be sticking around for bug fixes from here on out.
