### ISSUE TITLE
Email doesn`t work when Name is set in the From field

### ISSUE THREAD

**Issue by stenioaraujo** [formtools/core#85]
Formtools 2.2.6
Using PHP::mail() and msmtp to send an email.

When I am setting up the Recipient(s) for the email configuration for a Form, it is asked a From for the email. If I set a name and an email, the mail() function sends the emails, but they are not accepted by Gmail. Gmail rejects the email because it has more than one from emails in the From header.

> Messages with multiple addresses in From: 550 5.7.1 header are not accepted

Looking the failed email's header I saw that it was added the following:

> From: Mr Example <mr@example.com>, Mr Example, mr@example.com

However, if I leave the field Name empty, the email is sent, and From header only has one information, the email.

**Comment by benkeen** [comment]
Hmm, thanks @stenioaraujo! Kinda surprised this is an issue - I thought this has been tried + tested a long time ago. 

I'm just working on FT3 alpha at the moment and I'm turning to the email functionality this week. I'll check it out then and get back to you. If it's a bug, I won't be releasing any more FT2 versions - but I'll let you know how to manually patch it. 

Speak soon.

**Comment by stenioaraujo** [comment]
Thank you benkeen, If it is indeed a bug, I will be happy to help in any way.

**Comment by benkeen** [comment]
Apologies, I haven't gotten to this yet. Haven't forgotten - it's on my list. :)

**Comment by benkeen** [comment]
Flagged as bug so I won't lose this ticket, sorry I haven't gotten to it yet........

**Comment by benkeen** [comment]
Closing. Do comment or open another ticket if I'm incorrect about you using `mail()`, but I'm afraid there's nothing that can be done about the mail function inconsistencies.
