### ISSUE TITLE
Field validation doesn't work Ver. 3.0.20

### ISSUE THREAD

**Issue by whatusernameisavailabletoday** [formtools/core#878]
I have tiny contact form, four fields, all set to required, but doesn't works.
External form, website is in different country, different server.
Doesn't work means anybody can send empty forms or wrong type of input (letters required but accepts numbers).

**Comment by benkeen** [comment]
Field validation is actually only for Form Builder or internal forms, not external ones - sorry. With external forms you have to control the forms completely yourself - including adding the validation on your end. Sorry about that!
