### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by benkeen** [formtools/core#879]
Alrighty... time to leap back into this sucker. Look into this this year once [generatedata.com](https://github.com/benkeen/generatedata) 4.1 is released and stable.

**Comment by koacamper** [comment]
This is great news!

**Comment by nicktalsma** [comment]
This is awesome news!   I literally just got word from my host this morning they are discontinuing support for PHP 7.4.  

@benkeen any idea when FormTools might be updated by?  And thank you so much for all you've done!!

**Comment by benkeen** [comment]
Thanks! :)

The challenge is time... I have to do an update for generatedata.com in the next little while to accommodate some changing Google APIs and then I need to spend some time with some iNaturalist.org problems, but I'll be getting into this after that. Shouldn't be too long. I'll post here when I know something more concrete.

**Comment by gummisko** [comment]
Would indeed be so very awesom Ben! Thank you!
Gerard

**Comment by benkeen** [comment]
I should be wrapping up my other work this weekend, so I'll be getting to it after that. :)

**Comment by Sandy-Spence** [comment]
Wow!

**Comment by nicktalsma** [comment]
> I should be wrapping up my other work this weekend, so I'll be getting to it after that. :)

This literally just made my day hearing this!!  Thank you again Ben!

**Comment by koacamper** [comment]
Are you still accepting donations for this project through the formtools.org site?  I'd like to donate to the cause.  Thank you again for this wonderful program!

**Comment by benkeen** [comment]
Thanks, that's kind @koacamper. But I'm afraid that the donation form is a little out of date! Clearly I need to update that too. ;-)

**Comment by koacamper** [comment]
> 

Let me know when the donations section is updated.  Thank you again.

**Comment by benkeen** [comment]
I've created a separate ticket here to track my progress + take notes. 
https://github.com/formtools/core/issues/892

Lots to do, but on the bright side I'm not sure there will be _too_ much to do for the actual PHP8 update. I've already gotten the bulk of the core application going, so it'll just be a matter of slogging through every piece of functionality and tweaking it as I go.

**Comment by benkeen** [comment]
Hey folks, I just released 3.1.0 of the core + a couple of update modules (Export Manager included). It's running fine for me on PHP 8.2, but do let me know if anyone spots any problems!

As I [posted on the website](https://formtools.org/news/) I'll be sticking around for bug fixes from here on out. :) I see a few listed in the issues list.

**Comment by nicktalsma** [comment]
@benkeen you are the man!!!  I will be trying the update soon.  It looks like I just need to download 3.1.0 from formtools.org, extract the contents of the zip file and upload to my server (overwriting existing files) in order to update? Backing everything up first of course...

**Comment by benkeen** [comment]
Hey! I updated the upgrade instructions here:
https://docs.formtools.org/upgrading/

 I _do_ miss the automatic upgrade script, but that's non-functional now. I'll be updating that page today to link to the new instructions. 

But yes, that's the gist of it - just uploading the new version + overwriting the old ones. :) You can download the new code version on the download page. 

Let me know if you have any trouble!

**Comment by nicktalsma** [comment]
@benkeen 

Upgrade page mentions upgrading to 3.1.5, but isn’t 3.1.0 the latest release that just came out? 

https://docs.formtools.org/upgrading/3_1_5/

**Comment by benkeen** [comment]
Good grief, you just found a very old documentation bug. Apologies! The doc is wrong - it should read 3.0.15, not 3.1.5. I'll update that shortly. 

Yup, 3.1.0 is the latest version.

**Comment by benkeen** [comment]
Sorry folks, but just a heads up that a couple of other issues were spotted around PHP 8 compatibility, so I released 3.1.1 to patch it - plus a few modules. They're all downloadable via the main website. 

I posted about it on the main website. I'll continue announcing all updates there in future.
https://formtools.org/news/

Thanks!

**Comment by benkeen** [comment]
Good to hear! Yes, let me know about the emails. I've been a little swamped this week but I can take a look a bit later too.

**Comment by Sandy-Spence** [comment]
Good Morning Ben,

Thank you once again for all that you do.

Regards,

Sandy
