### ISSUE TITLE
Form Tools Core (3.0.0-alpha-20171023) no dropdown/radio list selections 

### ISSUE THREAD

**Issue by djdadevil** [formtools/core#88]
I am using the latest version of Form Tools Alpha 3.0 (released 23-10-2017) removed data visualisation before install, installed it fine, starting making a form, either one thing not working. Defining new dropdown/option list or radio button selection, it says faulty action and leads me to my standard 404 page on my domain. When clicking back all is fine, either still can't make dropdown/optional list structure or radio button structure.

 Anyone with a solution?

 Dropdown setting list points to .../formtools/admin/forms/edit/?form_id=1#
 Radio button option list points to .../formtools/admin/forms/edit/?form_id=1#

 Is this correct?

**Comment by djdadevil** [comment]
Oh, never mind, I saw this problem yesterday, and there wasn't a selection box. Now I see it and I can put in Option lists, so sorry for putting this here, it's solved automaticly. Was probably a old browser related issue! :)

**Comment by djdadevil** [comment]
Aah, spoke to early, could only apply 1 option list, problem still persists. :(

**Comment by benkeen** [comment]
Hey @djdadevil - ah drat! Possibly I introduced an issue in my last version. I did some refactoring of some of the code in that section - I'll take a look. Thanks for letting me know!

**Comment by benkeen** [comment]
Ah I see - actually it's just a broken link within the script. I've just fixed it locally and it'll be in the next build. In the meantime, you can bypass the issue by creating your Option Lists separately in the Forms -> Option Lists page (left nav). After they're created, you can go back to Edit Form -> Fields -> edit field dialog and you'll see your option lists listed there to select. 

Hop this helps.

**Comment by benkeen** [comment]
This is fixed in 3.0.0-alpha-20171029. Let me know if the problem persists.

**Comment by djdadevil** [comment]
Dear Ben,

Thank you very very much! :D:D:D I can confirm that it's working now! I apreciate your work very much! Would be great if Form Maker and Data Visualisation plugins are coming soon. I Wish you best of luck!

Your's Sincerely,

_Mark (aka djdadevil)
