### ISSUE TITLE
When changing a submission, Form Tools ends up in a empty page

### ISSUE THREAD

**Issue by joklu** [formtools/core#907]
When I am in a submission itself, e.g. admin/forms/edit_submission.php?form_id=7&view_id=6&submission_id=119
And then click Update with a change in one of the fields
Form Tools shows an empty page and does not update the submission. The URL in the browser remains the same.
Any idea how I can solve this?

**Comment by benkeen** [comment]
Hi @joklu, did it always do this or just recently? A blank page almost always means there's a server-side error and the page can't render. Try this: edit your `/global/config.php` file and add the following line:

```php
$g_default_error_reporting = 2047;
```

([Doc on that file here](https://docs.formtools.org/userdoc/getting_started/config_file/)). Then try the action again and see if it outputs any errors to the screen.

**Comment by joklu** [comment]
Hi Ben, thanks a lot for your prompt answer. Indeed it showed an error and turned out I forgot to install submission_pre_parser module after updating. Working again now, thanks!

**Comment by benkeen** [comment]
Great stuff!
