### ISSUE TITLE
Modules - Refresh Modules List

### ISSUE THREAD

**Issue by ocbroadband** [formtools/core#94]
Hi,

Not sure if this is a bug, or it has to do with PHP.  On the modules page, if I click 'Refresh Modules List', the system comes back with an error page with the following...

> Either the theme cache folder doesn't have write-permissions, or your $g_root_dir value is invalid. Please update the /themes/cache/ to have full read-write permissions (777 on unix).

The folder being referenced in the error does in fact have 777 for the permissions.

PHP version is 7.0.24

**Comment by benkeen** [comment]
Thanks @ocbroadband! Does this occur every time you click that button? I've seen that same error at that page, but it's been erratic for me - there's clearly something wrong, I just haven't identified it yet.

**Comment by ocbroadband** [comment]
For me it does.  I'll send you a account to login.

**Comment by benkeen** [comment]
Thanks! I just encountered the same issue, but in an unrelated part of the codebase. There seems to be a bug with the settings update function... can't quite find the sucker, but it's here somewhere. But I should be able to patch it in the next version. I'll leave this ticket open until then.

**Comment by benkeen** [comment]
Hmm, I found one issue which is now patched, but I'm not sure if it would have caused the issue you posted. One thing: would you mind logging out then in again and immediately click the Refresh Modules list - same problem?

If you're still seeing it & don't mind me taking a look, sending me the creds would be great! [ben.keen@gmail.com].

**Comment by ocbroadband** [comment]
Same issue.  Closed all browsers and started with clean launch, logged in,
went straight to Modules -> Refresh.   Error page appears.  I'll send the
creds in a different email.

**Comment by benkeen** [comment]
Did this problem stick around? I've never encountered it myself, unfortunately. I'll close this ticket if not.
