### ISSUE TITLE
Modules - TinyMCE field

### ISSUE THREAD

**Issue by ocbroadband** [formtools/core#95]
When changing from 'simple' to any other level,(basic, advanced, expert), the system fails with an error.

> Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined in /home/thedoves/www/ft3/global/code/Database.class.php:116 Stack trace: #0 /home/thedoves/www/ft3/global/code/Database.class.php(116): PDOStatement->bindValue('default_value', 'advanced', 2) #1 /home/thedoves/www/ft3/global/code/Database.class.php(121): FormTools\Database->bind('default_value', 'advanced') #2 /home/thedoves/www/ft3/modules/field_type_tinymce/code/Module.class.php(199): FormTools\Database->bindAll(Array) #3 /home/thedoves/www/ft3/modules/field_type_tinymce/index.php(13): FormTools\Modules\FieldTypeTinymce\Module->updateSettings(Array) #4 {main} thrown in /home/thedoves/www/ft3/global/code/Database.class.php on line 116

**Comment by benkeen** [comment]
Just pushed a fix to the https://github.com/formtools/module-field_type_tinymce repo - I'll update the main download tomorrow. Thanks, @ocbroadband!

**Comment by ocbroadband** [comment]
Issue resolved.
